import { Task } from './task.model';

export const TASKS: Task[] = [
  {
    id: '41',
    executionComments: '',
    taskComments: '',
    startDate: '4/18/2020 11:15 AM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'General',
    associatedLink: '',
    priority: 'Normal',
    type: 'generate surveillance report',
    creator: 'S O',
    district: '',
    region: '',
    dueDate: '4/17/2020 11:15 AM',
    status: 'pending',
  },
  {
    id: '42',
    executionComments: '',
    taskComments: '',
    startDate: '4/16/2020 4:53 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Case',
    associatedLink: '<a title="XRBCJN-JJSBY3-DJCXI6-FZMEKGJA">XRBCJN</a> (XRBCJN)',
    priority: 'Normal',
    type: 'contact tracing',
    creator: 'Test 60',
    district: 'SK Berlin Pankow',
    region: 'Berlin',
    dueDate: '4/16/2020 12:15 PM',
    status: 'pending',
  },
  {
    id: '43',
    executionComments: '',
    taskComments: '',
    startDate: '4/15/2020 10:12 AM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="WJCITY-BPB6MS-NOC4AX-EHM5SPQM">WJCITY</a> (WJCITY)',
    priority: 'High',
    type: 'contact follow up',
    creator: 'Surveillance SUPERVISOR',
    district: 'SK Berlin Mitte',
    region: 'Berlin',
    dueDate: '4/10/2020 9:45 AM',
    status: 'done',
  },
  {
    id: '44',
    executionComments: 'review durchführen',
    taskComments: '',
    startDate: '4/12/2020 9:35 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="TV2R6Z-PWNX4Q-UJWIMD-TXXVKGE4">TV2R6Z</a> (TV2R6Z)',
    priority: 'Normal',
    type: 'other task as described in comments',
    creator: 'ad MIN',
    district: '',
    region: 'Berlin',
    dueDate: '4/11/2020 9:35 PM',
    status: 'pending',
  },
  {
    id: '45',
    executionComments: '',
    taskComments: '',
    startDate: '4/10/2020 4:36 PM',
    assignee: 'Surveillance OFFICER (4)',
    context: 'Case',
    associatedLink: '<a title="UL6O4U-2XEYCK-ZX4FPU-VQ7WKKPE">UL6O4U</a> (test TESTER (UL6O4U))',
    priority: 'Normal',
    type: 'case investigation',
    creator: ' ',
    district: 'Default District_old',
    region: 'Default Region_old',
    dueDate: '4/9/2020 4:36 PM',
    status: 'pending',
  },
  {
    id: '46',
    executionComments: '',
    taskComments: '',
    startDate: '4/10/2020 11:51 AM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Case',
    associatedLink: '<a title="STLXQD-JCO7CA-OPVTTD-QARACKFQ">STLXQD</a> (STLXQD)',
    priority: 'Normal',
    type: 'case management',
    creator: 'Test 45',
    district: 'SK Berlin Treptow-Köpenick',
    region: 'Berlin',
    dueDate: '4/9/2020 11:51 AM',
    status: 'pending',
  },
  {
    id: '47',
    executionComments: '',
    taskComments: '',
    startDate: '4/9/2020 2:52 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Case',
    associatedLink: '<a title="THVEZU-O2CFFT-XT2LIP-6T3XCGWI">THVEZU</a> (THVEZU)',
    priority: 'Normal',
    type: 'case investigation',
    creator: ' ',
    district: 'LK Meißen',
    region: 'Sachsen',
    dueDate: '4/8/2020 2:52 PM',
    status: 'pending',
  },
  {
    id: '48',
    executionComments: '',
    taskComments: '',
    startDate: '4/8/2020 2:46 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="WZLCKX-B7WVCY-EV6T4T-N67D2PUU">WZLCKX</a> (WZLCKX)',
    priority: 'High',
    type: 'contact follow up',
    creator: 'Test 48',
    district: 'SK Berlin Mitte',
    region: 'Berlin',
    dueDate: '4/7/2020 2:46 PM',
    status: 'pending',
  },
  {
    id: '49',
    executionComments: '',
    taskComments: '',
    startDate: '4/8/2020 2:37 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="SIBJMH-YQNAND-GAFXUK-42WNCGVQ">SIBJMH</a> (SIBJMH)',
    priority: 'Normal',
    type: 'contact follow up',
    creator: 'Test 48',
    district: 'SK Berlin Mitte',
    region: 'Berlin',
    dueDate: '4/7/2020 2:37 PM',
    status: 'pending',
  },
  {
    id: '50',
    executionComments: 'Q aufheben',
    taskComments: '',
    startDate: '4/7/2020 7:30 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="QHONLA-KOKROW-5KKWY2-HS642NDA">QHONLA</a> (QHONLA)',
    priority: 'High',
    type: 'other task as described in comments',
    creator: 'Test 44',
    district: 'SK Berlin Mitte',
    region: 'Berlin',
    dueDate: '4/7/2020 2:46 PM',
    status: 'pending',
  },
  {
    id: '51',
    executionComments: 'huhu',
    taskComments: '',
    startDate: '3/25/2020 1:19 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Case',
    associatedLink: '<a title="SCQ4OF-EXC7XQ-YJYLV7-AEERSHK4">SCQ4OF</a> (SCQ4OF)',
    priority: 'Normal',
    type: 'contact tracing',
    creator: 'bsiSS BSISS',
    district: 'LK Gießen_old',
    region: 'Hessen',
    dueDate: '3/24/2020 1:19 PM',
    status: 'done',
  },
  {
    id: '52',
    executionComments: '',
    taskComments: '',
    startDate: '3/22/2020 1:48 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Case',
    associatedLink: '<a title="TGHXEL-QGRDNJ-37Z4VA-QNJYKKHE">TGHXEL</a> (TGHXEL)',
    priority: 'Normal',
    type: 'sample collection',
    creator: 'Surveillance SUPERVISOR',
    district: 'SK Berlin Steglitz-Zehlendorf_old',
    region: 'Berlin',
    dueDate: '3/21/2020 1:48 PM',
    status: 'done',
  },
  {
    id: '53',
    executionComments: 'Telefonbuchabfrage',
    taskComments: '',
    startDate: '3/20/2020 2:01 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="UVMBCB-AFAIII-WZYZFQ-OKW42BLE">UVMBCB</a> (UVMBCB)',
    priority: 'Normal',
    type: 'contact follow up',
    creator: 'Test 9',
    district: '',
    region: '',
    dueDate: '3/20/2020 2:01 PM',
    status: 'pending',
  },
  {
    id: '54',
    executionComments: '',
    taskComments: '',
    startDate: '3/20/2020 1:56 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="V4GZ36-GRWRS4-LPEECA-234G2J2M">V4GZ36</a> (V4GZ36)',
    priority: 'Normal',
    type: 'contact follow up',
    creator: 'Test 9',
    district: '',
    region: '',
    dueDate: '3/20/2020 2:00 AM',
    status: 'pending',
  },
  {
    id: '55',
    executionComments: '',
    taskComments: '',
    startDate: '3/20/2020 9:10 AM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="U2HQM3-5HQJPD-OLIBDM-A6NVCA7M">U2HQM3</a> (U2HQM3)',
    priority: 'Normal',
    type: 'contact follow up',
    creator: 'GesundMitarbeiter 8',
    district: '',
    region: '',
    dueDate: '3/20/2020 9:10 AM',
    status: 'pending',
  },
  {
    id: '56',
    executionComments: '',
    taskComments: '',
    startDate: '3/19/2020 11:59 PM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="U2HQM3-5HQJPD-OLIBDM-A6NVCA7M">U2HQM3</a> (U2HQM3)',
    priority: 'Normal',
    type: 'contact follow up',
    creator: ' ',
    district: '',
    region: '',
    dueDate: '3/19/2020 12:00 AM',
    status: 'pending',
  },
  {
    id: '57',
    executionComments: 'Bitte untersuchen. Kann zuhause erfolgen.',
    taskComments: '',
    startDate: '3/17/2020 10:17 AM',
    assignee: 'Case SUPERVISOR (53)',
    context: 'Contact',
    associatedLink: '<a title="QYFE52-VNG73U-BOG6XW-RPJHSCQM">QYFE52</a> (QYFE52)',
    priority: 'Normal',
    type: 'contact investigation',
    creator: 'GesundMitarbeiter 6',
    district: '',
    region: '',
    dueDate: '3/16/2020 10:17 AM',
    status: 'pending',
  },
];
