/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ActionMeasure =
  | 'PROHIBITION_OF_ENTRY_AND_WORK_CASES'
  | 'SAMPLE_COLLECTION'
  | 'FORWARDING_TO_NATIONAL_REFERENCE_CENTER'
  | 'CONTACT_FOLLOW_UP'
  | 'VERIFICATION_OF_VACCINATION_IMMUNIZATION'
  | 'POST_EXPOSURE_PROPHYLAXIS_VACCINATION'
  | 'CLOSURE_OF_FACILITY'
  | 'PROHIBITION_OF_ENTRY_AND_WORK_CONTACTS'
  | 'POPULATION_INFORMATION'
  | 'OTHER';

export const ActionMeasure = {
  PROHIBITION_OF_ENTRY_AND_WORK_CASES: 'PROHIBITION_OF_ENTRY_AND_WORK_CASES' as ActionMeasure,
  SAMPLE_COLLECTION: 'SAMPLE_COLLECTION' as ActionMeasure,
  FORWARDING_TO_NATIONAL_REFERENCE_CENTER: 'FORWARDING_TO_NATIONAL_REFERENCE_CENTER' as ActionMeasure,
  CONTACT_FOLLOW_UP: 'CONTACT_FOLLOW_UP' as ActionMeasure,
  VERIFICATION_OF_VACCINATION_IMMUNIZATION: 'VERIFICATION_OF_VACCINATION_IMMUNIZATION' as ActionMeasure,
  POST_EXPOSURE_PROPHYLAXIS_VACCINATION: 'POST_EXPOSURE_PROPHYLAXIS_VACCINATION' as ActionMeasure,
  CLOSURE_OF_FACILITY: 'CLOSURE_OF_FACILITY' as ActionMeasure,
  PROHIBITION_OF_ENTRY_AND_WORK_CONTACTS: 'PROHIBITION_OF_ENTRY_AND_WORK_CONTACTS' as ActionMeasure,
  POPULATION_INFORMATION: 'POPULATION_INFORMATION' as ActionMeasure,
  OTHER: 'OTHER' as ActionMeasure,
};
