/* eslint-disable @typescript-eslint/no-redeclare */

export type ActionMeasure =
  | 'PROHIBITION_OF_ENTRY_AND_WORK_CASES'
  | 'SAMPLE_COLLECTION'
  | 'FORWARDING_TO_NATIONAL_REFERENCE_CENTER'
  | 'CONTACT_FOLLOW_UP'
  | 'VERIFICATION_OF_VACCINATION_IMMUNIZATION'
  | 'POST_EXPOSURE_PROPHYLAXIS_VACCINATION'
  | 'CLOSURE_OF_FACILITY'
  | 'PROHIBITION_OF_ENTRY_AND_WORK_CONTACTS'
  | 'POPULATION_INFORMATION'
  | 'OTHER';

export const ActionMeasure = {
  PROHIBITIONOFENTRYANDWORKCASES: 'PROHIBITION_OF_ENTRY_AND_WORK_CASES' as ActionMeasure,
  SAMPLECOLLECTION: 'SAMPLE_COLLECTION' as ActionMeasure,
  FORWARDINGTONATIONALREFERENCECENTER: 'FORWARDING_TO_NATIONAL_REFERENCE_CENTER' as ActionMeasure,
  CONTACTFOLLOWUP: 'CONTACT_FOLLOW_UP' as ActionMeasure,
  VERIFICATIONOFVACCINATIONIMMUNIZATION: 'VERIFICATION_OF_VACCINATION_IMMUNIZATION' as ActionMeasure,
  POSTEXPOSUREPROPHYLAXISVACCINATION: 'POST_EXPOSURE_PROPHYLAXIS_VACCINATION' as ActionMeasure,
  CLOSUREOFFACILITY: 'CLOSURE_OF_FACILITY' as ActionMeasure,
  PROHIBITIONOFENTRYANDWORKCONTACTS: 'PROHIBITION_OF_ENTRY_AND_WORK_CONTACTS' as ActionMeasure,
  POPULATIONINFORMATION: 'POPULATION_INFORMATION' as ActionMeasure,
  OTHER: 'OTHER' as ActionMeasure,
};
