/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ActivityAsCaseType =
  | 'WORK'
  | 'TRAVEL'
  | 'SPORT'
  | 'VISIT'
  | 'GATHERING'
  | 'HABITATION'
  | 'PERSONAL_SERVICES'
  | 'OTHER'
  | 'UNKNOWN';

export const ActivityAsCaseType = {
  WORK: 'WORK' as ActivityAsCaseType,
  TRAVEL: 'TRAVEL' as ActivityAsCaseType,
  SPORT: 'SPORT' as ActivityAsCaseType,
  VISIT: 'VISIT' as ActivityAsCaseType,
  GATHERING: 'GATHERING' as ActivityAsCaseType,
  HABITATION: 'HABITATION' as ActivityAsCaseType,
  PERSONALSERVICES: 'PERSONAL_SERVICES' as ActivityAsCaseType,
  OTHER: 'OTHER' as ActivityAsCaseType,
  UNKNOWN: 'UNKNOWN' as ActivityAsCaseType,
};
