/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ActionMeasure =
  | 'PROHIBITION_OF_ENTRY_AND_WORK_CASES'
  | 'SAMPLE_COLLECTION'
  | 'FORWARDING_TO_NATIONAL_REFERENCE_CENTER'
  | 'CONTACT_FOLLOW_UP'
  | 'VERIFICATION_OF_VACCINATION_IMMUNIZATION'
  | 'POST_EXPOSURE_PROPHYLAXIS_VACCINATION'
  | 'CLOSURE_OF_FACILITY'
  | 'PROHIBITION_OF_ENTRY_AND_WORK_CONTACTS'
  | 'POPULATION_INFORMATION'
  | 'OTHER';
