/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AdditionalTestType =
  | 'HAEMOGLOBINURIA'
  | 'PROTEINURIA'
  | 'HEMATURIA'
  | 'ARTERIAL_VENOUS_BLOOD_GAS'
  | 'ALT_SGPT'
  | 'AST_SGOT'
  | 'CREATININE'
  | 'POTASSIUM'
  | 'UREA'
  | 'HAEMOGLOBIN'
  | 'TOTAL_BILIRUBIN'
  | 'CONJ_BILIRUBIN'
  | 'WBC_COUNT'
  | 'PLATELETS'
  | 'PROTHROMBIN_TIME';
