/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AdditionalTestingStatus = 'NOT_REQUESTED' | 'REQUESTED' | 'PERFORMED';

export const AdditionalTestingStatus = {
  NOT_REQUESTED: 'NOT_REQUESTED' as AdditionalTestingStatus,
  REQUESTED: 'REQUESTED' as AdditionalTestingStatus,
  PERFORMED: 'PERFORMED' as AdditionalTestingStatus,
};
