/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AnimalCondition = 'ALIVE' | 'DEAD' | 'PROCESSED' | 'UNKNOWN';

export const AnimalCondition = {
  ALIVE: 'ALIVE' as AnimalCondition,
  DEAD: 'DEAD' as AnimalCondition,
  PROCESSED: 'PROCESSED' as AnimalCondition,
  UNKNOWN: 'UNKNOWN' as AnimalCondition,
};
