/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AnimalContactType = 'BITE' | 'TOUCH' | 'SCRATCH' | 'LICK' | 'OTHER';

export const AnimalContactType = {
  BITE: 'BITE' as AnimalContactType,
  TOUCH: 'TOUCH' as AnimalContactType,
  SCRATCH: 'SCRATCH' as AnimalContactType,
  LICK: 'LICK' as AnimalContactType,
  OTHER: 'OTHER' as AnimalContactType,
};
