/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ArmedForcesRelationType = 'UNKNOWN' | 'NO_RELATION' | 'CIVIL' | 'SOLDIER_OR_RELATIVE';

export const ArmedForcesRelationType = {
  UNKNOWN: 'UNKNOWN' as ArmedForcesRelationType,
  NO_RELATION: 'NO_RELATION' as ArmedForcesRelationType,
  CIVIL: 'CIVIL' as ArmedForcesRelationType,
  SOLDIER_OR_RELATIVE: 'SOLDIER_OR_RELATIVE' as ArmedForcesRelationType,
};
