/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CampaignFormDataEntry } from './campaignFormDataEntry';
import { CampaignFormMetaReferenceDto } from './campaignFormMetaReferenceDto';
import { CampaignReferenceDto } from './campaignReferenceDto';
import { CommunityReferenceDto } from './communityReferenceDto';
import { DistrictReferenceDto } from './districtReferenceDto';
import { RegionReferenceDto } from './regionReferenceDto';
import { UserReferenceDto } from './userReferenceDto';

export interface CampaignFormDataDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  formValues?: Array<CampaignFormDataEntry>;
  campaign?: CampaignReferenceDto;
  campaignFormMeta?: CampaignFormMetaReferenceDto;
  formDate?: Date;
  region?: RegionReferenceDto;
  district?: DistrictReferenceDto;
  community?: CommunityReferenceDto;
  creatingUser?: UserReferenceDto;
}
