/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CaseIdentificationSource =
  | 'UNKNOWN'
  | 'OUTBREAK_INVESTIGATION'
  | 'CONTACT_TRACKING_APP'
  | 'SUSPICION_REPORT'
  | 'CONTACT_TRACING'
  | 'SCREENING'
  | 'OTHER';

export const CaseIdentificationSource = {
  UNKNOWN: 'UNKNOWN' as CaseIdentificationSource,
  OUTBREAK_INVESTIGATION: 'OUTBREAK_INVESTIGATION' as CaseIdentificationSource,
  CONTACT_TRACKING_APP: 'CONTACT_TRACKING_APP' as CaseIdentificationSource,
  SUSPICION_REPORT: 'SUSPICION_REPORT' as CaseIdentificationSource,
  CONTACT_TRACING: 'CONTACT_TRACING' as CaseIdentificationSource,
  SCREENING: 'SCREENING' as CaseIdentificationSource,
  OTHER: 'OTHER' as CaseIdentificationSource,
};
