/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CaseClassification =
  | 'NOT_CLASSIFIED'
  | 'SUSPECT'
  | 'PROBABLE'
  | 'CONFIRMED'
  | 'CONFIRMED_NO_SYMPTOMS'
  | 'CONFIRMED_UNKNOWN_SYMPTOMS'
  | 'NO_CASE';

export const CaseClassification = {
  NOT_CLASSIFIED: 'NOT_CLASSIFIED' as CaseClassification,
  SUSPECT: 'SUSPECT' as CaseClassification,
  PROBABLE: 'PROBABLE' as CaseClassification,
  CONFIRMED: 'CONFIRMED' as CaseClassification,
  CONFIRMED_NO_SYMPTOMS: 'CONFIRMED_NO_SYMPTOMS' as CaseClassification,
  CONFIRMED_UNKNOWN_SYMPTOMS: 'CONFIRMED_UNKNOWN_SYMPTOMS' as CaseClassification,
  NO_CASE: 'NO_CASE' as CaseClassification,
};
