/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CaseOutcome = 'NO_OUTCOME' | 'DECEASED' | 'RECOVERED' | 'UNKNOWN';

export const CaseOutcome = {
  NOOUTCOME: 'NO_OUTCOME' as CaseOutcome,
  DECEASED: 'DECEASED' as CaseOutcome,
  RECOVERED: 'RECOVERED' as CaseOutcome,
  UNKNOWN: 'UNKNOWN' as CaseOutcome,
};
