/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CaseOrigin = 'IN_COUNTRY' | 'POINT_OF_ENTRY';

export const CaseOrigin = {
  IN_COUNTRY: 'IN_COUNTRY' as CaseOrigin,
  POINT_OF_ENTRY: 'POINT_OF_ENTRY' as CaseOrigin,
};
