/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgeAndBirthDateDto } from './ageAndBirthDateDto';
import { CaseClassification } from './caseClassification';
import { CaseOutcome } from './caseOutcome';
import { Disease } from './disease';
import { DiseaseVariant } from './diseaseVariant';
import { ExternalShareStatus } from './externalShareStatus';
import { FollowUpStatus } from './followUpStatus';
import { InvestigationStatus } from './investigationStatus';
import { PresentCondition } from './presentCondition';
import { Sex } from './sex';
import { SymptomJournalStatus } from './symptomJournalStatus';
import { VaccinationStatus } from './vaccinationStatus';

export interface CaseIndexDto {
  pseudonymized?: boolean;
  id?: number;
  uuid?: string;
  epidNumber?: string;
  externalID?: string;
  externalToken?: string;
  internalToken?: string;
  personFirstName?: string;
  personLastName?: string;
  disease?: Disease;
  diseaseVariant?: DiseaseVariant;
  diseaseDetails?: string;
  caseClassification?: CaseClassification;
  investigationStatus?: InvestigationStatus;
  presentCondition?: PresentCondition;
  reportDate?: Date;
  creationDate?: Date;
  healthFacilityName?: string;
  pointOfEntryName?: string;
  surveillanceOfficerUuid?: string;
  outcome?: CaseOutcome;
  sex?: Sex;
  ageAndBirthDate?: AgeAndBirthDateDto;
  completeness?: number;
  quarantineTo?: Date;
  followUpStatus?: FollowUpStatus;
  followUpUntil?: Date;
  symptomJournalStatus?: SymptomJournalStatus;
  vaccinationStatus?: VaccinationStatus;
  visitCount?: number;
  surveillanceToolLastShareDate?: Date;
  surveillanceToolShareCount?: number;
  surveillanceToolStatus?: ExternalShareStatus;
  responsibleRegionUuid?: string;
  responsibleDistrictUuid?: string;
  regionUuid?: string;
  districtUuid?: string;
  responsibleDistrictName?: string;
  inJurisdiction?: boolean;
}
