/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClinicalCourseReferenceDto } from './clinicalCourseReferenceDto';
import { Disease } from './disease';
import { SymptomsDto } from './symptomsDto';

export interface ClinicalVisitDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  clinicalCourse?: ClinicalCourseReferenceDto;
  symptoms?: SymptomsDto;
  disease?: Disease;
  visitDateTime?: Date;
  visitingPerson?: string;
  visitRemarks?: string;
}
