/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CompatibilityCheckResponse = 'COMPATIBLE' | 'TOO_OLD' | 'TOO_NEW';

export const CompatibilityCheckResponse = {
  COMPATIBLE: 'COMPATIBLE' as CompatibilityCheckResponse,
  TOOOLD: 'TOO_OLD' as CompatibilityCheckResponse,
  TOONEW: 'TOO_NEW' as CompatibilityCheckResponse,
};
