/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CongenitalHeartDiseaseType = 'PDA' | 'PPS' | 'VSD' | 'OTHER';

export const CongenitalHeartDiseaseType = {
  PDA: 'PDA' as CongenitalHeartDiseaseType,
  PPS: 'PPS' as CongenitalHeartDiseaseType,
  VSD: 'VSD' as CongenitalHeartDiseaseType,
  OTHER: 'OTHER' as CongenitalHeartDiseaseType,
};
