/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContactProximity =
  | 'TOUCHED_FLUID'
  | 'PHYSICAL_CONTACT'
  | 'CLOTHES_OR_OTHER'
  | 'CLOSE_CONTACT'
  | 'FACE_TO_FACE_LONG'
  | 'MEDICAL_UNSAFE'
  | 'SAME_ROOM'
  | 'AIRPLANE'
  | 'FACE_TO_FACE_SHORT'
  | 'MEDICAL_SAFE'
  | 'MEDICAL_SAME_ROOM'
  | 'AEROSOL'
  | 'MEDICAL_DISTANT'
  | 'MEDICAL_LIMITED';

export const ContactProximity = {
  TOUCHED_FLUID: 'TOUCHED_FLUID' as ContactProximity,
  PHYSICAL_CONTACT: 'PHYSICAL_CONTACT' as ContactProximity,
  CLOTHES_OR_OTHER: 'CLOTHES_OR_OTHER' as ContactProximity,
  CLOSE_CONTACT: 'CLOSE_CONTACT' as ContactProximity,
  FACE_TO_FACE_LONG: 'FACE_TO_FACE_LONG' as ContactProximity,
  MEDICAL_UNSAFE: 'MEDICAL_UNSAFE' as ContactProximity,
  SAME_ROOM: 'SAME_ROOM' as ContactProximity,
  AIRPLANE: 'AIRPLANE' as ContactProximity,
  FACE_TO_FACE_SHORT: 'FACE_TO_FACE_SHORT' as ContactProximity,
  MEDICAL_SAFE: 'MEDICAL_SAFE' as ContactProximity,
  MEDICAL_SAME_ROOM: 'MEDICAL_SAME_ROOM' as ContactProximity,
  AEROSOL: 'AEROSOL' as ContactProximity,
  MEDICAL_DISTANT: 'MEDICAL_DISTANT' as ContactProximity,
  MEDICAL_LIMITED: 'MEDICAL_LIMITED' as ContactProximity,
};
