/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContactCategory =
  | 'HIGH_RISK'
  | 'HIGH_RISK_MED'
  | 'MEDIUM_RISK_MED'
  | 'LOW_RISK'
  | 'NO_RISK';

export const ContactCategory = {
  HIGHRISK: 'HIGH_RISK' as ContactCategory,
  HIGHRISKMED: 'HIGH_RISK_MED' as ContactCategory,
  MEDIUMRISKMED: 'MEDIUM_RISK_MED' as ContactCategory,
  LOWRISK: 'LOW_RISK' as ContactCategory,
  NORISK: 'NO_RISK' as ContactCategory,
};
