/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseClassification } from './caseClassification';
import { CaseReferenceDto } from './caseReferenceDto';
import { ContactCategory } from './contactCategory';
import { ContactClassification } from './contactClassification';
import { ContactProximity } from './contactProximity';
import { ContactStatus } from './contactStatus';
import { Disease } from './disease';
import { FollowUpStatus } from './followUpStatus';
import { SymptomJournalStatus } from './symptomJournalStatus';
import { VaccinationStatus } from './vaccinationStatus';

export interface ContactIndexDto {
  pseudonymized?: boolean;
  uuid?: string;
  firstName?: string;
  lastName?: string;
  caze?: CaseReferenceDto;
  disease?: Disease;
  diseaseDetails?: string;
  lastContactDate?: Date;
  contactProximity?: ContactProximity;
  contactClassification?: ContactClassification;
  contactStatus?: ContactStatus;
  completeness?: number;
  followUpStatus?: FollowUpStatus;
  followUpUntil?: Date;
  symptomJournalStatus?: SymptomJournalStatus;
  vaccinationStatus?: VaccinationStatus;
  districtUuid?: string;
  contactOfficerUuid?: string;
  reportDateTime?: Date;
  contactCategory?: ContactCategory;
  caseClassification?: CaseClassification;
  visitCount?: number;
  externalID?: string;
  externalToken?: string;
  internalToken?: string;
  regionName?: string;
  districtName?: string;
  caseRegionName?: string;
  caseDistrictName?: string;
  inJurisdiction?: boolean;
  caseInJurisdiction?: boolean;
}
