/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseClassification } from './caseClassification';
import { CaseReferenceDto } from './caseReferenceDto';
import { CommunityReferenceDto } from './communityReferenceDto';
import { ContactCategory } from './contactCategory';
import { ContactClassification } from './contactClassification';
import { ContactRelation } from './contactRelation';
import { ContactStatus } from './contactStatus';
import { DateFilterOption } from './dateFilterOption';
import { Disease } from './disease';
import { DiseaseVariant } from './diseaseVariant';
import { DistrictReferenceDto } from './districtReferenceDto';
import { EntityRelevanceStatus } from './entityRelevanceStatus';
import { EventParticipantReferenceDto } from './eventParticipantReferenceDto';
import { EventReferenceDto } from './eventReferenceDto';
import { FollowUpStatus } from './followUpStatus';
import { PersonReferenceDto } from './personReferenceDto';
import { QuarantineType } from './quarantineType';
import { RegionReferenceDto } from './regionReferenceDto';
import { SymptomJournalStatus } from './symptomJournalStatus';
import { UserReferenceDto } from './userReferenceDto';
import { UserRole } from './userRole';
import { VaccinationStatus } from './vaccinationStatus';
import { YesNoUnknown } from './yesNoUnknown';

export interface ContactCriteria {
  reportingUserRole?: UserRole;
  disease?: Disease;
  diseaseVariant?: DiseaseVariant;
  caze?: CaseReferenceDto;
  resultingCase?: CaseReferenceDto;
  region?: RegionReferenceDto;
  district?: DistrictReferenceDto;
  community?: CommunityReferenceDto;
  contactOfficer?: UserReferenceDto;
  contactClassification?: ContactClassification;
  contactStatus?: ContactStatus;
  followUpStatus?: FollowUpStatus;
  reportDateFrom?: Date;
  reportDateTo?: Date;
  dateFilterOption?: DateFilterOption;
  followUpUntilFrom?: Date;
  followUpUntilTo?: Date;
  followUpVisitsFrom?: Date;
  followUpVisitsTo?: Date;
  followUpVisitsInterval?: number;
  followUpUntilToPrecise?: boolean;
  symptomJournalStatus?: SymptomJournalStatus;
  vaccinationStatus?: VaccinationStatus;
  relationToCase?: ContactRelation;
  lastContactDateFrom?: Date;
  lastContactDateTo?: Date;
  deleted?: boolean;
  nameUuidCaseLike?: string;
  relevanceStatus?: EntityRelevanceStatus;
  onlyHighPriorityContacts?: boolean;
  contactCategory?: ContactCategory;
  caseClassification?: CaseClassification;
  quarantineType?: QuarantineType;
  quarantineFrom?: Date;
  quarantineTo?: Date;
  onlyQuarantineHelpNeeded?: boolean;
  quarantineOrderedVerbally?: boolean;
  quarantineOrderedOfficialDocument?: boolean;
  quarantineNotOrdered?: boolean;
  withExtendedQuarantine?: boolean;
  withReducedQuarantine?: boolean;
  person?: PersonReferenceDto;
  birthdateYYYY?: number;
  birthdateMM?: number;
  birthdateDD?: number;
  returningTraveler?: YesNoUnknown;
  eventLike?: string;
  eventUuid?: string;
  includeContactsFromOtherJurisdictions?: boolean;
  onlyContactsSharingEventWithSourceCase?: boolean;
  eventParticipant?: EventParticipantReferenceDto;
  onlyContactsWithSourceCaseInGivenEvent?: EventReferenceDto;
  onlyContactsFromOtherInstances?: boolean;
  creationDateFrom?: Date;
  creationDateTo?: Date;
  reportingUserLike?: string;
}
