/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContactClassification = 'UNCONFIRMED' | 'CONFIRMED' | 'NO_CONTACT';

export const ContactClassification = {
  UNCONFIRMED: 'UNCONFIRMED' as ContactClassification,
  CONFIRMED: 'CONFIRMED' as ContactClassification,
  NO_CONTACT: 'NO_CONTACT' as ContactClassification,
};
