/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContactProximity =
  | 'TOUCHED_FLUID'
  | 'PHYSICAL_CONTACT'
  | 'CLOTHES_OR_OTHER'
  | 'CLOSE_CONTACT'
  | 'FACE_TO_FACE_LONG'
  | 'MEDICAL_UNSAFE'
  | 'SAME_ROOM'
  | 'AIRPLANE'
  | 'FACE_TO_FACE_SHORT'
  | 'MEDICAL_SAFE'
  | 'MEDICAL_SAME_ROOM'
  | 'AEROSOL'
  | 'MEDICAL_DISTANT'
  | 'MEDICAL_LIMITED';
