/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContactIdentificationSource =
  | 'CASE_PERSON'
  | 'CONTACT_PERSON'
  | 'TRACING_APP'
  | 'OTHER'
  | 'UNKNOWN';

export const ContactIdentificationSource = {
  CASE_PERSON: 'CASE_PERSON' as ContactIdentificationSource,
  CONTACT_PERSON: 'CONTACT_PERSON' as ContactIdentificationSource,
  TRACING_APP: 'TRACING_APP' as ContactIdentificationSource,
  OTHER: 'OTHER' as ContactIdentificationSource,
  UNKNOWN: 'UNKNOWN' as ContactIdentificationSource,
};
