/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContactCategory =
  | 'HIGH_RISK'
  | 'HIGH_RISK_MED'
  | 'MEDIUM_RISK_MED'
  | 'LOW_RISK'
  | 'NO_RISK';

export const ContactCategory = {
  HIGH_RISK: 'HIGH_RISK' as ContactCategory,
  HIGH_RISK_MED: 'HIGH_RISK_MED' as ContactCategory,
  MEDIUM_RISK_MED: 'MEDIUM_RISK_MED' as ContactCategory,
  LOW_RISK: 'LOW_RISK' as ContactCategory,
  NO_RISK: 'NO_RISK' as ContactCategory,
};
