export type CovidTestReason =
  | 'PRESENCE_OF_SYMPTOMS'
  | 'OUTBREAK_INVESTIGATION_SCREENING'
  | 'COHORT_SCREENING'
  | 'REQUIREMENT_OF_EMPLOYER'
  | 'DURING_QUARANTINE'
  | 'AFTER_CONTACT_TRACING'
  | 'SWISS_COVID_APP_NOTIFICATION'
  | 'OTHER_REASON';
