/* eslint-disable @typescript-eslint/no-redeclare */

export type CovidTestReason =
  | 'PRESENCE_OF_SYMPTOMS'
  | 'OUTBREAK_INVESTIGATION_SCREENING'
  | 'COHORT_SCREENING'
  | 'REQUIREMENT_OF_EMPLOYER'
  | 'DURING_QUARANTINE'
  | 'AFTER_CONTACT_TRACING'
  | 'SWISS_COVID_APP_NOTIFICATION'
  | 'OTHER_REASON';

export const CovidTestReason = {
  PRESENCEOFSYMPTOMS: 'PRESENCE_OF_SYMPTOMS' as CovidTestReason,
  OUTBREAKINVESTIGATIONSCREENING: 'OUTBREAK_INVESTIGATION_SCREENING' as CovidTestReason,
  COHORTSCREENING: 'COHORT_SCREENING' as CovidTestReason,
  REQUIREMENTOFEMPLOYER: 'REQUIREMENT_OF_EMPLOYER' as CovidTestReason,
  DURINGQUARANTINE: 'DURING_QUARANTINE' as CovidTestReason,
  AFTERCONTACTTRACING: 'AFTER_CONTACT_TRACING' as CovidTestReason,
  SWISSCOVIDAPPNOTIFICATION: 'SWISS_COVID_APP_NOTIFICATION' as CovidTestReason,
  OTHERREASON: 'OTHER_REASON' as CovidTestReason,
};
