/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RegionCriteria } from './regionCriteria';
import { SortProperty } from './sortProperty';

export interface CriteriaWithSortingRegionCriteria {
  criteria?: RegionCriteria;
  sortProperties?: Array<SortProperty>;
  caseCriteria?: RegionCriteria;
}
