/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomizableEnumTranslation } from './customizableEnumTranslation';
import { CustomizableEnumType } from './customizableEnumType';
import { Disease } from './disease';

export interface CustomizableEnumValueDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  dataType?: CustomizableEnumType;
  value?: string;
  caption?: string;
  translations?: Array<CustomizableEnumTranslation>;
  diseases?: Array<Disease>;
  description?: string;
  descriptionTranslations?: Array<CustomizableEnumTranslation>;
  properties?: { [key: string]: any };
}
