/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CustomizableEnumType = 'DISEASE_VARIANT' | 'SPECIFIC_EVENT_RISK';

export const CustomizableEnumType = {
  DISEASE_VARIANT: 'DISEASE_VARIANT' as CustomizableEnumType,
  SPECIFIC_EVENT_RISK: 'SPECIFIC_EVENT_RISK' as CustomizableEnumType,
};
