/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DengueFeverType = 'DENGUE_FEVER' | 'DENGUE_HEMORRHAGIC_FEVER' | 'DENUGE_SHOCK_SYNDROME';

export const DengueFeverType = {
  DENGUE_FEVER: 'DENGUE_FEVER' as DengueFeverType,
  DENGUE_HEMORRHAGIC_FEVER: 'DENGUE_HEMORRHAGIC_FEVER' as DengueFeverType,
  DENUGE_SHOCK_SYNDROME: 'DENUGE_SHOCK_SYNDROME' as DengueFeverType,
};
