/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DiseaseTransmissionMode =
  | 'HUMAN_TO_HUMAN'
  | 'ANIMAL'
  | 'ENVIRONMENT'
  | 'FOOD'
  | 'VECTOR_BORNE'
  | 'UNKNOWN';

export const DiseaseTransmissionMode = {
  HUMANTOHUMAN: 'HUMAN_TO_HUMAN' as DiseaseTransmissionMode,
  ANIMAL: 'ANIMAL' as DiseaseTransmissionMode,
  ENVIRONMENT: 'ENVIRONMENT' as DiseaseTransmissionMode,
  FOOD: 'FOOD' as DiseaseTransmissionMode,
  VECTORBORNE: 'VECTOR_BORNE' as DiseaseTransmissionMode,
  UNKNOWN: 'UNKNOWN' as DiseaseTransmissionMode,
};
