/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disease } from './disease';

export interface DiseaseConfigurationDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  disease?: Disease;
  active?: boolean;
  primaryDisease?: boolean;
  caseBased?: boolean;
  followUpEnabled?: boolean;
  followUpDuration?: number;
  caseFollowUpDuration?: number;
  eventParticipantFollowUpDuration?: number;
}
