/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EndOfIsolationReason = 'RECOVERED' | 'DIED' | 'LOST_TO_FOLLOW_UP' | 'OTHER';

export const EndOfIsolationReason = {
  RECOVERED: 'RECOVERED' as EndOfIsolationReason,
  DIED: 'DIED' as EndOfIsolationReason,
  LOSTTOFOLLOWUP: 'LOST_TO_FOLLOW_UP' as EndOfIsolationReason,
  OTHER: 'OTHER' as EndOfIsolationReason,
};
