/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EndOfQuarantineReason =
  | 'ASYMPTOMATIC'
  | 'ISOLATED_AS_CASE'
  | 'LOST_TO_FOLLOWUP'
  | 'OTHER';

export const EndOfQuarantineReason = {
  ASYMPTOMATIC: 'ASYMPTOMATIC' as EndOfQuarantineReason,
  ISOLATED_AS_CASE: 'ISOLATED_AS_CASE' as EndOfQuarantineReason,
  LOST_TO_FOLLOWUP: 'LOST_TO_FOLLOWUP' as EndOfQuarantineReason,
  OTHER: 'OTHER' as EndOfQuarantineReason,
};
