/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityAsCaseDto } from './activityAsCaseDto';
import { ExposureDto } from './exposureDto';
import { YesNoUnknown } from './yesNoUnknown';

export interface EpiDataDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  exposureDetailsKnown?: YesNoUnknown;
  activityAsCaseDetailsKnown?: YesNoUnknown;
  contactWithSourceCaseKnown?: YesNoUnknown;
  highTransmissionRiskArea?: YesNoUnknown;
  largeOutbreaksArea?: YesNoUnknown;
  areaInfectedAnimals?: YesNoUnknown;
  exposures?: Array<ExposureDto>;
  activitiesAsCase?: Array<ActivityAsCaseDto>;
}
