import { Disease } from './disease';
import { DiseaseTransmissionMode } from './diseaseTransmissionMode';
import { EventInvestigationStatus } from './eventInvestigationStatus';
import { EventReferenceDto } from './eventReferenceDto';
import { EventSourceType } from './eventSourceType';
import { EventStatus } from './eventStatus';
import { InstitutionalPartnerType } from './institutionalPartnerType';
import { LocationDto } from './locationDto';
import { MeansOfTransport } from './meansOfTransport';
import { RiskLevel } from './riskLevel';
import { TypeOfPlace } from './typeOfPlace';
import { UserReferenceDto } from './userReferenceDto';
import { WorkEnvironment } from './workEnvironment';
import { YesNoUnknown } from './yesNoUnknown';

export interface EventDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  superordinateEvent?: EventReferenceDto;
  eventStatus: EventStatus;
  riskLevel?: RiskLevel;
  eventInvestigationStatus?: EventInvestigationStatus;
  eventInvestigationStartDate?: Date;
  eventInvestigationEndDate?: Date;
  externalId?: string;
  externalToken?: string;
  eventTitle?: string;
  eventDesc: string;
  nosocomial?: YesNoUnknown;
  startDate?: Date;
  endDate?: Date;
  reportDateTime: Date;
  reportingUser: UserReferenceDto;
  evolutionDate?: Date;
  evolutionComment?: string;
  eventLocation?: LocationDto;
  typeOfPlace?: TypeOfPlace;
  meansOfTransport?: MeansOfTransport;
  meansOfTransportDetails?: string;
  connectionNumber?: string;
  travelDate?: Date;
  workEnvironment?: WorkEnvironment;
  srcType?: EventSourceType;
  srcInstitutionalPartnerType?: InstitutionalPartnerType;
  srcInstitutionalPartnerTypeDetails?: string;
  srcFirstName?: string;
  srcLastName?: string;
  srcTelNo?: string;
  srcEmail?: string;
  srcMediaWebsite?: string;
  srcMediaName?: string;
  srcMediaDetails?: string;
  disease?: Disease;
  diseaseDetails?: string;
  responsibleUser?: UserReferenceDto;
  typeOfPlaceText?: string;
  reportLat?: number;
  reportLon?: number;
  reportLatLonAccuracy?: number;
  transregionalOutbreak?: YesNoUnknown;
  diseaseTransmissionMode?: DiseaseTransmissionMode;
  multiDayEvent?: boolean;
}
