/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EventStatus = 'SIGNAL' | 'EVENT' | 'SCREENING' | 'CLUSTER' | 'DROPPED';

export const EventStatus = {
  SIGNAL: 'SIGNAL' as EventStatus,
  EVENT: 'EVENT' as EventStatus,
  SCREENING: 'SCREENING' as EventStatus,
  CLUSTER: 'CLUSTER' as EventStatus,
  DROPPED: 'DROPPED' as EventStatus,
};
