/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disease } from './disease';
import { EventReferenceDto } from './eventReferenceDto';
import { PathogenTestResultType } from './pathogenTestResultType';
import { PersonReferenceDto } from './personReferenceDto';
import { VaccinationStatus } from './vaccinationStatus';

export interface EventParticipantCriteria {
  event?: EventReferenceDto;
  person?: PersonReferenceDto;
  freeText?: string;
  birthdateYYYY?: number;
  birthdateMM?: number;
  birthdateDD?: number;
  onlyCountContactsWithSourceCaseInEvent?: boolean;
  disease?: Disease;
  pathogenTestResult?: PathogenTestResultType;
  vaccinationStatus?: VaccinationStatus;
  relevantDate?: Date;
  excludePseudonymized?: boolean;
  noResultingCase?: boolean;
}
