/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseReferenceDto } from './caseReferenceDto';
import { DistrictReferenceDto } from './districtReferenceDto';
import { EventReferenceDto } from './eventReferenceDto';
import { PersonDto } from './personDto';
import { RegionReferenceDto } from './regionReferenceDto';
import { SormasToSormasOriginInfoDto } from './sormasToSormasOriginInfoDto';
import { UserReferenceDto } from './userReferenceDto';
import { VaccinationStatus } from './vaccinationStatus';

export interface EventParticipantDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  reportingUser?: UserReferenceDto;
  event: EventReferenceDto;
  person: PersonDto;
  involvementDescription?: string;
  resultingCase?: CaseReferenceDto;
  region?: RegionReferenceDto;
  district?: DistrictReferenceDto;
  sormasToSormasOriginInfo?: SormasToSormasOriginInfoDto;
  ownershipHandedOver?: boolean;
  vaccinationStatus?: VaccinationStatus;
}
