/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disease } from './disease';
import { DiseaseVariant } from './diseaseVariant';
import { EventGroupsIndexDto } from './eventGroupsIndexDto';
import { EventIdentificationSource } from './eventIdentificationSource';
import { EventIndexLocation } from './eventIndexLocation';
import { EventInvestigationStatus } from './eventInvestigationStatus';
import { EventManagementStatus } from './eventManagementStatus';
import { EventSourceType } from './eventSourceType';
import { EventStatus } from './eventStatus';
import { ExternalShareStatus } from './externalShareStatus';
import { RiskLevel } from './riskLevel';
import { SpecificRisk } from './specificRisk';
import { UserReferenceDto } from './userReferenceDto';

export interface EventIndexDto {
  pseudonymized?: boolean;
  id?: number;
  uuid?: string;
  externalId?: string;
  externalToken?: string;
  internalToken?: string;
  eventStatus?: EventStatus;
  riskLevel?: RiskLevel;
  specificRisk?: SpecificRisk;
  eventInvestigationStatus?: EventInvestigationStatus;
  eventManagementStatus?: EventManagementStatus;
  participantCount?: number;
  caseCount?: number;
  deathCount?: number;
  contactCount?: number;
  contactCountSourceInEvent?: number;
  disease?: Disease;
  diseaseVariant?: DiseaseVariant;
  diseaseDetails?: string;
  startDate?: Date;
  endDate?: Date;
  evolutionDate?: Date;
  eventTitle?: string;
  eventLocation?: EventIndexLocation;
  srcType?: EventSourceType;
  srcFirstName?: string;
  srcLastName?: string;
  srcTelNo?: string;
  srcMediaWebsite?: string;
  srcMediaName?: string;
  reportDateTime?: Date;
  reportingUser?: UserReferenceDto;
  responsibleUser?: UserReferenceDto;
  regionUuid?: string;
  eventGroups?: EventGroupsIndexDto;
  eventIdentificationSource?: EventIdentificationSource;
  surveillanceToolLastShareDate?: Date;
  surveillanceToolShareCount?: number;
  surveillanceToolStatus?: ExternalShareStatus;
  district?: string;
  community?: string;
  inJurisdictionOrOwned?: boolean;
  region?: string;
  address?: string;
}
