/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EventSourceType =
  | 'NOT_APPLICABLE'
  | 'MEDIA_NEWS'
  | 'HOTLINE_PERSON'
  | 'MATHEMATICAL_MODEL'
  | 'INSTITUTIONAL_PARTNER';

export const EventSourceType = {
  NOT_APPLICABLE: 'NOT_APPLICABLE' as EventSourceType,
  MEDIA_NEWS: 'MEDIA_NEWS' as EventSourceType,
  HOTLINE_PERSON: 'HOTLINE_PERSON' as EventSourceType,
  MATHEMATICAL_MODEL: 'MATHEMATICAL_MODEL' as EventSourceType,
  INSTITUTIONAL_PARTNER: 'INSTITUTIONAL_PARTNER' as EventSourceType,
};
