/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ExposureType =
  | 'WORK'
  | 'TRAVEL'
  | 'SPORT'
  | 'VISIT'
  | 'GATHERING'
  | 'HABITATION'
  | 'PERSONAL_SERVICES'
  | 'BURIAL'
  | 'ANIMAL_CONTACT'
  | 'OTHER'
  | 'UNKNOWN';

export const ExposureType = {
  WORK: 'WORK' as ExposureType,
  TRAVEL: 'TRAVEL' as ExposureType,
  SPORT: 'SPORT' as ExposureType,
  VISIT: 'VISIT' as ExposureType,
  GATHERING: 'GATHERING' as ExposureType,
  HABITATION: 'HABITATION' as ExposureType,
  PERSONAL_SERVICES: 'PERSONAL_SERVICES' as ExposureType,
  BURIAL: 'BURIAL' as ExposureType,
  ANIMAL_CONTACT: 'ANIMAL_CONTACT' as ExposureType,
  OTHER: 'OTHER' as ExposureType,
  UNKNOWN: 'UNKNOWN' as ExposureType,
};
