import { AnimalCondition } from './animalCondition';
import { AnimalContactType } from './animalContactType';
import { ContactReferenceDto } from './contactReferenceDto';
import { ExposureRole } from './exposureRole';
import { ExposureType } from './exposureType';
import { GatheringType } from './gatheringType';
import { HabitationType } from './habitationType';
import { LocationDto } from './locationDto';
import { MeansOfTransport } from './meansOfTransport';
import { TypeOfAnimal } from './typeOfAnimal';
import { TypeOfPlace } from './typeOfPlace';
import { UserReferenceDto } from './userReferenceDto';
import { WaterSource } from './waterSource';
import { WorkEnvironment } from './workEnvironment';
import { YesNoUnknown } from './yesNoUnknown';

export interface ExposureDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  reportingUser?: UserReferenceDto;
  startDate?: Date;
  endDate?: Date;
  description?: string;
  exposureType: ExposureType;
  exposureTypeDetails?: string;
  location?: LocationDto;
  exposureRole?: ExposureRole;
  typeOfPlace?: TypeOfPlace;
  typeOfPlaceDetails?: string;
  meansOfTransport?: MeansOfTransport;
  meansOfTransportDetails?: string;
  connectionNumber?: string;
  seatNumber?: string;
  workEnvironment?: WorkEnvironment;
  indoors?: YesNoUnknown;
  outdoors?: YesNoUnknown;
  wearingMask?: YesNoUnknown;
  wearingPpe?: YesNoUnknown;
  otherProtectiveMeasures?: YesNoUnknown;
  protectiveMeasuresDetails?: string;
  shortDistance?: YesNoUnknown;
  longFaceToFaceContact?: YesNoUnknown;
  animalMarket?: YesNoUnknown;
  percutaneous?: YesNoUnknown;
  contactToBodyFluids?: YesNoUnknown;
  handlingSamples?: YesNoUnknown;
  eatingRawAnimalProducts?: YesNoUnknown;
  handlingAnimals?: YesNoUnknown;
  animalCondition?: AnimalCondition;
  animalVaccinated?: YesNoUnknown;
  animalContactType?: AnimalContactType;
  animalContactTypeDetails?: string;
  bodyOfWater?: YesNoUnknown;
  waterSource?: WaterSource;
  waterSourceDetails?: string;
  contactToCase?: ContactReferenceDto;
  prophylaxis?: YesNoUnknown;
  prophylaxisDate?: Date;
  riskArea?: YesNoUnknown;
  gatheringType?: GatheringType;
  gatheringDetails?: string;
  habitationType?: HabitationType;
  habitationDetails?: string;
  typeOfAnimal?: TypeOfAnimal;
  typeOfAnimalDetails?: string;
  physicalContactDuringPreparation?: YesNoUnknown;
  physicalContactWithBody?: YesNoUnknown;
  deceasedPersonIll?: YesNoUnknown;
  deceasedPersonName?: string;
  deceasedPersonRelation?: string;
}
