/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ExposureRole =
  | 'PASSENGER'
  | 'STAFF'
  | 'NURSING_STAFF'
  | 'MEDICAL_STAFF'
  | 'VISITOR'
  | 'GUEST'
  | 'CUSTOMER'
  | 'CONSERVATEE'
  | 'PATIENT'
  | 'EDUCATOR'
  | 'TRAINEE_TEACHER'
  | 'PUPIL'
  | 'STUDENT'
  | 'PARENT'
  | 'TEACHER'
  | 'UNKNOWN'
  | 'OTHER';

export const ExposureRole = {
  PASSENGER: 'PASSENGER' as ExposureRole,
  STAFF: 'STAFF' as ExposureRole,
  NURSING_STAFF: 'NURSING_STAFF' as ExposureRole,
  MEDICAL_STAFF: 'MEDICAL_STAFF' as ExposureRole,
  VISITOR: 'VISITOR' as ExposureRole,
  GUEST: 'GUEST' as ExposureRole,
  CUSTOMER: 'CUSTOMER' as ExposureRole,
  CONSERVATEE: 'CONSERVATEE' as ExposureRole,
  PATIENT: 'PATIENT' as ExposureRole,
  EDUCATOR: 'EDUCATOR' as ExposureRole,
  TRAINEE_TEACHER: 'TRAINEE_TEACHER' as ExposureRole,
  PUPIL: 'PUPIL' as ExposureRole,
  STUDENT: 'STUDENT' as ExposureRole,
  PARENT: 'PARENT' as ExposureRole,
  TEACHER: 'TEACHER' as ExposureRole,
  UNKNOWN: 'UNKNOWN' as ExposureRole,
  OTHER: 'OTHER' as ExposureRole,
};
