/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ExposureRole =
  | 'PASSENGER'
  | 'STAFF'
  | 'NURSING_STAFF'
  | 'MEDICAL_STAFF'
  | 'VISITOR'
  | 'GUEST'
  | 'CUSTOMER'
  | 'CONSERVATEE'
  | 'PATIENT'
  | 'EDUCATOR'
  | 'TRAINEE_TEACHER'
  | 'PUPIL'
  | 'STUDENT'
  | 'PARENT'
  | 'TEACHER'
  | 'UNKNOWN'
  | 'OTHER';
