/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FacilityTypeGroup =
  | 'ACCOMMODATION'
  | 'CARE_FACILITY'
  | 'CATERING_OUTLET'
  | 'EDUCATIONAL_FACILITY'
  | 'LEISURE_FACILITY'
  | 'MEDICAL_FACILITY'
  | 'WORKING_PLACE'
  | 'RESIDENCE'
  | 'COMMERCE';

export const FacilityTypeGroup = {
  ACCOMMODATION: 'ACCOMMODATION' as FacilityTypeGroup,
  CARE_FACILITY: 'CARE_FACILITY' as FacilityTypeGroup,
  CATERING_OUTLET: 'CATERING_OUTLET' as FacilityTypeGroup,
  EDUCATIONAL_FACILITY: 'EDUCATIONAL_FACILITY' as FacilityTypeGroup,
  LEISURE_FACILITY: 'LEISURE_FACILITY' as FacilityTypeGroup,
  MEDICAL_FACILITY: 'MEDICAL_FACILITY' as FacilityTypeGroup,
  WORKING_PLACE: 'WORKING_PLACE' as FacilityTypeGroup,
  RESIDENCE: 'RESIDENCE' as FacilityTypeGroup,
  COMMERCE: 'COMMERCE' as FacilityTypeGroup,
};
