/* eslint-disable @typescript-eslint/no-redeclare */

export type FeatureType =
  | 'LINE_LISTING'
  | 'AGGREGATE_REPORTING'
  | 'EVENT_SURVEILLANCE'
  | 'WEEKLY_REPORTING'
  | 'CLINICAL_MANAGEMENT'
  | 'NATIONAL_CASE_SHARING'
  | 'TASK_MANAGEMENT'
  | 'TASK_GENERATION_CASE_SURVEILLANCE'
  | 'TASK_GENERATION_CONTACT_TRACING'
  | 'TASK_GENERATION_EVENT_SURVEILLANCE'
  | 'TASK_GENERATION_GENERAL'
  | 'CAMPAIGNS'
  | 'CASE_SURVEILANCE'
  | 'CONTACT_TRACING'
  | 'SAMPLES_LAB'
  | 'INFRASTRUCTURE_TYPE_AREA'
  | 'CASE_FOLLOWUP'
  | 'TASK_NOTIFICATIONS'
  | 'MANUAL_EXTERNAL_MESSAGES'
  | 'OTHER_NOTIFICATIONS'
  | 'DOCUMENTS'
  | 'OUTBREAKS'
  | 'LAB_MESSAGES'
  | 'ASSIGN_TASKS_TO_HIGHER_LEVEL'
  | 'SURVEILLANCE_REPORTS';

export const FeatureType = {
  LINELISTING: 'LINE_LISTING' as FeatureType,
  AGGREGATEREPORTING: 'AGGREGATE_REPORTING' as FeatureType,
  EVENTSURVEILLANCE: 'EVENT_SURVEILLANCE' as FeatureType,
  WEEKLYREPORTING: 'WEEKLY_REPORTING' as FeatureType,
  CLINICALMANAGEMENT: 'CLINICAL_MANAGEMENT' as FeatureType,
  NATIONALCASESHARING: 'NATIONAL_CASE_SHARING' as FeatureType,
  TASKMANAGEMENT: 'TASK_MANAGEMENT' as FeatureType,
  TASKGENERATIONCASESURVEILLANCE: 'TASK_GENERATION_CASE_SURVEILLANCE' as FeatureType,
  TASKGENERATIONCONTACTTRACING: 'TASK_GENERATION_CONTACT_TRACING' as FeatureType,
  TASKGENERATIONEVENTSURVEILLANCE: 'TASK_GENERATION_EVENT_SURVEILLANCE' as FeatureType,
  TASKGENERATIONGENERAL: 'TASK_GENERATION_GENERAL' as FeatureType,
  CAMPAIGNS: 'CAMPAIGNS' as FeatureType,
  CASESURVEILANCE: 'CASE_SURVEILANCE' as FeatureType,
  CONTACTTRACING: 'CONTACT_TRACING' as FeatureType,
  SAMPLESLAB: 'SAMPLES_LAB' as FeatureType,
  INFRASTRUCTURETYPEAREA: 'INFRASTRUCTURE_TYPE_AREA' as FeatureType,
  CASEFOLLOWUP: 'CASE_FOLLOWUP' as FeatureType,
  TASKNOTIFICATIONS: 'TASK_NOTIFICATIONS' as FeatureType,
  MANUALEXTERNALMESSAGES: 'MANUAL_EXTERNAL_MESSAGES' as FeatureType,
  OTHERNOTIFICATIONS: 'OTHER_NOTIFICATIONS' as FeatureType,
  DOCUMENTS: 'DOCUMENTS' as FeatureType,
  OUTBREAKS: 'OUTBREAKS' as FeatureType,
  LABMESSAGES: 'LAB_MESSAGES' as FeatureType,
  ASSIGNTASKSTOHIGHERLEVEL: 'ASSIGN_TASKS_TO_HIGHER_LEVEL' as FeatureType,
  SURVEILLANCEREPORTS: 'SURVEILLANCE_REPORTS' as FeatureType,
};
