/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FollowUpStatus = 'FOLLOW_UP' | 'COMPLETED' | 'CANCELED' | 'LOST' | 'NO_FOLLOW_UP';

export const FollowUpStatus = {
  FOLLOWUP: 'FOLLOW_UP' as FollowUpStatus,
  COMPLETED: 'COMPLETED' as FollowUpStatus,
  CANCELED: 'CANCELED' as FollowUpStatus,
  LOST: 'LOST' as FollowUpStatus,
  NOFOLLOWUP: 'NO_FOLLOW_UP' as FollowUpStatus,
};
