/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type GatheringType =
  | 'PARTY'
  | 'RELIGIOUS'
  | 'MUSICAL'
  | 'DEMONSTRATION'
  | 'CARNIVAL'
  | 'FAIR'
  | 'SPORTING_EVENT'
  | 'OTHER';

export const GatheringType = {
  PARTY: 'PARTY' as GatheringType,
  RELIGIOUS: 'RELIGIOUS' as GatheringType,
  MUSICAL: 'MUSICAL' as GatheringType,
  DEMONSTRATION: 'DEMONSTRATION' as GatheringType,
  CARNIVAL: 'CARNIVAL' as GatheringType,
  FAIR: 'FAIR' as GatheringType,
  SPORTINGEVENT: 'SPORTING_EVENT' as GatheringType,
  OTHER: 'OTHER' as GatheringType,
};
