/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HospitalizationReasonType } from './hospitalizationReasonType';
import { PreviousHospitalizationDto } from './previousHospitalizationDto';
import { YesNoUnknown } from './yesNoUnknown';

export interface HospitalizationDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  admittedToHealthFacility?: YesNoUnknown;
  admissionDate?: Date;
  dischargeDate?: Date;
  isolated?: YesNoUnknown;
  isolationDate?: Date;
  leftAgainstAdvice?: YesNoUnknown;
  hospitalizedPreviously?: YesNoUnknown;
  previousHospitalizations?: Array<PreviousHospitalizationDto>;
  intensiveCareUnit?: YesNoUnknown;
  intensiveCareUnitStart?: Date;
  intensiveCareUnitEnd?: Date;
  hospitalizationReason?: HospitalizationReasonType;
  otherHospitalizationReason?: string;
}
