/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type HospitalWardType =
  | 'PEDIATRIC_INPATIENT'
  | 'NURSERY'
  | 'EPU'
  | 'CHER'
  | 'OPD'
  | 'EYE'
  | 'ENT'
  | 'CARDIOLOGY'
  | 'OTHER';

export const HospitalWardType = {
  PEDIATRICINPATIENT: 'PEDIATRIC_INPATIENT' as HospitalWardType,
  NURSERY: 'NURSERY' as HospitalWardType,
  EPU: 'EPU' as HospitalWardType,
  CHER: 'CHER' as HospitalWardType,
  OPD: 'OPD' as HospitalWardType,
  EYE: 'EYE' as HospitalWardType,
  ENT: 'ENT' as HospitalWardType,
  CARDIOLOGY: 'CARDIOLOGY' as HospitalWardType,
  OTHER: 'OTHER' as HospitalWardType,
};
