/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type HumanTransmissionMode =
  | 'FECAL_ORAL_SMEAR_INFECTION'
  | 'PARENTERAL'
  | 'DIRECT_SKIN_CONTACT'
  | 'RESPIRATORY'
  | 'SEXUAL'
  | 'CONNATAL'
  | 'OTHER';

export const HumanTransmissionMode = {
  FECAL_ORAL_SMEAR_INFECTION: 'FECAL_ORAL_SMEAR_INFECTION' as HumanTransmissionMode,
  PARENTERAL: 'PARENTERAL' as HumanTransmissionMode,
  DIRECT_SKIN_CONTACT: 'DIRECT_SKIN_CONTACT' as HumanTransmissionMode,
  RESPIRATORY: 'RESPIRATORY' as HumanTransmissionMode,
  SEXUAL: 'SEXUAL' as HumanTransmissionMode,
  CONNATAL: 'CONNATAL' as HumanTransmissionMode,
  OTHER: 'OTHER' as HumanTransmissionMode,
};
