/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ImmunizationStatus = 'PENDING' | 'ACQUIRED' | 'NOT_ACQUIRED' | 'EXPIRED';

export const ImmunizationStatus = {
  PENDING: 'PENDING' as ImmunizationStatus,
  ACQUIRED: 'ACQUIRED' as ImmunizationStatus,
  NOT_ACQUIRED: 'NOT_ACQUIRED' as ImmunizationStatus,
  EXPIRED: 'EXPIRED' as ImmunizationStatus,
};
