/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseReferenceDto } from './caseReferenceDto';
import { CommunityReferenceDto } from './communityReferenceDto';
import { CountryReferenceDto } from './countryReferenceDto';
import { Disease } from './disease';
import { DistrictReferenceDto } from './districtReferenceDto';
import { FacilityReferenceDto } from './facilityReferenceDto';
import { FacilityType } from './facilityType';
import { ImmunizationManagementStatus } from './immunizationManagementStatus';
import { ImmunizationStatus } from './immunizationStatus';
import { MeansOfImmunization } from './meansOfImmunization';
import { PersonReferenceDto } from './personReferenceDto';
import { RegionReferenceDto } from './regionReferenceDto';
import { SormasToSormasOriginInfoDto } from './sormasToSormasOriginInfoDto';
import { UserReferenceDto } from './userReferenceDto';
import { VaccinationDto } from './vaccinationDto';
import { YesNoUnknown } from './yesNoUnknown';

export interface ImmunizationDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  disease: Disease;
  diseaseDetails?: string;
  person: PersonReferenceDto;
  reportDate: Date;
  reportingUser?: UserReferenceDto;
  archived?: boolean;
  immunizationStatus: ImmunizationStatus;
  meansOfImmunization: MeansOfImmunization;
  meansOfImmunizationDetails?: string;
  immunizationManagementStatus?: ImmunizationManagementStatus;
  externalId?: string;
  responsibleRegion: RegionReferenceDto;
  responsibleDistrict: DistrictReferenceDto;
  responsibleCommunity?: CommunityReferenceDto;
  country?: CountryReferenceDto;
  facilityType?: FacilityType;
  healthFacility?: FacilityReferenceDto;
  healthFacilityDetails?: string;
  startDate?: Date;
  endDate?: Date;
  numberOfDoses?: number;
  previousInfection?: YesNoUnknown;
  lastInfectionDate?: Date;
  additionalDetails?: string;
  positiveTestResultDate?: Date;
  recoveryDate?: Date;
  validFrom?: Date;
  validUntil?: Date;
  relatedCase?: CaseReferenceDto;
  vaccinations?: Array<VaccinationDto>;
  sormasToSormasOriginInfo?: SormasToSormasOriginInfoDto;
  ownershipHandedOver?: boolean;
}
