/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type InfectionSetting =
  | 'UNKNOWN'
  | 'AMBULATORY'
  | 'MEDICAL_PRACTICE'
  | 'OPERATIVE_1200'
  | 'HOSPITAL_1300'
  | 'OTHER_OUTPATIENT_FACILITY'
  | 'STATIONARY'
  | 'HOSPITAL_2100'
  | 'NORMAL_WARD'
  | 'OPERATIVE_2111'
  | 'NOT_OPERATIVE'
  | 'HEMATOLOGICAL_ONCOLOGY'
  | 'CHILDREN_WARD'
  | 'NEONATOLOGY'
  | 'INTENSIVE_CARE_UNIT'
  | 'OTHER_STATION'
  | 'NURSING_HOME'
  | 'REHAB_FACILITY'
  | 'OTHER_STATIONARY_FACILITY';
