/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type InfectionSetting =
  | 'UNKNOWN'
  | 'AMBULATORY'
  | 'MEDICAL_PRACTICE'
  | 'OPERATIVE_1200'
  | 'HOSPITAL_1300'
  | 'OTHER_OUTPATIENT_FACILITY'
  | 'STATIONARY'
  | 'HOSPITAL_2100'
  | 'NORMAL_WARD'
  | 'OPERATIVE_2111'
  | 'NOT_OPERATIVE'
  | 'HEMATOLOGICAL_ONCOLOGY'
  | 'CHILDREN_WARD'
  | 'NEONATOLOGY'
  | 'INTENSIVE_CARE_UNIT'
  | 'OTHER_STATION'
  | 'NURSING_HOME'
  | 'REHAB_FACILITY'
  | 'OTHER_STATIONARY_FACILITY';

export const InfectionSetting = {
  UNKNOWN: 'UNKNOWN' as InfectionSetting,
  AMBULATORY: 'AMBULATORY' as InfectionSetting,
  MEDICAL_PRACTICE: 'MEDICAL_PRACTICE' as InfectionSetting,
  OPERATIVE_1200: 'OPERATIVE_1200' as InfectionSetting,
  HOSPITAL_1300: 'HOSPITAL_1300' as InfectionSetting,
  OTHER_OUTPATIENT_FACILITY: 'OTHER_OUTPATIENT_FACILITY' as InfectionSetting,
  STATIONARY: 'STATIONARY' as InfectionSetting,
  HOSPITAL_2100: 'HOSPITAL_2100' as InfectionSetting,
  NORMAL_WARD: 'NORMAL_WARD' as InfectionSetting,
  OPERATIVE_2111: 'OPERATIVE_2111' as InfectionSetting,
  NOT_OPERATIVE: 'NOT_OPERATIVE' as InfectionSetting,
  HEMATOLOGICAL_ONCOLOGY: 'HEMATOLOGICAL_ONCOLOGY' as InfectionSetting,
  CHILDREN_WARD: 'CHILDREN_WARD' as InfectionSetting,
  NEONATOLOGY: 'NEONATOLOGY' as InfectionSetting,
  INTENSIVE_CARE_UNIT: 'INTENSIVE_CARE_UNIT' as InfectionSetting,
  OTHER_STATION: 'OTHER_STATION' as InfectionSetting,
  NURSING_HOME: 'NURSING_HOME' as InfectionSetting,
  REHAB_FACILITY: 'REHAB_FACILITY' as InfectionSetting,
  OTHER_STATIONARY_FACILITY: 'OTHER_STATIONARY_FACILITY' as InfectionSetting,
};
