/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InfrastructureChangeDatesDto {
  continentChangeDate?: Date;
  subcontinentChangeDate?: Date;
  countryChangeDate?: Date;
  areaChangeDate?: Date;
  regionChangeDate?: Date;
  districtChangeDate?: Date;
  communityChangeDate?: Date;
  facilityChangeDate?: Date;
  pointOfEntryChangeDate?: Date;
  userChangeDate?: Date;
  diseaseClassificationChangeDate?: Date;
  diseaseConfigurationChangeDate?: Date;
  userRoleConfigurationChangeDate?: Date;
  featureConfigurationChangeDate?: Date;
  campaignChangeDate?: Date;
  campaignFormMetaChangeDate?: Date;
}
