/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type InstitutionalPartnerType =
  | 'HEALTH_INSURANCE'
  | 'TERRITORIAL_COMMUNITIES'
  | 'NATIONAL_EDUCATION'
  | 'HEALTH_ESTABLISHMENTS'
  | 'MEDICO_SOCIAL_ESTABLISHMENTS'
  | 'OTHER';

export const InstitutionalPartnerType = {
  HEALTH_INSURANCE: 'HEALTH_INSURANCE' as InstitutionalPartnerType,
  TERRITORIAL_COMMUNITIES: 'TERRITORIAL_COMMUNITIES' as InstitutionalPartnerType,
  NATIONAL_EDUCATION: 'NATIONAL_EDUCATION' as InstitutionalPartnerType,
  HEALTH_ESTABLISHMENTS: 'HEALTH_ESTABLISHMENTS' as InstitutionalPartnerType,
  MEDICO_SOCIAL_ESTABLISHMENTS: 'MEDICO_SOCIAL_ESTABLISHMENTS' as InstitutionalPartnerType,
  OTHER: 'OTHER' as InstitutionalPartnerType,
};
