/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type InstitutionalPartnerType =
  | 'HEALTH_INSURANCE'
  | 'TERRITORIAL_COMMUNITIES'
  | 'NATIONAL_EDUCATION'
  | 'HEALTH_ESTABLISHMENTS'
  | 'MEDICO_SOCIAL_ESTABLISHMENTS'
  | 'OTHER';

export const InstitutionalPartnerType = {
  HEALTHINSURANCE: 'HEALTH_INSURANCE' as InstitutionalPartnerType,
  TERRITORIALCOMMUNITIES: 'TERRITORIAL_COMMUNITIES' as InstitutionalPartnerType,
  NATIONALEDUCATION: 'NATIONAL_EDUCATION' as InstitutionalPartnerType,
  HEALTHESTABLISHMENTS: 'HEALTH_ESTABLISHMENTS' as InstitutionalPartnerType,
  MEDICOSOCIALESTABLISHMENTS: 'MEDICO_SOCIAL_ESTABLISHMENTS' as InstitutionalPartnerType,
  OTHER: 'OTHER' as InstitutionalPartnerType,
};
