/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JsonNodeType } from './jsonNodeType';

export interface JsonNode {
  number?: boolean;
  _int?: boolean;
  missingNode?: boolean;
  object?: boolean;
  pojo?: boolean;
  integralNumber?: boolean;
  floatingPointNumber?: boolean;
  _short?: boolean;
  _long?: boolean;
  _double?: boolean;
  bigDecimal?: boolean;
  bigInteger?: boolean;
  textual?: boolean;
  _boolean?: boolean;
  binary?: boolean;
  valueNode?: boolean;
  containerNode?: boolean;
  nodeType?: JsonNodeType;
  _float?: boolean;
  array?: boolean;
  empty?: boolean;
  _null?: boolean;
}
