/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type JsonNodeType =
  | 'ARRAY'
  | 'BINARY'
  | 'BOOLEAN'
  | 'MISSING'
  | 'NULL'
  | 'NUMBER'
  | 'OBJECT'
  | 'POJO'
  | 'STRING';

export const JsonNodeType = {
  ARRAY: 'ARRAY' as JsonNodeType,
  BINARY: 'BINARY' as JsonNodeType,
  BOOLEAN: 'BOOLEAN' as JsonNodeType,
  MISSING: 'MISSING' as JsonNodeType,
  NULL: 'NULL' as JsonNodeType,
  NUMBER: 'NUMBER' as JsonNodeType,
  OBJECT: 'OBJECT' as JsonNodeType,
  POJO: 'POJO' as JsonNodeType,
  STRING: 'STRING' as JsonNodeType,
};
