/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LabMessageStatus } from './labMessageStatus';
import { SampleMaterial } from './sampleMaterial';
import { Sex } from './sex';
import { SpecimenCondition } from './specimenCondition';
import { UserReferenceDto } from './userReferenceDto';

export interface LabMessageDto {
  uuid: string;
  messageDateTime?: Date;
  sampleDateTime?: Date;
  sampleReceivedDate?: Date;
  labSampleId?: string;
  sampleMaterial?: SampleMaterial;
  sampleMaterialText?: string;
  specimenCondition?: SpecimenCondition;
  labName?: string;
  labExternalId?: string;
  labPostalCode?: number;
  labCity?: string;
  personFirstName?: string;
  personLastName?: string;
  personSex?: Sex;
  personBirthDateDD?: number;
  personBirthDateMM?: number;
  personBirthDateYYYY?: number;
  personPostalCode?: number;
  personCity?: string;
  personPhone?: number;
  personEmail?: string;
  personStreet?: string;
  personHouseNumber?: number;
  labMessageDetails?: string;
  processed?: boolean;
  reportId?: string;
  status?: LabMessageStatus;
  assignee?: UserReferenceDto;
}
