/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Language =
  | 'EN'
  | 'EN_NG'
  | 'EN_GH'
  | 'EN_AF'
  | 'FR'
  | 'FR_CH'
  | 'DE'
  | 'DE_CH'
  | 'ES_EC'
  | 'ES_CU'
  | 'IT'
  | 'IT_CH'
  | 'FI'
  | 'PS'
  | 'FA'
  | 'CZ';
