/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Language =
  | 'EN'
  | 'EN_NG'
  | 'EN_GH'
  | 'EN_AF'
  | 'FR'
  | 'FR_CH'
  | 'DE'
  | 'DE_CH'
  | 'ES_EC'
  | 'ES_CU'
  | 'IT'
  | 'IT_CH'
  | 'FI'
  | 'PS'
  | 'FA'
  | 'CZ';

export const Language = {
  EN: 'EN' as Language,
  EN_NG: 'EN_NG' as Language,
  EN_GH: 'EN_GH' as Language,
  EN_AF: 'EN_AF' as Language,
  FR: 'FR' as Language,
  FR_CH: 'FR_CH' as Language,
  DE: 'DE' as Language,
  DE_CH: 'DE_CH' as Language,
  ES_EC: 'ES_EC' as Language,
  ES_CU: 'ES_CU' as Language,
  IT: 'IT' as Language,
  IT_CH: 'IT_CH' as Language,
  FI: 'FI' as Language,
  PS: 'PS' as Language,
  FA: 'FA' as Language,
  CZ: 'CZ' as Language,
};
