/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommunityReferenceDto } from './communityReferenceDto';
import { DistrictReferenceDto } from './districtReferenceDto';
import { RegionReferenceDto } from './regionReferenceDto';
import { YesNoUnknown } from './yesNoUnknown';

export interface MaternalHistoryDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  childrenNumber?: number;
  ageAtBirth?: number;
  conjunctivitis?: YesNoUnknown;
  conjunctivitisOnset?: Date;
  conjunctivitisMonth?: number;
  maculopapularRash?: YesNoUnknown;
  maculopapularRashOnset?: Date;
  maculopapularRashMonth?: number;
  swollenLymphs?: YesNoUnknown;
  swollenLymphsOnset?: Date;
  swollenLymphsMonth?: number;
  arthralgiaArthritis?: YesNoUnknown;
  arthralgiaArthritisOnset?: Date;
  arthralgiaArthritisMonth?: number;
  otherComplications?: YesNoUnknown;
  otherComplicationsOnset?: Date;
  otherComplicationsMonth?: number;
  otherComplicationsDetails?: string;
  rubella?: YesNoUnknown;
  rubellaOnset?: Date;
  rashExposure?: YesNoUnknown;
  rashExposureDate?: Date;
  rashExposureMonth?: number;
  rashExposureRegion?: RegionReferenceDto;
  rashExposureDistrict?: DistrictReferenceDto;
  rashExposureCommunity?: CommunityReferenceDto;
}
