/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MeansOfTransport =
  | 'LOCAL_PUBLIC_TRANSPORT'
  | 'BUS'
  | 'FERRY'
  | 'PLANE'
  | 'TRAIN'
  | 'OTHER';

export const MeansOfTransport = {
  LOCAL_PUBLIC_TRANSPORT: 'LOCAL_PUBLIC_TRANSPORT' as MeansOfTransport,
  BUS: 'BUS' as MeansOfTransport,
  FERRY: 'FERRY' as MeansOfTransport,
  PLANE: 'PLANE' as MeansOfTransport,
  TRAIN: 'TRAIN' as MeansOfTransport,
  OTHER: 'OTHER' as MeansOfTransport,
};
