/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MeansOfImmunization = 'VACCINATION' | 'RECOVERY' | 'VACCINATION_RECOVERY' | 'OTHER';

export const MeansOfImmunization = {
  VACCINATION: 'VACCINATION' as MeansOfImmunization,
  RECOVERY: 'RECOVERY' as MeansOfImmunization,
  VACCINATION_RECOVERY: 'VACCINATION_RECOVERY' as MeansOfImmunization,
  OTHER: 'OTHER' as MeansOfImmunization,
};
