/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MedicallyAssociatedTransmissionMode =
  | 'OPERATIVE_OR_DIAGNOSTIC_PROCEDURE'
  | 'BLOOD_PRODUCTS'
  | 'ORGAN_TRANSPLANTATION'
  | 'DIALYSIS'
  | 'INJECTION_FOR_MEDICAL_PURPOSES';

export const MedicallyAssociatedTransmissionMode = {
  OPERATIVE_OR_DIAGNOSTIC_PROCEDURE: 'OPERATIVE_OR_DIAGNOSTIC_PROCEDURE' as MedicallyAssociatedTransmissionMode,
  BLOOD_PRODUCTS: 'BLOOD_PRODUCTS' as MedicallyAssociatedTransmissionMode,
  ORGAN_TRANSPLANTATION: 'ORGAN_TRANSPLANTATION' as MedicallyAssociatedTransmissionMode,
  DIALYSIS: 'DIALYSIS' as MedicallyAssociatedTransmissionMode,
  INJECTION_FOR_MEDICAL_PURPOSES: 'INJECTION_FOR_MEDICAL_PURPOSES' as MedicallyAssociatedTransmissionMode,
};
