/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type OccupationType =
  | 'RETAIL_AND_REPAIR_SERVICE'
  | 'MANUFACTURING'
  | 'CONSTRUCTION'
  | 'TRANSPORT_AND_STORAGE'
  | 'HEALTH_AND_SOCIAL'
  | 'EDUCATION'
  | 'ACCOMMODATION_AND_FOOD_SERVICES'
  | 'ARTS_ENTERTAINMENT_AND_RECREATION'
  | 'PUBLIC_ADMINISTRATION_AND_DEFENCE'
  | 'FINANCE_AND_INSURANCE'
  | 'INFORMATION_AND_COMMUNICATION'
  | 'PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL'
  | 'ADMINISTRATIVE_AND_SUPPORT'
  | 'SERVICE_OTHER'
  | 'REAL_ESTATE'
  | 'ENERGY_SUPPLY'
  | 'WATER_SUPPLY_AND_WASTE'
  | 'EXTRATERRITORIAL_ORGANIZATIONS'
  | 'AGRICULTURE'
  | 'MINING'
  | 'PRIVATE_HOUSEHOLD'
  | 'FARMER'
  | 'BUTCHER'
  | 'HUNTER_MEAT_TRADER'
  | 'MINER'
  | 'RELIGIOUS_LEADER'
  | 'HOUSEWIFE'
  | 'PUPIL_STUDENT'
  | 'CHILD'
  | 'BUSINESSMAN_WOMAN'
  | 'TRANSPORTER'
  | 'HEALTHCARE_WORKER'
  | 'TRADITIONAL_SPIRITUAL_HEALER'
  | 'WORKING_WITH_ANIMALS'
  | 'LABORATORY_STAFF'
  | 'OTHER';
