/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ParenteralTransmissionMode =
  | 'INTRAVENOUS_DRUG_USE'
  | 'HOUSEHOLD_CONTACT'
  | 'MEDICALLY_ASSOCIATED'
  | 'TATTOOING_PIERCING'
  | 'PEDICURE_MANICURE'
  | 'OTHER';

export const ParenteralTransmissionMode = {
  INTRAVENOUS_DRUG_USE: 'INTRAVENOUS_DRUG_USE' as ParenteralTransmissionMode,
  HOUSEHOLD_CONTACT: 'HOUSEHOLD_CONTACT' as ParenteralTransmissionMode,
  MEDICALLY_ASSOCIATED: 'MEDICALLY_ASSOCIATED' as ParenteralTransmissionMode,
  TATTOOING_PIERCING: 'TATTOOING_PIERCING' as ParenteralTransmissionMode,
  PEDICURE_MANICURE: 'PEDICURE_MANICURE' as ParenteralTransmissionMode,
  OTHER: 'OTHER' as ParenteralTransmissionMode,
};
