/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PathogenTestResultType =
  | 'INDETERMINATE'
  | 'PENDING'
  | 'NEGATIVE'
  | 'POSITIVE'
  | 'NOT_DONE';

export const PathogenTestResultType = {
  INDETERMINATE: 'INDETERMINATE' as PathogenTestResultType,
  PENDING: 'PENDING' as PathogenTestResultType,
  NEGATIVE: 'NEGATIVE' as PathogenTestResultType,
  POSITIVE: 'POSITIVE' as PathogenTestResultType,
  NOTDONE: 'NOT_DONE' as PathogenTestResultType,
};
