/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PathogenTestType =
  | 'ANTIBODY_DETECTION'
  | 'ANTIGEN_DETECTION'
  | 'RAPID_TEST'
  | 'CULTURE'
  | 'HISTOPATHOLOGY'
  | 'ISOLATION'
  | 'IGM_SERUM_ANTIBODY'
  | 'IGG_SERUM_ANTIBODY'
  | 'IGA_SERUM_ANTIBODY'
  | 'INCUBATION_TIME'
  | 'INDIRECT_FLUORESCENT_ANTIBODY'
  | 'DIRECT_FLUORESCENT_ANTIBODY'
  | 'MICROSCOPY'
  | 'NEUTRALIZING_ANTIBODIES'
  | 'PCR_RT_PCR'
  | 'GRAM_STAIN'
  | 'LATEX_AGGLUTINATION'
  | 'CQ_VALUE_DETECTION'
  | 'SEQUENCING'
  | 'DNA_MICROARRAY'
  | 'OTHER';

export const PathogenTestType = {
  ANTIBODY_DETECTION: 'ANTIBODY_DETECTION' as PathogenTestType,
  ANTIGEN_DETECTION: 'ANTIGEN_DETECTION' as PathogenTestType,
  RAPID_TEST: 'RAPID_TEST' as PathogenTestType,
  CULTURE: 'CULTURE' as PathogenTestType,
  HISTOPATHOLOGY: 'HISTOPATHOLOGY' as PathogenTestType,
  ISOLATION: 'ISOLATION' as PathogenTestType,
  IGM_SERUM_ANTIBODY: 'IGM_SERUM_ANTIBODY' as PathogenTestType,
  IGG_SERUM_ANTIBODY: 'IGG_SERUM_ANTIBODY' as PathogenTestType,
  IGA_SERUM_ANTIBODY: 'IGA_SERUM_ANTIBODY' as PathogenTestType,
  INCUBATION_TIME: 'INCUBATION_TIME' as PathogenTestType,
  INDIRECT_FLUORESCENT_ANTIBODY: 'INDIRECT_FLUORESCENT_ANTIBODY' as PathogenTestType,
  DIRECT_FLUORESCENT_ANTIBODY: 'DIRECT_FLUORESCENT_ANTIBODY' as PathogenTestType,
  MICROSCOPY: 'MICROSCOPY' as PathogenTestType,
  NEUTRALIZING_ANTIBODIES: 'NEUTRALIZING_ANTIBODIES' as PathogenTestType,
  PCR_RT_PCR: 'PCR_RT_PCR' as PathogenTestType,
  GRAM_STAIN: 'GRAM_STAIN' as PathogenTestType,
  LATEX_AGGLUTINATION: 'LATEX_AGGLUTINATION' as PathogenTestType,
  CQ_VALUE_DETECTION: 'CQ_VALUE_DETECTION' as PathogenTestType,
  SEQUENCING: 'SEQUENCING' as PathogenTestType,
  DNA_MICROARRAY: 'DNA_MICROARRAY' as PathogenTestType,
  OTHER: 'OTHER' as PathogenTestType,
};
