/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PathogenTestType =
  | 'ANTIBODY_DETECTION'
  | 'ANTIGEN_DETECTION'
  | 'RAPID_TEST'
  | 'CULTURE'
  | 'HISTOPATHOLOGY'
  | 'ISOLATION'
  | 'IGM_SERUM_ANTIBODY'
  | 'IGG_SERUM_ANTIBODY'
  | 'IGA_SERUM_ANTIBODY'
  | 'INCUBATION_TIME'
  | 'INDIRECT_FLUORESCENT_ANTIBODY'
  | 'DIRECT_FLUORESCENT_ANTIBODY'
  | 'MICROSCOPY'
  | 'NEUTRALIZING_ANTIBODIES'
  | 'PCR_RT_PCR'
  | 'GRAM_STAIN'
  | 'LATEX_AGGLUTINATION'
  | 'CQ_VALUE_DETECTION'
  | 'SEQUENCING'
  | 'DNA_MICROARRAY'
  | 'OTHER';
