/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PCRTestSpecification = 'VARIANT_SPECIFIC' | 'N501Y_MUTATION_DETECTION';

export const PCRTestSpecification = {
  VARIANT_SPECIFIC: 'VARIANT_SPECIFIC' as PCRTestSpecification,
  N501Y_MUTATION_DETECTION: 'N501Y_MUTATION_DETECTION' as PCRTestSpecification,
};
