/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgeAndBirthDateDto } from './ageAndBirthDateDto';
import { Sex } from './sex';

export interface PersonIndexDto {
  pseudonymized?: boolean;
  uuid?: string;
  firstName?: string;
  lastName?: string;
  ageAndBirthDate?: AgeAndBirthDateDto;
  sex?: Sex;
  district?: string;
  street?: string;
  houseNumber?: string;
  postalCode?: string;
  city?: string;
  phone?: string;
  emailAddress?: string;
  changeDate?: Date;
  inJurisdiction?: boolean;
}
