/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PersonContactDetailType } from './personContactDetailType';
import { PersonReferenceDto } from './personReferenceDto';
import { PhoneNumberType } from './phoneNumberType';

export interface PersonContactDetailDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  person?: PersonReferenceDto;
  primaryContact?: boolean;
  personContactDetailType?: PersonContactDetailType;
  phoneNumberType?: PhoneNumberType;
  details?: string;
  contactInformation?: string;
  additionalInformation?: string;
  thirdParty?: boolean;
  thirdPartyRole?: string;
  thirdPartyName?: string;
}
