/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PersonAssociation =
  | 'ALL'
  | 'CASE'
  | 'CONTACT'
  | 'EVENT_PARTICIPANT'
  | 'IMMUNIZATION'
  | 'TRAVEL_ENTRY';

export const PersonAssociation = {
  ALL: 'ALL' as PersonAssociation,
  CASE: 'CASE' as PersonAssociation,
  CONTACT: 'CONTACT' as PersonAssociation,
  EVENT_PARTICIPANT: 'EVENT_PARTICIPANT' as PersonAssociation,
  IMMUNIZATION: 'IMMUNIZATION' as PersonAssociation,
  TRAVEL_ENTRY: 'TRAVEL_ENTRY' as PersonAssociation,
};
