/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PersonAddressType =
  | 'HOME'
  | 'PLACE_OF_RESIDENCE'
  | 'PLACE_OF_EXPOSURE'
  | 'PLACE_OF_WORK'
  | 'PLACE_OF_ISOLATION'
  | 'EVENT_LOCATION'
  | 'OTHER_ADDRESS';
