/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PlagueType = 'BUBONIC' | 'PNEUMONIC' | 'SEPTICAEMIC';

export const PlagueType = {
  BUBONIC: 'BUBONIC' as PlagueType,
  PNEUMONIC: 'PNEUMONIC' as PlagueType,
  SEPTICAEMIC: 'SEPTICAEMIC' as PlagueType,
};
