/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DistrictReferenceDto } from './districtReferenceDto';
import { PointOfEntryType } from './pointOfEntryType';
import { RegionReferenceDto } from './regionReferenceDto';

export interface PointOfEntryDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pointOfEntryType?: PointOfEntryType;
  name?: string;
  region?: RegionReferenceDto;
  district?: DistrictReferenceDto;
  latitude?: number;
  longitude?: number;
  active?: boolean;
  archived?: boolean;
  externalID?: string;
  nameOtherPointOfEntry?: boolean;
  otherPointOfEntry?: boolean;
}
