/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TherapyReferenceDto } from './therapyReferenceDto';
import { TreatmentRoute } from './treatmentRoute';
import { TreatmentType } from './treatmentType';
import { TypeOfDrug } from './typeOfDrug';

export interface PrescriptionDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  therapy?: TherapyReferenceDto;
  prescriptionDate?: Date;
  prescriptionStart?: Date;
  prescriptionEnd?: Date;
  prescribingClinician?: string;
  prescriptionType?: TreatmentType;
  prescriptionDetails?: string;
  typeOfDrug?: TypeOfDrug;
  frequency?: string;
  dose?: string;
  route?: TreatmentRoute;
  routeDetails?: string;
  additionalNotes?: string;
}
