/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PushResult = 'OK' | 'TOO_OLD' | 'ERROR';

export const PushResult = {
  OK: 'OK' as PushResult,
  TOO_OLD: 'TOO_OLD' as PushResult,
  ERROR: 'ERROR' as PushResult,
};
