/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type QuarantineType =
  | 'HOME'
  | 'INSTITUTIONELL'
  | 'HOSPITAL'
  | 'HOTEL'
  | 'ASYLUM_ACCOMMODATION'
  | 'NONE'
  | 'UNKNOWN'
  | 'OTHER';

export const QuarantineType = {
  HOME: 'HOME' as QuarantineType,
  INSTITUTIONELL: 'INSTITUTIONELL' as QuarantineType,
  HOSPITAL: 'HOSPITAL' as QuarantineType,
  HOTEL: 'HOTEL' as QuarantineType,
  ASYLUM_ACCOMMODATION: 'ASYLUM_ACCOMMODATION' as QuarantineType,
  NONE: 'NONE' as QuarantineType,
  UNKNOWN: 'UNKNOWN' as QuarantineType,
  OTHER: 'OTHER' as QuarantineType,
};
