/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type QuarantineReason =
  | 'IDENTIFIED_BY_CONTACT_TRACING'
  | 'ENTRY_FROM_RISK_AREA'
  | 'SWISS_COVID_APP_NOTIFICATION'
  | 'OUTBREAK_INVESTIGATION'
  | 'OTHER_REASON';
