/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ReportingType =
  | 'DOCTOR'
  | 'FORWARDING'
  | 'HOSPITAL_OR_STATIONARY_CARE'
  | 'COMMUNITY_FACILITY'
  | 'COMMUNITY_FACILITY_IFSG_ARTICLE_34'
  | 'OWN_DETERMINATION'
  | 'NOT_DETERMINABLE'
  | 'NOT_RAISED'
  | 'OTHER';

export const ReportingType = {
  DOCTOR: 'DOCTOR' as ReportingType,
  FORWARDING: 'FORWARDING' as ReportingType,
  HOSPITAL_OR_STATIONARY_CARE: 'HOSPITAL_OR_STATIONARY_CARE' as ReportingType,
  COMMUNITY_FACILITY: 'COMMUNITY_FACILITY' as ReportingType,
  COMMUNITY_FACILITY_IFSG_ARTICLE_34: 'COMMUNITY_FACILITY_IFSG_ARTICLE_34' as ReportingType,
  OWN_DETERMINATION: 'OWN_DETERMINATION' as ReportingType,
  NOT_DETERMINABLE: 'NOT_DETERMINABLE' as ReportingType,
  NOT_RAISED: 'NOT_RAISED' as ReportingType,
  OTHER: 'OTHER' as ReportingType,
};
