export type ReportingType =
  | 'DOCTOR'
  | 'FORWARDING'
  | 'HOSPITAL_OR_STATIONARY_CARE'
  | 'COMMUNITY_FACILITY'
  | 'COMMUNITY_FACILITY_IFSG_ARTICLE_34'
  | 'OWN_DETERMINATION'
  | 'NOT_DETERMINABLE'
  | 'NOT_RAISED'
  | 'OTHER';
