/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Salutation = 'MR' | 'MRS' | 'MR_AND_MRS' | 'FAMILY' | 'GUARDIAN_OF_MINOR' | 'OTHER';

export const Salutation = {
  MR: 'MR' as Salutation,
  MRS: 'MRS' as Salutation,
  MRANDMRS: 'MR_AND_MRS' as Salutation,
  FAMILY: 'FAMILY' as Salutation,
  GUARDIANOFMINOR: 'GUARDIAN_OF_MINOR' as Salutation,
  OTHER: 'OTHER' as Salutation,
};
