/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SamplingReason =
  | 'PRESENCE_OF_SYMPTOMS'
  | 'OUTBREAK'
  | 'SCREENING'
  | 'PROFESSIONAL_REASON'
  | 'QUARANTINE_REGULATIONS'
  | 'CONTACT_TO_CASE'
  | 'PLANNING_TO_TRAVEL'
  | 'RETURNING_TRAVELER'
  | 'PERSONAL_REASON'
  | 'MOVING_RETURNING_RETIREMENT_HOME'
  | 'SWISS_COVID_APP_NOTIFICATION'
  | 'QUARANTINE_END'
  | 'UNKNOWN'
  | 'OTHER_REASON';
