/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseClassification } from './caseClassification';
import { CaseReferenceDto } from './caseReferenceDto';
import { ContactReferenceDto } from './contactReferenceDto';
import { DateFilterOption } from './dateFilterOption';
import { Disease } from './disease';
import { DistrictReferenceDto } from './districtReferenceDto';
import { EntityRelevanceStatus } from './entityRelevanceStatus';
import { EventParticipantReferenceDto } from './eventParticipantReferenceDto';
import { FacilityReferenceDto } from './facilityReferenceDto';
import { PathogenTestResultType } from './pathogenTestResultType';
import { RegionReferenceDto } from './regionReferenceDto';
import { SampleAssociationType } from './sampleAssociationType';
import { SpecimenCondition } from './specimenCondition';

export interface SampleCriteria {
  region?: RegionReferenceDto;
  district?: DistrictReferenceDto;
  laboratory?: FacilityReferenceDto;
  shipped?: boolean;
  received?: boolean;
  referred?: boolean;
  pathogenTestResult?: PathogenTestResultType;
  caseClassification?: CaseClassification;
  disease?: Disease;
  specimenCondition?: SpecimenCondition;
  caze?: CaseReferenceDto;
  contact?: ContactReferenceDto;
  eventParticipant?: EventParticipantReferenceDto;
  deleted?: boolean;
  caseCodeIdLike?: string;
  relevanceStatus?: EntityRelevanceStatus;
  sampleAssociationType?: SampleAssociationType;
  sampleReportDateFrom?: Date;
  sampleReportDateTo?: Date;
  dateFilterOption?: DateFilterOption;
  caseUuids?: Array<string>;
  contactUuids?: Array<string>;
  eventParticipantUuids?: Array<string>;
}
