/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SamplingReason =
  | 'PRESENCE_OF_SYMPTOMS'
  | 'OUTBREAK'
  | 'SCREENING'
  | 'PROFESSIONAL_REASON'
  | 'QUARANTINE_REGULATIONS'
  | 'CONTACT_TO_CASE'
  | 'PLANNING_TO_TRAVEL'
  | 'RETURNING_TRAVELER'
  | 'PERSONAL_REASON'
  | 'MOVING_RETURNING_RETIREMENT_HOME'
  | 'SWISS_COVID_APP_NOTIFICATION'
  | 'QUARANTINE_END'
  | 'UNKNOWN'
  | 'OTHER_REASON';

export const SamplingReason = {
  PRESENCE_OF_SYMPTOMS: 'PRESENCE_OF_SYMPTOMS' as SamplingReason,
  OUTBREAK: 'OUTBREAK' as SamplingReason,
  SCREENING: 'SCREENING' as SamplingReason,
  PROFESSIONAL_REASON: 'PROFESSIONAL_REASON' as SamplingReason,
  QUARANTINE_REGULATIONS: 'QUARANTINE_REGULATIONS' as SamplingReason,
  CONTACT_TO_CASE: 'CONTACT_TO_CASE' as SamplingReason,
  PLANNING_TO_TRAVEL: 'PLANNING_TO_TRAVEL' as SamplingReason,
  RETURNING_TRAVELER: 'RETURNING_TRAVELER' as SamplingReason,
  PERSONAL_REASON: 'PERSONAL_REASON' as SamplingReason,
  MOVING_RETURNING_RETIREMENT_HOME: 'MOVING_RETURNING_RETIREMENT_HOME' as SamplingReason,
  SWISS_COVID_APP_NOTIFICATION: 'SWISS_COVID_APP_NOTIFICATION' as SamplingReason,
  QUARANTINE_END: 'QUARANTINE_END' as SamplingReason,
  UNKNOWN: 'UNKNOWN' as SamplingReason,
  OTHER_REASON: 'OTHER_REASON' as SamplingReason,
};
