/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalTestingStatus } from './additionalTestingStatus';
import { CaseReferenceDto } from './caseReferenceDto';
import { ContactReferenceDto } from './contactReferenceDto';
import { Disease } from './disease';
import { EventParticipantReferenceDto } from './eventParticipantReferenceDto';
import { FacilityReferenceDto } from './facilityReferenceDto';
import { PathogenTestResultType } from './pathogenTestResultType';
import { PathogenTestType } from './pathogenTestType';
import { SampleJurisdictionFlagsDto } from './sampleJurisdictionFlagsDto';
import { SampleMaterial } from './sampleMaterial';
import { SamplePurpose } from './samplePurpose';
import { SamplingReason } from './samplingReason';
import { SpecimenCondition } from './specimenCondition';

export interface SampleIndexDto {
  pseudonymized?: boolean;
  uuid?: string;
  associatedCase?: CaseReferenceDto;
  associatedContact?: ContactReferenceDto;
  associatedEventParticipant?: EventParticipantReferenceDto;
  epidNumber?: string;
  labSampleID?: string;
  disease?: Disease;
  diseaseDetails?: string;
  district?: string;
  shipped?: boolean;
  received?: boolean;
  referred?: boolean;
  sampleDateTime?: Date;
  shipmentDate?: Date;
  receivedDate?: Date;
  lab?: FacilityReferenceDto;
  sampleMaterial?: SampleMaterial;
  samplePurpose?: SamplePurpose;
  specimenCondition?: SpecimenCondition;
  pathogenTestResult?: PathogenTestResultType;
  additionalTestingStatus?: AdditionalTestingStatus;
  samplingReason?: SamplingReason;
  samplingReasonDetails?: string;
  pathogenTestCount?: number;
  typeOfLastTest?: PathogenTestType;
  lastTestCqValue?: number;
  sampleJurisdictionFlagsDto?: SampleJurisdictionFlagsDto;
}
