/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SampleMaterial =
  | 'BLOOD'
  | 'SERA'
  | 'STOOL'
  | 'NASAL_SWAB'
  | 'THROAT_SWAB'
  | 'NP_SWAB'
  | 'RECTAL_SWAB'
  | 'CEREBROSPINAL_FLUID'
  | 'CRUST'
  | 'TISSUE'
  | 'URINE'
  | 'CORNEA_PM'
  | 'SALIVA'
  | 'URINE_PM'
  | 'NUCHAL_SKIN_BIOPSY'
  | 'SPUTUM'
  | 'ENDOTRACHEAL_ASPIRATE'
  | 'BRONCHOALVEOLAR_LAVAGE'
  | 'BRAIN_TISSUE'
  | 'ANTERIOR_NARES_SWAB'
  | 'OP_ASPIRATE'
  | 'NP_ASPIRATE'
  | 'PLEURAL_FLUID'
  | 'OTHER';

export const SampleMaterial = {
  BLOOD: 'BLOOD' as SampleMaterial,
  SERA: 'SERA' as SampleMaterial,
  STOOL: 'STOOL' as SampleMaterial,
  NASAL_SWAB: 'NASAL_SWAB' as SampleMaterial,
  THROAT_SWAB: 'THROAT_SWAB' as SampleMaterial,
  NP_SWAB: 'NP_SWAB' as SampleMaterial,
  RECTAL_SWAB: 'RECTAL_SWAB' as SampleMaterial,
  CEREBROSPINAL_FLUID: 'CEREBROSPINAL_FLUID' as SampleMaterial,
  CRUST: 'CRUST' as SampleMaterial,
  TISSUE: 'TISSUE' as SampleMaterial,
  URINE: 'URINE' as SampleMaterial,
  CORNEA_PM: 'CORNEA_PM' as SampleMaterial,
  SALIVA: 'SALIVA' as SampleMaterial,
  URINE_PM: 'URINE_PM' as SampleMaterial,
  NUCHAL_SKIN_BIOPSY: 'NUCHAL_SKIN_BIOPSY' as SampleMaterial,
  SPUTUM: 'SPUTUM' as SampleMaterial,
  ENDOTRACHEAL_ASPIRATE: 'ENDOTRACHEAL_ASPIRATE' as SampleMaterial,
  BRONCHOALVEOLAR_LAVAGE: 'BRONCHOALVEOLAR_LAVAGE' as SampleMaterial,
  BRAIN_TISSUE: 'BRAIN_TISSUE' as SampleMaterial,
  ANTERIOR_NARES_SWAB: 'ANTERIOR_NARES_SWAB' as SampleMaterial,
  OP_ASPIRATE: 'OP_ASPIRATE' as SampleMaterial,
  NP_ASPIRATE: 'NP_ASPIRATE' as SampleMaterial,
  PLEURAL_FLUID: 'PLEURAL_FLUID' as SampleMaterial,
  OTHER: 'OTHER' as SampleMaterial,
};
