/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SampleMaterial =
  | 'BLOOD'
  | 'SERA'
  | 'STOOL'
  | 'NASAL_SWAB'
  | 'THROAT_SWAB'
  | 'NP_SWAB'
  | 'RECTAL_SWAB'
  | 'CEREBROSPINAL_FLUID'
  | 'CRUST'
  | 'TISSUE'
  | 'URINE'
  | 'CORNEA_PM'
  | 'SALIVA'
  | 'URINE_PM'
  | 'NUCHAL_SKIN_BIOPSY'
  | 'SPUTUM'
  | 'ENDOTRACHEAL_ASPIRATE'
  | 'BRONCHOALVEOLAR_LAVAGE'
  | 'BRAIN_TISSUE'
  | 'ANTERIOR_NARES_SWAB'
  | 'OP_ASPIRATE'
  | 'NP_ASPIRATE'
  | 'PLEURAL_FLUID'
  | 'OTHER';
