/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ScreeningType =
  | 'ON_HOSPITAL_ADMISSION'
  | 'ON_CARE_HOME_ADMISSION'
  | 'ON_ASYLUM_ADMISSION'
  | 'ON_ENTRY_FROM_RISK_AREA'
  | 'HEALTH_SECTOR_EMPLOYEE'
  | 'EDUCATIONAL_INSTITUTIONS'
  | 'OTHER';

export const ScreeningType = {
  ONHOSPITALADMISSION: 'ON_HOSPITAL_ADMISSION' as ScreeningType,
  ONCAREHOMEADMISSION: 'ON_CARE_HOME_ADMISSION' as ScreeningType,
  ONASYLUMADMISSION: 'ON_ASYLUM_ADMISSION' as ScreeningType,
  ONENTRYFROMRISKAREA: 'ON_ENTRY_FROM_RISK_AREA' as ScreeningType,
  HEALTHSECTOREMPLOYEE: 'HEALTH_SECTOR_EMPLOYEE' as ScreeningType,
  EDUCATIONALINSTITUTIONS: 'EDUCATIONAL_INSTITUTIONS' as ScreeningType,
  OTHER: 'OTHER' as ScreeningType,
};
