/* eslint-disable @typescript-eslint/no-redeclare */

export type ScreeningType =
  | 'ON_HOSPITAL_ADMISSION'
  | 'ON_CARE_HOME_ADMISSION'
  | 'ON_ASYLUM_ADMISSION'
  | 'ON_ENTRY_FROM_RISK_AREA'
  | 'HEALTH_SECTOR_EMPLOYEE'
  | 'EDUCATIONAL_INSTITUTIONS'
  | 'OTHER';

export const ScreeningType = {
  ONHOSPITALADMISSION: 'ON_HOSPITAL_ADMISSION' as ScreeningType,
  ONCAREHOMEADMISSION: 'ON_CARE_HOME_ADMISSION' as ScreeningType,
  ONASYLUMADMISSION: 'ON_ASYLUM_ADMISSION' as ScreeningType,
  ONENTRYFROMRISKAREA: 'ON_ENTRY_FROM_RISK_AREA' as ScreeningType,
  HEALTHSECTOREMPLOYEE: 'HEALTH_SECTOR_EMPLOYEE' as ScreeningType,
  EDUCATIONALINSTITUTIONS: 'EDUCATIONAL_INSTITUTIONS' as ScreeningType,
  OTHER: 'OTHER' as ScreeningType,
};
