/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ScreeningType =
  | 'ON_HOSPITAL_ADMISSION'
  | 'ON_CARE_HOME_ADMISSION'
  | 'ON_ASYLUM_ADMISSION'
  | 'ON_ENTRY_FROM_RISK_AREA'
  | 'HEALTH_SECTOR_EMPLOYEE'
  | 'EDUCATIONAL_INSTITUTIONS'
  | 'SELF_ARRANGED_TEST'
  | 'SELF_CONDUCTED_TEST'
  | 'OTHER';

export const ScreeningType = {
  ON_HOSPITAL_ADMISSION: 'ON_HOSPITAL_ADMISSION' as ScreeningType,
  ON_CARE_HOME_ADMISSION: 'ON_CARE_HOME_ADMISSION' as ScreeningType,
  ON_ASYLUM_ADMISSION: 'ON_ASYLUM_ADMISSION' as ScreeningType,
  ON_ENTRY_FROM_RISK_AREA: 'ON_ENTRY_FROM_RISK_AREA' as ScreeningType,
  HEALTH_SECTOR_EMPLOYEE: 'HEALTH_SECTOR_EMPLOYEE' as ScreeningType,
  EDUCATIONAL_INSTITUTIONS: 'EDUCATIONAL_INSTITUTIONS' as ScreeningType,
  SELF_ARRANGED_TEST: 'SELF_ARRANGED_TEST' as ScreeningType,
  SELF_CONDUCTED_TEST: 'SELF_CONDUCTED_TEST' as ScreeningType,
  OTHER: 'OTHER' as ScreeningType,
};
