/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Sex = 'MALE' | 'FEMALE' | 'OTHER' | 'UNKNOWN';

export const Sex = {
  MALE: 'MALE' as Sex,
  FEMALE: 'FEMALE' as Sex,
  OTHER: 'OTHER' as Sex,
  UNKNOWN: 'UNKNOWN' as Sex,
};
