/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PresentCondition } from './presentCondition';
import { Sex } from './sex';

export interface SimilarPersonDto {
  uuid: string;
  creationDate?: Date;
  changeDate?: Date;
  firstName: string;
  lastName: string;
  nickname?: string;
  ageAndBirthDate?: string;
  sex?: Sex;
  presentCondition?: PresentCondition;
  phone?: string;
  districtName?: string;
  communityName?: string;
  postalCode?: string;
  city?: string;
  street?: string;
  houseNumber?: string;
  nationalHealthId?: string;
  passportNumber?: string;
}
