/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CaseDataDto } from './caseDataDto';
import { ContactDto } from './contactDto';
import { EventDto } from './eventDto';
import { ShareRequestDataType } from './shareRequestDataType';
import { ShareRequestStatus } from './shareRequestStatus';
import { SormasToSormasOriginInfoDto } from './sormasToSormasOriginInfoDto';

export interface SormasToSormasShareRequestDto {
  uuid?: string;
  dataType?: ShareRequestDataType;
  status?: ShareRequestStatus;
  originInfo?: SormasToSormasOriginInfoDto;
  cases?: Array<CaseDataDto>;
  contacts?: Array<ContactDto>;
  events?: Array<EventDto>;
}
