/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ShareRequestDataType } from './shareRequestDataType';
import { ShareRequestStatus } from './shareRequestStatus';

export interface SormasToSormasShareRequestIndexDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  dataType?: ShareRequestDataType;
  status?: ShareRequestStatus;
  organizationId?: string;
  organizationName?: string;
  senderName?: boolean;
  ownershipHandedOver?: boolean;
  comment?: string;
}
