/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SormasToSormasOriginInfoDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  organizationId?: string;
  senderName?: string;
  senderEmail?: string;
  senderPhoneNumber?: string;
  ownershipHandedOver?: boolean;
  comment?: string;
}
