/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseReferenceDto } from './caseReferenceDto';
import { DistrictReferenceDto } from './districtReferenceDto';
import { FacilityReferenceDto } from './facilityReferenceDto';
import { FacilityType } from './facilityType';
import { RegionReferenceDto } from './regionReferenceDto';
import { ReportingType } from './reportingType';
import { UserReferenceDto } from './userReferenceDto';

export interface SurveillanceReportDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  reportingType?: ReportingType;
  creatingUser?: UserReferenceDto;
  reportDate?: Date;
  dateOfDiagnosis?: Date;
  facilityRegion?: RegionReferenceDto;
  facilityDistrict?: DistrictReferenceDto;
  facilityType?: FacilityType;
  facility?: FacilityReferenceDto;
  facilityDetails?: string;
  notificationDetails?: string;
  caze?: CaseReferenceDto;
}
