/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SymptomJournalStatus =
  | 'UNREGISTERED'
  | 'REGISTERED'
  | 'ACCEPTED'
  | 'REJECTED'
  | 'DELETED';

export const SymptomJournalStatus = {
  UNREGISTERED: 'UNREGISTERED' as SymptomJournalStatus,
  REGISTERED: 'REGISTERED' as SymptomJournalStatus,
  ACCEPTED: 'ACCEPTED' as SymptomJournalStatus,
  REJECTED: 'REJECTED' as SymptomJournalStatus,
  DELETED: 'DELETED' as SymptomJournalStatus,
};
