/* eslint-disable @typescript-eslint/no-redeclare */

export type TaskType =
  | 'ACTIVE_SEARCH_FOR_OTHER_CASES'
  | 'CASE_ISOLATION'
  | 'CASE_INVESTIGATION'
  | 'CASE_MANAGEMENT'
  | 'CASE_BURIAL'
  | 'CONTACT_TRACING'
  | 'SAMPLE_COLLECTION'
  | 'CONTACT_INVESTIGATION'
  | 'CONTACT_FOLLOW_UP'
  | 'ANIMAL_TESTING'
  | 'EVENT_INVESTIGATION'
  | 'EVENT_CONTINUE_INVESTIGATION'
  | 'EVENT_REQUEST_ADDITIONAL_INFORMATION'
  | 'TREATMENT_CENTER_ESTABLISHMENT'
  | 'ENVIRONMENTAL_HEALTH_ACTIVITIES'
  | 'DECONTAMINATION_DISINFECTION_ACTIVITIES'
  | 'QUARANTINE_PLACE'
  | 'VACCINATION_ACTIVITIES'
  | 'ANIMAL_DEPOPULATION'
  | 'OTHER'
  | 'DAILY_REPORT_GENERATION'
  | 'SURVEILLANCE_REPORT_GENERATION'
  | 'WEEKLY_REPORT_GENERATION';

export const TaskType = {
  ACTIVESEARCHFOROTHERCASES: 'ACTIVE_SEARCH_FOR_OTHER_CASES' as TaskType,
  CASEISOLATION: 'CASE_ISOLATION' as TaskType,
  CASEINVESTIGATION: 'CASE_INVESTIGATION' as TaskType,
  CASEMANAGEMENT: 'CASE_MANAGEMENT' as TaskType,
  CASEBURIAL: 'CASE_BURIAL' as TaskType,
  CONTACTTRACING: 'CONTACT_TRACING' as TaskType,
  SAMPLECOLLECTION: 'SAMPLE_COLLECTION' as TaskType,
  CONTACTINVESTIGATION: 'CONTACT_INVESTIGATION' as TaskType,
  CONTACTFOLLOWUP: 'CONTACT_FOLLOW_UP' as TaskType,
  ANIMALTESTING: 'ANIMAL_TESTING' as TaskType,
  EVENTINVESTIGATION: 'EVENT_INVESTIGATION' as TaskType,
  EVENTCONTINUEINVESTIGATION: 'EVENT_CONTINUE_INVESTIGATION' as TaskType,
  EVENTREQUESTADDITIONALINFORMATION: 'EVENT_REQUEST_ADDITIONAL_INFORMATION' as TaskType,
  TREATMENTCENTERESTABLISHMENT: 'TREATMENT_CENTER_ESTABLISHMENT' as TaskType,
  ENVIRONMENTALHEALTHACTIVITIES: 'ENVIRONMENTAL_HEALTH_ACTIVITIES' as TaskType,
  DECONTAMINATIONDISINFECTIONACTIVITIES: 'DECONTAMINATION_DISINFECTION_ACTIVITIES' as TaskType,
  QUARANTINEPLACE: 'QUARANTINE_PLACE' as TaskType,
  VACCINATIONACTIVITIES: 'VACCINATION_ACTIVITIES' as TaskType,
  ANIMALDEPOPULATION: 'ANIMAL_DEPOPULATION' as TaskType,
  OTHER: 'OTHER' as TaskType,
  DAILYREPORTGENERATION: 'DAILY_REPORT_GENERATION' as TaskType,
  SURVEILLANCEREPORTGENERATION: 'SURVEILLANCE_REPORT_GENERATION' as TaskType,
  WEEKLYREPORTGENERATION: 'WEEKLY_REPORT_GENERATION' as TaskType,
};
