/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseReferenceDto } from './caseReferenceDto';
import { ContactReferenceDto } from './contactReferenceDto';
import { EventReferenceDto } from './eventReferenceDto';
import { ReferenceDto } from './referenceDto';
import { TaskContext } from './taskContext';
import { TaskPriority } from './taskPriority';
import { TaskStatus } from './taskStatus';
import { TaskType } from './taskType';
import { TravelEntryReferenceDto } from './travelEntryReferenceDto';
import { UserReferenceDto } from './userReferenceDto';

export interface TaskDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  taskContext: TaskContext;
  caze?: CaseReferenceDto;
  event?: EventReferenceDto;
  contact?: ContactReferenceDto;
  travelEntry?: TravelEntryReferenceDto;
  taskType: TaskType;
  priority?: TaskPriority;
  dueDate: Date;
  suggestedStart?: Date;
  taskStatus?: TaskStatus;
  statusChangeDate?: Date;
  perceivedStart?: Date;
  creatorUser?: UserReferenceDto;
  creatorComment?: string;
  assigneeUser: UserReferenceDto;
  assigneeReply?: string;
  closedLat?: number;
  closedLon?: number;
  closedLatLonAccuracy?: number;
  contextReference?: ReferenceDto;
}
