/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { YesNoUnknown } from '../app.constants';
import { DiseaseVariant } from './diseaseVariant';
import { DistrictReferenceDto } from './districtReferenceDto';
import { CommunityReferenceDto, PersonReferenceDto } from './models';
import { PointOfEntryReferenceDto } from './pointOfEntryReferenceDto';
import { RegionReferenceDto } from './regionReferenceDto';
import { UserReferenceDto } from './userReferenceDto';

export interface TravelEntryDto {
  uuid: string;
  externalId?: string;
  responsibleRegion: RegionReferenceDto;
  responsibleDistrict: DistrictReferenceDto;
  responsibleCommunity: CommunityReferenceDto;
  pointOfEntryRegion: RegionReferenceDto;
  pointOfEntryDistrict: DistrictReferenceDto;
  person: PersonReferenceDto;
  pointOfEntry: PointOfEntryReferenceDto;
  pointOfEntryDetails: string;
  recovered: boolean;
  vaccinated: boolean;
  testedNegative: boolean;
  reportingUser: UserReferenceDto;
  reportDate: Date;
  quarantineEnd: Date;
  disease: string;
  diseaseVariant: DiseaseVariant;
  diseaseDetails: string;
  diseaseVariantDetails: string;
  quarantineHomePossible: YesNoUnknown;
  quarantineHomePossibleComment: string;
  quarantineHomeSupplyEnsured: YesNoUnknown;
  quarantineHomeSupplyEnsuredComment: string;
  quarantine: string;
  quarantineFrom: Date;
  quarantineTo: Date;
  quarantineExtended: boolean;
  quarantineReduced: boolean;
  quarantineTypeDetails: string;
  quarantineOrderedVerbally: boolean;
  quarantineOrderedVerballyDate: Date;
  quarantineOrderedOfficialDocument: boolean;
  quarantineOrderedOfficialDocumentDate: Date;
  quarantineOfficialOrderSent: boolean;
  quarantineOfficialOrderSentDate: Date;
  quarantineHelpNeeded: boolean;
}
