/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TravelEntryDto {
  uuid: string;
  externalId?: string;
  firstName: string;
  lastName: string;
  district: string;
  pointOfEntry: string;
  recovered: boolean;
  vaccinated: boolean;
  testedNegative: boolean;
  quarantineEnd: Date;
}
