/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TreatmentType =
  | 'DRUG_INTAKE'
  | 'ORAL_REHYDRATION_SALTS'
  | 'BLOOD_TRANSFUSION'
  | 'RENAL_REPLACEMENT_THERAPY'
  | 'IV_FLUID_THERAPY'
  | 'OXYGEN_THERAPY'
  | 'INVASIVE_MECHANICAL_VENTILATION'
  | 'VASOPRESSORS_INOTROPES'
  | 'OTHER';
