export type TreatmentType =
  | 'DRUG_INTAKE'
  | 'ORAL_REHYDRATION_SALTS'
  | 'BLOOD_TRANSFUSION'
  | 'RENAL_REPLACEMENT_THERAPY'
  | 'IV_FLUID_THERAPY'
  | 'OXYGEN_THERAPY'
  | 'INVASIVE_MECHANICAL_VENTILATION'
  | 'VASOPRESSORS_INOTROPES'
  | 'OTHER';
