/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TreatmentType =
  | 'DRUG_INTAKE'
  | 'ORAL_REHYDRATION_SALTS'
  | 'BLOOD_TRANSFUSION'
  | 'RENAL_REPLACEMENT_THERAPY'
  | 'IV_FLUID_THERAPY'
  | 'OXYGEN_THERAPY'
  | 'INVASIVE_MECHANICAL_VENTILATION'
  | 'VASOPRESSORS_INOTROPES'
  | 'OTHER';

export const TreatmentType = {
  DRUG_INTAKE: 'DRUG_INTAKE' as TreatmentType,
  ORAL_REHYDRATION_SALTS: 'ORAL_REHYDRATION_SALTS' as TreatmentType,
  BLOOD_TRANSFUSION: 'BLOOD_TRANSFUSION' as TreatmentType,
  RENAL_REPLACEMENT_THERAPY: 'RENAL_REPLACEMENT_THERAPY' as TreatmentType,
  IV_FLUID_THERAPY: 'IV_FLUID_THERAPY' as TreatmentType,
  OXYGEN_THERAPY: 'OXYGEN_THERAPY' as TreatmentType,
  INVASIVE_MECHANICAL_VENTILATION: 'INVASIVE_MECHANICAL_VENTILATION' as TreatmentType,
  VASOPRESSORS_INOTROPES: 'VASOPRESSORS_INOTROPES' as TreatmentType,
  OTHER: 'OTHER' as TreatmentType,
};
