/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeOfPlace =
  | 'FACILITY'
  | 'FACILITY_23_IFSG'
  | 'COMMUNITY_FACILITY'
  | 'FACILITY_36_IFSG'
  | 'FESTIVITIES'
  | 'HOME'
  | 'MEANS_OF_TRANSPORT'
  | 'PUBLIC_PLACE'
  | 'SCATTERED'
  | 'UNKNOWN'
  | 'OTHER';

export const TypeOfPlace = {
  FACILITY: 'FACILITY' as TypeOfPlace,
  FACILITY_23_IFSG: 'FACILITY_23_IFSG' as TypeOfPlace,
  COMMUNITY_FACILITY: 'COMMUNITY_FACILITY' as TypeOfPlace,
  FACILITY_36_IFSG: 'FACILITY_36_IFSG' as TypeOfPlace,
  FESTIVITIES: 'FESTIVITIES' as TypeOfPlace,
  HOME: 'HOME' as TypeOfPlace,
  MEANS_OF_TRANSPORT: 'MEANS_OF_TRANSPORT' as TypeOfPlace,
  PUBLIC_PLACE: 'PUBLIC_PLACE' as TypeOfPlace,
  SCATTERED: 'SCATTERED' as TypeOfPlace,
  UNKNOWN: 'UNKNOWN' as TypeOfPlace,
  OTHER: 'OTHER' as TypeOfPlace,
};
