/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeOfAnimal =
  | 'BAT'
  | 'POULTRY'
  | 'CAMEL'
  | 'CANIDAE'
  | 'CAT'
  | 'CATTLE'
  | 'DOG'
  | 'PRIMATE'
  | 'SNAKE'
  | 'SWINE'
  | 'RABBIT'
  | 'RODENT'
  | 'TICK'
  | 'FLEA'
  | 'OTHER';

export const TypeOfAnimal = {
  BAT: 'BAT' as TypeOfAnimal,
  POULTRY: 'POULTRY' as TypeOfAnimal,
  CAMEL: 'CAMEL' as TypeOfAnimal,
  CANIDAE: 'CANIDAE' as TypeOfAnimal,
  CAT: 'CAT' as TypeOfAnimal,
  CATTLE: 'CATTLE' as TypeOfAnimal,
  DOG: 'DOG' as TypeOfAnimal,
  PRIMATE: 'PRIMATE' as TypeOfAnimal,
  SNAKE: 'SNAKE' as TypeOfAnimal,
  SWINE: 'SWINE' as TypeOfAnimal,
  RABBIT: 'RABBIT' as TypeOfAnimal,
  RODENT: 'RODENT' as TypeOfAnimal,
  TICK: 'TICK' as TypeOfAnimal,
  FLEA: 'FLEA' as TypeOfAnimal,
  OTHER: 'OTHER' as TypeOfAnimal,
};
