/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UserRole =
  | 'ADMIN'
  | 'NATIONAL_USER'
  | 'SURVEILLANCE_SUPERVISOR'
  | 'ADMIN_SUPERVISOR'
  | 'SURVEILLANCE_OFFICER'
  | 'HOSPITAL_INFORMANT'
  | 'COMMUNITY_OFFICER'
  | 'COMMUNITY_INFORMANT'
  | 'CASE_SUPERVISOR'
  | 'CASE_OFFICER'
  | 'CONTACT_SUPERVISOR'
  | 'CONTACT_OFFICER'
  | 'EVENT_OFFICER'
  | 'LAB_USER'
  | 'EXTERNAL_LAB_USER'
  | 'NATIONAL_OBSERVER'
  | 'STATE_OBSERVER'
  | 'DISTRICT_OBSERVER'
  | 'NATIONAL_CLINICIAN'
  | 'POE_INFORMANT'
  | 'POE_SUPERVISOR'
  | 'POE_NATIONAL_USER'
  | 'IMPORT_USER'
  | 'REST_EXTERNAL_VISITS_USER'
  | 'REST_USER'
  | 'SORMAS_TO_SORMAS_CLIENT'
  | 'BAG_USER';
