/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Vaccination } from './vaccination';
import { VaccinationInfoSource } from './vaccinationInfoSource';
import { Vaccine } from './vaccine';
import { VaccineManufacturer } from './vaccineManufacturer';

export interface VaccinationInfoDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  vaccination?: Vaccination;
  vaccinationDoses?: string;
  firstVaccinationDate?: Date;
  lastVaccinationDate?: Date;
  vaccinationInfoSource?: VaccinationInfoSource;
  vaccineName?: Vaccine;
  otherVaccineName?: string;
  vaccineManufacturer?: VaccineManufacturer;
  otherVaccineManufacturer?: string;
  vaccineInn?: string;
  vaccineBatchNumber?: string;
  vaccineUniiCode?: string;
  vaccineAtcCode?: string;
}
