/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Vaccine =
  | 'COMIRNATY'
  | 'MRNA_1273'
  | 'OXFORD_ASTRA_ZENECA'
  | 'AD26_COV2_S'
  | 'NVX_COV_2373'
  | 'SANOFI_GSK'
  | 'UNKNOWN'
  | 'OTHER';
