/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HealthConditionsDto } from './healthConditionsDto';
import { ImmunizationReferenceDto } from './immunizationReferenceDto';
import { Trimester } from './trimester';
import { UserReferenceDto } from './userReferenceDto';
import { VaccinationInfoSource } from './vaccinationInfoSource';
import { Vaccine } from './vaccine';
import { VaccineManufacturer } from './vaccineManufacturer';
import { YesNoUnknown } from './yesNoUnknown';

export interface VaccinationDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  immunization: ImmunizationReferenceDto;
  healthConditions: HealthConditionsDto;
  reportDate: Date;
  reportingUser?: UserReferenceDto;
  vaccinationDate?: Date;
  vaccineName?: Vaccine;
  otherVaccineName?: string;
  vaccineManufacturer?: VaccineManufacturer;
  otherVaccineManufacturer?: string;
  vaccineType?: string;
  vaccineDose?: string;
  vaccineInn?: string;
  vaccineBatchNumber?: string;
  vaccineUniiCode?: string;
  vaccineAtcCode?: string;
  vaccinationInfoSource?: VaccinationInfoSource;
  pregnant?: YesNoUnknown;
  trimester?: Trimester;
}
