/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type VaccineManufacturer =
  | 'BIONTECH_PFIZER'
  | 'MODERNA'
  | 'ASTRA_ZENECA'
  | 'JOHNSON_JOHNSON'
  | 'NOVAVAX'
  | 'SANOFI_GSK'
  | 'UNKNOWN'
  | 'OTHER';

export const VaccineManufacturer = {
  BIONTECH_PFIZER: 'BIONTECH_PFIZER' as VaccineManufacturer,
  MODERNA: 'MODERNA' as VaccineManufacturer,
  ASTRA_ZENECA: 'ASTRA_ZENECA' as VaccineManufacturer,
  JOHNSON_JOHNSON: 'JOHNSON_JOHNSON' as VaccineManufacturer,
  NOVAVAX: 'NOVAVAX' as VaccineManufacturer,
  SANOFI_GSK: 'SANOFI_GSK' as VaccineManufacturer,
  UNKNOWN: 'UNKNOWN' as VaccineManufacturer,
  OTHER: 'OTHER' as VaccineManufacturer,
};
