/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type VaccinationInfoSource =
  | 'VACCINATION_CARD'
  | 'ORAL_COMMUNICATION'
  | 'NO_EVIDENCE'
  | 'UNKNOWN';

export const VaccinationInfoSource = {
  VACCINATION_CARD: 'VACCINATION_CARD' as VaccinationInfoSource,
  ORAL_COMMUNICATION: 'ORAL_COMMUNICATION' as VaccinationInfoSource,
  NO_EVIDENCE: 'NO_EVIDENCE' as VaccinationInfoSource,
  UNKNOWN: 'UNKNOWN' as VaccinationInfoSource,
};
