/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Vaccine =
  | 'COMIRNATY'
  | 'MRNA_1273'
  | 'OXFORD_ASTRA_ZENECA'
  | 'AD26_COV2_S'
  | 'NVX_COV_2373'
  | 'SANOFI_GSK'
  | 'UNKNOWN'
  | 'OTHER';

export const Vaccine = {
  COMIRNATY: 'COMIRNATY' as Vaccine,
  MRNA_1273: 'MRNA_1273' as Vaccine,
  OXFORD_ASTRA_ZENECA: 'OXFORD_ASTRA_ZENECA' as Vaccine,
  AD26_COV2_S: 'AD26_COV2_S' as Vaccine,
  NVX_COV_2373: 'NVX_COV_2373' as Vaccine,
  SANOFI_GSK: 'SANOFI_GSK' as Vaccine,
  UNKNOWN: 'UNKNOWN' as Vaccine,
  OTHER: 'OTHER' as Vaccine,
};
