/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disease } from './disease';
import { TemperatureSource } from './temperatureSource';
import { UserReferenceDto } from './userReferenceDto';
import { VisitOrigin } from './visitOrigin';
import { VisitStatus } from './visitStatus';

export interface VisitIndexDto {
  pseudonymized?: boolean;
  id?: number;
  uuid?: string;
  visitDateTime?: Date;
  visitStatus?: VisitStatus;
  visitRemarks?: string;
  disease?: Disease;
  symptomatic?: boolean;
  temperature?: number;
  temperatureSource?: TemperatureSource;
  origin?: VisitOrigin;
  visitUser?: UserReferenceDto;
  inJurisdiction?: boolean;
}
