/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type WaterSource =
  | 'PIPE_NETWORK'
  | 'COMMUNITY_BOREHOLE_WELL'
  | 'PRIVATE_BOREHOLE_WELL'
  | 'STREAM'
  | 'OTHER';

export const WaterSource = {
  PIPENETWORK: 'PIPE_NETWORK' as WaterSource,
  COMMUNITYBOREHOLEWELL: 'COMMUNITY_BOREHOLE_WELL' as WaterSource,
  PRIVATEBOREHOLEWELL: 'PRIVATE_BOREHOLE_WELL' as WaterSource,
  STREAM: 'STREAM' as WaterSource,
  OTHER: 'OTHER' as WaterSource,
};
