/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.57.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommunityReferenceDto } from './communityReferenceDto';
import { DistrictReferenceDto } from './districtReferenceDto';
import { FacilityReferenceDto } from './facilityReferenceDto';
import { UserReferenceDto } from './userReferenceDto';
import { WeeklyReportEntryDto } from './weeklyReportEntryDto';

export interface WeeklyReportDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  reportingUser?: UserReferenceDto;
  reportDateTime?: Date;
  district?: DistrictReferenceDto;
  community?: CommunityReferenceDto;
  healthFacility?: FacilityReferenceDto;
  assignedOfficer?: UserReferenceDto;
  totalNumberOfCases?: number;
  year?: number;
  epiWeek?: number;
  reportEntries?: Array<WeeklyReportEntryDto>;
}
