/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type WorkEnvironment =
  | 'UNKNOWN'
  | 'OPEN_SPACE_OFFICE'
  | 'FOOD_SECTOR'
  | 'BUILDING_SECTOR'
  | 'LOGISTICS_CENTER'
  | 'OTHER';

export const WorkEnvironment = {
  UNKNOWN: 'UNKNOWN' as WorkEnvironment,
  OPEN_SPACE_OFFICE: 'OPEN_SPACE_OFFICE' as WorkEnvironment,
  FOOD_SECTOR: 'FOOD_SECTOR' as WorkEnvironment,
  BUILDING_SECTOR: 'BUILDING_SECTOR' as WorkEnvironment,
  LOGISTICS_CENTER: 'LOGISTICS_CENTER' as WorkEnvironment,
  OTHER: 'OTHER' as WorkEnvironment,
};
