/* eslint-disable @typescript-eslint/no-redeclare */
/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.64.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type YesNoUnknown = 'YES' | 'NO' | 'UNKNOWN';

export const YesNoUnknown = {
  YES: 'YES' as YesNoUnknown,
  NO: 'NO' as YesNoUnknown,
  UNKNOWN: 'UNKNOWN' as YesNoUnknown,
};
