export const mockData = [
  {
    creationDate: 1613468467495,
    changeDate: 1613487711033,
    uuid: 'R674FI-J5G2Z7-GOEVQR-WAQCCKGM',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'W7OKUK-PWEWZ2-KQB4AO-M2BNKHJY',
      caption: 'feb 16',
      firstName: 'feb',
      lastName: '16',
    },
    reportDate: 1612738800000,
    reportingUser: {
      uuid: 'VJPSIM-KH4EV4-J4X77G-MBZO2KYU',
      caption: 'Surveillance SUPERVISOR - Überwachungsleitung',
      firstName: 'Surveillance',
      lastName: 'Supervisor',
    },
    caseClassification: 'SUSPECT',
    caseIdentificationSource: 'SCREENING',
    screeningType: 'ON_ENTRY_FROM_RISK_AREA',
    classificationUser: {
      uuid: 'VJPSIM-KH4EV4-J4X77G-MBZO2KYU',
      caption: 'Surveillance SUPERVISOR - Überwachungsleitung',
      firstName: 'Surveillance',
      lastName: 'Supervisor',
    },
    classificationDate: 1613468488459,
    investigationStatus: 'PENDING',
    outcome: 'DECEASED',
    outcomeDate: 1613430000000,
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1613468467511,
      changeDate: 1613487711034,
      uuid: 'VPNJL5-NQL6HN-WIEAX5-Y4A4SD4E',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1613468467518,
      changeDate: 1613468467519,
      uuid: 'QFPOYH-3Y4FNP-WUJDIE-HUIJ2MWI',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1613468467510,
      changeDate: 1613487711035,
      uuid: 'RJTNFH-DR5KEY-HELTES-C5CHKL2U',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1613468467520,
      changeDate: 1613468467520,
      uuid: 'TIVB4R-H3Y7SR-VYOQRN-6E7TSHLQ',
    },
    clinicalCourse: {
      creationDate: 1613468467508,
      changeDate: 1613468467508,
      uuid: 'QUR6XO-KQZYE5-J4EOBS-OKIB2F3Y',
      healthConditions: {
        creationDate: 1613468467508,
        changeDate: 1613468467508,
        uuid: 'SFBZ7X-YZ7TUN-RAFZAU-NSWISFVI',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1613468467513,
      changeDate: 1613468467513,
      uuid: 'SM47OG-SO5TZW-BUKNSD-TPP3KAUM',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1613468467517,
      changeDate: 1613468467517,
      uuid: 'UJJXP3-LZZUJE-JODU7B-UDM5CI3Y',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1613948400000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: true,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1613410155833,
    changeDate: 1613466808901,
    uuid: 'UONI3Y-TSDR66-MB7SJM-7Q3ISOXE',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'SKL2TJ-C3JM4S-EHEYZA-VC36CJCI',
      caption: 'Haam KORN',
      firstName: 'Haam',
      lastName: 'Korn',
    },
    reportDate: 1609542000000,
    reportingUser: {
      uuid: 'XB45HE-DFRW7X-ITDKMQ-BDRHKDSQ',
      caption: 'ad MIN - Administrator',
      firstName: 'ad',
      lastName: 'min',
    },
    caseClassification: 'NO_CASE',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    vaccination: 'VACCINATED',
    firstVaccinationDate: 1613430000000,
    lastVaccinationDate: 1613430000000,
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1613410155841,
      changeDate: 1613466808904,
      uuid: 'UGXUHU-FRFAGW-UMGYPN-UFBPCPBQ',
      admittedToHealthFacility: 'UNKNOWN',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1613410155844,
      changeDate: 1613410155844,
      uuid: 'WZAKHK-Y4KZUQ-XDZCQO-ONMLSJUM',
      pseudonymized: false,
      chillsSweats: 'NO',
      fever: 'NO',
      symptomatic: false,
      feelingIll: 'NO',
    },
    epiData: {
      creationDate: 1613410155840,
      changeDate: 1613466808904,
      uuid: 'XI52ZE-MKEG7M-P5CFVT-AVLB2DH4',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1613410155845,
      changeDate: 1613410155845,
      uuid: 'TVFQKF-DW5MA7-QTRDYR-BVXYKEEI',
    },
    clinicalCourse: {
      creationDate: 1613410155839,
      changeDate: 1613410155839,
      uuid: 'WD6FCZ-OKTNS4-GI6O7C-Y3RU2FPM',
      healthConditions: {
        creationDate: 1613410155839,
        changeDate: 1613410155839,
        uuid: 'WEBDZN-6UVBCW-Y7PC4S-GLKY2HR4',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1613410155842,
      changeDate: 1613410155842,
      uuid: 'QR7YPI-M6BOMI-WWMRVZ-DY7ICMTY',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1613410155843,
      changeDate: 1613410155843,
      uuid: 'Q352ZS-BXJR7H-ION34A-UMOFCFVY',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'HOME',
    quarantineFrom: 1609455600000,
    quarantineTo: 1611097200000,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1610751600000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    reportingDistrict: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    notACaseReasonNegativeTest: true,
    notACaseReasonPhysicianInformation: true,
    notACaseReasonDifferentPathogen: true,
    notACaseReasonOther: true,
    notACaseReasonDetails: 'test export then import',
  },
  {
    creationDate: 1613410344796,
    changeDate: 1613410344844,
    uuid: 'UONI3Y-TSDR66-MB7SJM-7Q3ISOBB',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'VSXAGU-DRQI2V-JHXVAD-F5TESM5Y',
      caption: 'Test KOR',
      firstName: 'Test',
      lastName: 'Kor',
    },
    reportDate: 1609542000000,
    reportingUser: {
      uuid: 'XB45HE-DFRW7X-ITDKMQ-BDRHKDSQ',
      caption: 'ad MIN - Administrator',
      firstName: 'ad',
      lastName: 'min',
    },
    caseClassification: 'NO_CASE',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1613410344802,
      changeDate: 1613410344802,
      uuid: 'TL32EC-Y2GFFJ-BKJ7UR-H7EQCPNU',
      admittedToHealthFacility: 'UNKNOWN',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1613410344805,
      changeDate: 1613410344805,
      uuid: 'VWDZMI-5FYA6P-BQCZEQ-Q6TUCKU4',
      pseudonymized: false,
      chillsSweats: 'NO',
      fever: 'NO',
      symptomatic: false,
      feelingIll: 'NO',
    },
    epiData: {
      creationDate: 1613410344801,
      changeDate: 1613410344801,
      uuid: 'XIXKHV-IXJFM3-AVG5UO-ZPMTKCEU',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1613410344806,
      changeDate: 1613410344806,
      uuid: 'SFNIOM-WFMY7W-UG5L2S-DMN42DU4',
    },
    clinicalCourse: {
      creationDate: 1613410344800,
      changeDate: 1613410344800,
      uuid: 'QPN7HU-REHHSY-N5CEB2-5HDF2OXE',
      healthConditions: {
        creationDate: 1613410344800,
        changeDate: 1613410344800,
        uuid: 'VZVATZ-D3YCSZ-CHOCY2-CO2OSDMM',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1613410344803,
      changeDate: 1613410344803,
      uuid: 'V5HM36-WXI774-BQAJ22-YSHY2LZY',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1613410344804,
      changeDate: 1613410344804,
      uuid: 'TPKSDI-IAURVW-RTHIZF-V6IJ2OZ4',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'HOME',
    quarantineFrom: 1609455600000,
    quarantineTo: 1611097200000,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1610751600000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
    notACaseReasonDetails: 'test export then import',
  },
  {
    creationDate: 1613408277174,
    changeDate: 1613408277353,
    uuid: 'VWBK7E-MW35GG-4IWSMQ-C2GT2NUM',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'QZ5LLY-VDXWLU-VGDF5J-IZVLSJWQ',
      caption: 'Jens HSSAIN',
      firstName: 'Jens',
      lastName: 'hssain',
    },
    reportDate: 1609542000000,
    reportingUser: {
      uuid: 'XB45HE-DFRW7X-ITDKMQ-BDRHKDSQ',
      caption: 'ad MIN - Administrator',
      firstName: 'ad',
      lastName: 'min',
    },
    caseClassification: 'NO_CASE',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1613408277182,
      changeDate: 1613408277182,
      uuid: 'T7G7H4-DKHRJH-SHIIET-O5XSCNLM',
      admittedToHealthFacility: 'UNKNOWN',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1613408277186,
      changeDate: 1613408277186,
      uuid: 'SLYV2D-KFTBXY-SOSQ4L-YZMK2CLM',
      pseudonymized: false,
      chillsSweats: 'NO',
      fever: 'NO',
      symptomatic: false,
      feelingIll: 'NO',
    },
    epiData: {
      creationDate: 1613408277181,
      changeDate: 1613408277181,
      uuid: 'VC523G-FUC4JV-5ZZCR6-VXPMKBDE',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1613408277188,
      changeDate: 1613408277188,
      uuid: 'UTMYWE-JVQL5P-ONQDD7-5GEKSGRQ',
    },
    clinicalCourse: {
      creationDate: 1613408277180,
      changeDate: 1613408277180,
      uuid: 'UHMVYY-JC3V5J-BC65BS-4WAZCE3U',
      healthConditions: {
        creationDate: 1613408277180,
        changeDate: 1613408277180,
        uuid: 'WVCQQ5-LQNYUJ-QQG7M3-HOOC2N7Q',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1613408277184,
      changeDate: 1613408277184,
      uuid: 'WF76JC-JWVFO4-KK3P26-IS3ESEOA',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1613408277185,
      changeDate: 1613408277185,
      uuid: 'TLKARE-AG47YA-EVAFZO-HOCBCHU4',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'HOME',
    quarantineFrom: 1609455600000,
    quarantineTo: 1611097200000,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1610751600000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
    notACaseReasonDetails: 'Check the recent import',
  },
  {
    creationDate: 1613377928663,
    changeDate: 1613377928777,
    uuid: 'SJ7NXK-YM7R6O-6UOGN7-YL2U2MJI',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'RHHAZQ-WXCN54-432RZH-ESQASBIU',
      caption: 'KarlA KLEINSCHMIDT',
      firstName: 'KarlA',
      lastName: 'Kleinschmidt',
    },
    reportDate: 1613257200000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1613377928669,
      changeDate: 1613377928669,
      uuid: 'VIQNJV-QKSJ3W-7EW65P-IJ6KSI4Q',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1613377928672,
      changeDate: 1613377928672,
      uuid: 'RVBDLV-N6QPR2-6HW33V-XMNUCPA4',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1613377893312,
      changeDate: 1613377928668,
      uuid: 'R5U7O3-JF6CH6-JHGR2F-GOTAKIBY',
      pseudonymized: false,
      contactWithSourceCaseKnown: 'YES',
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1613377928674,
      changeDate: 1613377928674,
      uuid: 'TLBYVS-UKYHAW-WYXZLB-LZWPKFO4',
    },
    clinicalCourse: {
      creationDate: 1613377928667,
      changeDate: 1613377928667,
      uuid: 'ROXC2L-XWAQFB-PDSYFU-4V76SPCU',
      healthConditions: {
        creationDate: 1613377893313,
        changeDate: 1613377928667,
        uuid: 'U7OJ66-UZOY5C-ISJEHY-7Q3YCI4E',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1613377928670,
      changeDate: 1613377928670,
      uuid: 'WVKABO-D5D6DI-C7FG6K-ARHCSCPU',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1613377928671,
      changeDate: 1613377928671,
      uuid: 'U3MTWW-NWCT54-SGFZEE-6TBOSKSQ',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1614466800000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    wasInQuarantineBeforeIsolation: 'YES',
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1613149984326,
    changeDate: 1613150074139,
    uuid: 'VZDBPU-NUZZ26-DVOW7J-OIS3KPFM',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'V7JMTZ-JRVYWB-7HWN57-AUUJKMQM',
      caption: 'Jacob SENS',
      firstName: 'Jacob',
      lastName: 'sens',
    },
    reportDate: 1609542000000,
    reportingUser: {
      uuid: 'XB45HE-DFRW7X-ITDKMQ-BDRHKDSQ',
      caption: 'ad MIN - Administrator',
      firstName: 'ad',
      lastName: 'min',
    },
    caseClassification: 'NO_CASE',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1613149984335,
      changeDate: 1613150074140,
      uuid: 'UTGYP2-WJBZB3-LRCLNO-TZ7CKIJE',
      admittedToHealthFacility: 'UNKNOWN',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1613149984339,
      changeDate: 1613149984339,
      uuid: 'QJYY4F-T7RLN2-5ZKFX5-LK26CHJA',
      pseudonymized: false,
      chillsSweats: 'NO',
      fever: 'NO',
      symptomatic: false,
      feelingIll: 'NO',
    },
    epiData: {
      creationDate: 1613149984334,
      changeDate: 1613150074141,
      uuid: 'UJSLCQ-L7WIUY-BIZGSV-QPMSKBHM',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1613149984340,
      changeDate: 1613149984340,
      uuid: 'Q2FTSC-AVYT6K-BUBV5P-BH3GKLSM',
    },
    clinicalCourse: {
      creationDate: 1613149984333,
      changeDate: 1613149984333,
      uuid: 'SNWHCL-Z6LORF-Z67KUY-QQQRKL5U',
      healthConditions: {
        creationDate: 1613149984332,
        changeDate: 1613149984333,
        uuid: 'X5RABC-45UDJM-ZOG5GS-FFWBSEJ4',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1613149984336,
      changeDate: 1613149984336,
      uuid: 'VUZLBM-TJ4523-IGRZAD-CCCZKKJ4',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1613149984337,
      changeDate: 1613149984337,
      uuid: 'UJTONW-YC4PPF-IG4QOK-UKAM2PFM',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'HOME',
    quarantineFrom: 1609455600000,
    quarantineTo: 1611097200000,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1610751600000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: true,
    notACaseReasonOther: false,
    notACaseReasonDetails: 'Check the import',
  },
  {
    creationDate: 1610547114437,
    changeDate: 1613149465112,
    uuid: 'UONI3Y-TSDR66-MB7SJM-7Q3ISDVE',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'WFM753-GPUMBQ-4N7XM6-ZXRKKPNU',
      caption: 'Tatü WEICH',
      firstName: 'Tatü',
      lastName: 'Weich',
    },
    epidNumber: 'DEF-REG-DIS-21-002',
    reportDate: 1609542000000,
    reportingUser: {
      uuid: 'TIF63T-JVFKOF-DEXESZ-QXHDCO3I',
      caption: 'Sormas to Sormas CLIENT - Sormas zu Sormas Client',
      firstName: 'Sormas to Sormas',
      lastName: 'Client',
    },
    caseClassification: 'NO_CASE',
    classificationUser: {
      uuid: 'VJPSIM-KH4EV4-J4X77G-MBZO2KYU',
      caption: 'Surveillance SUPERVISOR - Überwachungsleitung',
      firstName: 'Surveillance',
      lastName: 'Supervisor',
    },
    classificationDate: 1613149301449,
    clinicalConfirmation: 'YES',
    epidemiologicalConfirmation: 'YES',
    laboratoryDiagnosticConfirmation: 'YES',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    healthFacilityDetails: '',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1610547114444,
      changeDate: 1613376115775,
      uuid: 'SQYINZ-YM7ESS-FZJJBE-CUAVCPQU',
      admittedToHealthFacility: 'UNKNOWN',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1610547114448,
      changeDate: 1610547168802,
      uuid: 'UZURWX-IXSUPU-D2JZQR-OFQY2P2M',
      pseudonymized: false,
      chillsSweats: 'NO',
      fever: 'NO',
      symptomatic: false,
      feelingIll: 'NO',
    },
    epiData: {
      creationDate: 1610547114443,
      changeDate: 1613376115776,
      uuid: 'Q7NNFA-Z7T5YQ-4C6CAS-6P6RKMMQ',
      pseudonymized: false,
      exposureDetailsKnown: 'YES',
      contactWithSourceCaseKnown: 'UNKNOWN',
      highTransmissionRiskArea: 'YES',
      largeOutbreaksArea: 'YES',
      exposures: [
        {
          creationDate: 1612864853059,
          changeDate: 1612864853061,
          uuid: 'Q3L4HR-NVXB2M-KERC2G-QJVSKA7A',
          pseudonymized: false,
          reportingUser: {
            uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
            caption: 'National USER - Nationale*r Benutzer*in',
            firstName: 'National',
            lastName: 'User',
          },
          exposureType: 'UNKNOWN',
          location: {
            creationDate: 1612864853061,
            changeDate: 1612864853061,
            uuid: 'WWQRN6-OXDOGN-KQYMDE-QKPB2DPQ',
            pseudonymized: false,
          },
          exposureRole: 'STUDENT',
        },
      ],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1610547114450,
      changeDate: 1610547114450,
      uuid: 'RBZLVH-D5AUCL-24A6AI-XUGA2DZQ',
    },
    clinicalCourse: {
      creationDate: 1610547114442,
      changeDate: 1610547114442,
      uuid: 'S76LXR-VYOAYM-EKFDU3-PG6O2GDA',
      healthConditions: {
        creationDate: 1610547114442,
        changeDate: 1610547114442,
        uuid: 'TEZ3EB-ODA5RY-2R7SR4-YI3OSENA',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1610547114445,
      changeDate: 1610547114445,
      uuid: 'R4OP2J-LDSWV6-7XMORD-GQGESGUQ',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1610547114446,
      changeDate: 1610547114446,
      uuid: 'V5L3YF-IKM7SM-BWU2QG-JF632GOU',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'HOME',
    quarantineFrom: 1609455600000,
    quarantineTo: 1611097200000,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineHomePossible: 'NO',
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1610751600000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    prohibitionToWork: 'YES',
    prohibitionToWorkFrom: 1609455600000,
    prohibitionToWorkUntil: 1611097200000,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: true,
    notACaseReasonDetails: 'no reason',
  },
  {
    creationDate: 1611048983355,
    changeDate: 1613147773928,
    uuid: 'UJZTOK-54K7LQ-A7VYHW-RQZBCHIE',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'XBFVKX-PBECFN-MXOPKE-Q6HW2EZ4',
      caption: 'AB-3763 LN_3763',
      firstName: 'AB-3763',
      lastName: 'LN_3763',
    },
    epidNumber: 'DEF-REG-DIS-21-003',
    reportDate: 1611010800000,
    reportingUser: {
      uuid: 'TIF63T-JVFKOF-DEXESZ-QXHDCO3I',
      caption: 'Sormas to Sormas CLIENT - Sormas zu Sormas Client',
      firstName: 'Sormas to Sormas',
      lastName: 'Client',
    },
    caseClassification: 'SUSPECT',
    classificationUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    classificationDate: 1613147773380,
    clinicalConfirmation: 'YES',
    epidemiologicalConfirmation: 'YES',
    laboratoryDiagnosticConfirmation: 'YES',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    healthFacilityDetails: 'hoe of 3763',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1611048983364,
      changeDate: 1613147773930,
      uuid: 'UPHSSR-O6FHJS-UXLJ4Z-JZOFSMWA',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1611048983371,
      changeDate: 1611048983371,
      uuid: 'SKZ675-S7TPAF-TKAXC5-ROBMSEX4',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1611048983363,
      changeDate: 1613147773931,
      uuid: 'VXAKR3-3E4QQC-OFIZGC-53322GUQ',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1611048983374,
      changeDate: 1611048983374,
      uuid: 'TCL44S-XYGI3V-ORRZPH-2ARFKOJA',
    },
    clinicalCourse: {
      creationDate: 1611048983362,
      changeDate: 1611048983362,
      uuid: 'RMKJBK-Z55CXY-HJZKSL-2CM22MWI',
      healthConditions: {
        creationDate: 1611048983362,
        changeDate: 1611048983362,
        uuid: 'VCS757-N2LLBJ-7FZRG4-7D5DCN6Y',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1611048983365,
      changeDate: 1611048983366,
      uuid: 'X5YBEU-57KOJ7-JIRWQD-5V24SHSM',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1611048983368,
      changeDate: 1611048983368,
      uuid: 'Q2DKAN-BZ5454-3DQXQM-CNECKNRI',
    },
    caseOrigin: 'IN_COUNTRY',
    externalID: '4044',
    externalToken: '123404',
    sharedToCountry: false,
    nosocomialOutbreak: true,
    infectionSetting: 'OTHER_OUTPATIENT_FACILITY',
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineHomePossible: 'NO',
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1612220400000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    prohibitionToWork: 'YES',
    prohibitionToWorkFrom: 1611097200000,
    prohibitionToWorkUntil: 1611356400000,
    reportingDistrict: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1612191808913,
    changeDate: 1612954339705,
    uuid: 'QIRS4Z-HW2BFA-6R6SVB-UY2K2LBY',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'X33ZTV-7BSXQN-NYDIYH-VO3TCHWY',
      caption: 'Alina LAURA',
      firstName: 'Alina',
      lastName: 'Laura',
    },
    epidNumber: 'DEF-REG-DIS-21-006',
    reportDate: 1612134000000,
    reportingUser: {
      uuid: 'XB45HE-DFRW7X-ITDKMQ-BDRHKDSQ',
      caption: 'ad MIN - Administrator',
      firstName: 'ad',
      lastName: 'min',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    healthFacilityDetails: '',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1612191808927,
      changeDate: 1612954339707,
      uuid: 'QS65NG-GXGEDH-5ODGUK-JWVVKLSM',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1612191808946,
      changeDate: 1612191808946,
      uuid: 'VCDTRC-T5BRID-WYI4ZW-LE5GKI3E',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1612191808923,
      changeDate: 1612954339708,
      uuid: 'TI7DGP-ZNBGR6-WLYAT6-KT3GSMYI',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1612191808949,
      changeDate: 1612191808949,
      uuid: 'XHIILH-7ALKTS-NNTH6N-FSELCP4A',
    },
    clinicalCourse: {
      creationDate: 1612191808921,
      changeDate: 1612191808921,
      uuid: 'VUPA22-FOUIFA-4QUGMY-R7XNKMDI',
      healthConditions: {
        creationDate: 1612191808920,
        changeDate: 1612191808920,
        uuid: 'XONLXK-LV4SOJ-XPOKIN-TD7VSHUE',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1612191808930,
      changeDate: 1612191808930,
      uuid: 'SBT7UI-R7TOZ5-X3UQKH-C3RYSEVU',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1612191808934,
      changeDate: 1612191808934,
      uuid: 'WKJA7W-TP2NNI-A7IIWY-5N4KCO6E',
    },
    caseOrigin: 'IN_COUNTRY',
    externalID: 's2s_active_2',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    postpartum: 'YES',
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1613343600000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1612191754835,
    changeDate: 1612191772297,
    uuid: 'QUQTTU-ZIOAD2-Z4EIEG-H5SLKE3I',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'RYPQYB-NRDHP6-V77PYA-56VR2ADQ',
      caption: 'George BUCUR',
      firstName: 'George',
      lastName: 'Bucur',
    },
    epidNumber: 'DEF-REG-DIS-21-005',
    reportDate: 1612134000000,
    reportingUser: {
      uuid: 'XB45HE-DFRW7X-ITDKMQ-BDRHKDSQ',
      caption: 'ad MIN - Administrator',
      firstName: 'ad',
      lastName: 'min',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    healthFacilityDetails: '',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1612191754873,
      changeDate: 1612191772298,
      uuid: 'SZZ4SH-KYJYVA-YB4SYM-XY6HCLI4',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1612191754904,
      changeDate: 1612191754905,
      uuid: 'UEBRKS-S7MVS3-IKWLDO-XC32KFKA',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1612191754864,
      changeDate: 1612191772299,
      uuid: 'R3EUYB-K2OIEX-Z3XDWA-A7S2KODQ',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1612191754908,
      changeDate: 1612191754908,
      uuid: 'VEZMKH-54QPAO-QBKTAQ-HY7UCF7M',
    },
    clinicalCourse: {
      creationDate: 1612191754860,
      changeDate: 1612191754860,
      uuid: 'U5TGEP-YB7U3P-6L2XLN-34QQ2IPU',
      healthConditions: {
        creationDate: 1612191754860,
        changeDate: 1612191754860,
        uuid: 'SE36RA-TKWSYD-CBGJ4N-YNJ3KJK4',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1612191754876,
      changeDate: 1612191754876,
      uuid: 'QF3M6B-R2KM3S-OFBO2K-KRHV2MDQ',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1612191754892,
      changeDate: 1612191754892,
      uuid: 'UHDMOQ-LNRKA3-4NQHCT-E6XBCIS4',
    },
    caseOrigin: 'IN_COUNTRY',
    externalID: 's2s_active_1',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1613343600000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1610546172316,
    changeDate: 1611640574767,
    uuid: 'QGTLE7-4PFGJG-RJUZ2F-5AUZSIPQ',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'W52E3P-JIAPYM-3MQG3F-YX3ECAN4',
      caption: 'Share 3817',
      firstName: 'Share',
      lastName: '3817',
    },
    epidNumber: 'DEF-REG-DIS-21-001',
    reportDate: 1609455600000,
    reportingUser: {
      uuid: 'TIF63T-JVFKOF-DEXESZ-QXHDCO3I',
      caption: 'Sormas to Sormas CLIENT - Sormas zu Sormas Client',
      firstName: 'Sormas to Sormas',
      lastName: 'Client',
    },
    caseClassification: 'CONFIRMED',
    classificationUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    classificationDate: 1611640574262,
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    healthFacilityDetails: '',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1610546172336,
      changeDate: 1611640574608,
      uuid: 'QFVL6E-3VORDB-CRN3V2-XVIFSOWY',
      admittedToHealthFacility: 'YES',
      isolated: 'UNKNOWN',
      leftAgainstAdvice: 'UNKNOWN',
      hospitalizedPreviously: 'UNKNOWN',
      previousHospitalizations: [],
      intensiveCareUnit: 'UNKNOWN',
    },
    symptoms: {
      creationDate: 1610546172348,
      changeDate: 1610546889311,
      uuid: 'S2IP4Z-JJ73YL-PU6SJF-RNOKSB4Q',
      pseudonymized: false,
      chillsSweats: 'YES',
      fever: 'YES',
      symptomatic: true,
      feelingIll: 'YES',
    },
    epiData: {
      creationDate: 1610546172334,
      changeDate: 1611640574609,
      uuid: 'UZEVAO-PWOGDV-3IBHM4-UIPM2IUA',
      pseudonymized: false,
      exposureDetailsKnown: 'YES',
      contactWithSourceCaseKnown: 'NO',
      highTransmissionRiskArea: 'NO',
      largeOutbreaksArea: 'NO',
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1610546172351,
      changeDate: 1610546172351,
      uuid: 'XUFZPT-LPXSQU-2YWRT2-NEPOSM6I',
    },
    clinicalCourse: {
      creationDate: 1610546172331,
      changeDate: 1610546172331,
      uuid: 'SGXKBD-EVB3UT-A6DK3I-LE4RCJ6Y',
      healthConditions: {
        creationDate: 1610546172331,
        changeDate: 1610546172331,
        uuid: 'RUG6Q3-W4V267-PCFD4J-JIWVSETQ',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1610546172340,
      changeDate: 1610546172341,
      uuid: 'XELSMM-BW2KMY-DI37CI-I4DFKEXE',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1610546172343,
      changeDate: 1610546172343,
      uuid: 'XEBJK4-Q53OKW-2G7VIR-JHD32HEQ',
    },
    caseOrigin: 'IN_COUNTRY',
    additionalDetails: 'test data modified',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1610665200000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    prohibitionToWork: 'UNKNOWN',
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1611233140379,
    changeDate: 1611233141600,
    uuid: 'T2RQRX-PQ22VL-3IIUIO-DBCSKKVQ',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'S3KNGY-4H6NWC-VK4DGQ-PTZU2AIA',
      caption: 'ALDIN MOTIKA',
      firstName: 'ALDIN',
      lastName: 'MOTIKA',
    },
    epidNumber: 'DEF-REG-DIS-21-004',
    reportDate: 1611010800000,
    reportingUser: {
      uuid: 'TIF63T-JVFKOF-DEXESZ-QXHDCO3I',
      caption: 'Sormas to Sormas CLIENT - Sormas zu Sormas Client',
      firstName: 'Sormas to Sormas',
      lastName: 'Client',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1611041730721,
      changeDate: 1611233140416,
      uuid: 'WK3ZVZ-X3YD6J-O2LWIJ-NVIKKC2A',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1611041730731,
      changeDate: 1611233140428,
      uuid: 'V5H567-TZZL3X-Q7I2D6-LMWNKI2A',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1611041730719,
      changeDate: 1611233140414,
      uuid: 'RYXI5J-2YXOVB-VB3NIQ-U7VUSB6Q',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1611041730747,
      changeDate: 1611041730747,
      uuid: 'WFLTT6-HZ32MY-N6APO2-NQRI2LN4',
    },
    clinicalCourse: {
      creationDate: 1611041730717,
      changeDate: 1611233140412,
      uuid: 'TFVVUJ-GMBNR5-EGNEE2-QXMACDS4',
      healthConditions: {
        creationDate: 1611041730715,
        changeDate: 1611233140411,
        uuid: 'TFGFHH-BDY65V-KVD3VN-FNZKKNIU',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1611041730723,
      changeDate: 1611233140418,
      uuid: 'T2G4DA-W26LFV-XN5FSD-TGUXSEME',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1611041730726,
      changeDate: 1611233140420,
      uuid: 'Q6JN6I-77LZUE-3LZQES-X5N22LRU',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1612220400000,
    overwriteFollowUpUntil: false,
    sormasToSormasOriginInfo: {
      creationDate: 1611233140423,
      changeDate: 1611233140423,
      uuid: 'W4WSTU-MW2QWM-3JC74B-2BTMSLKA',
      organizationId: '2.03.1.01',
      senderName: 'National User',
      ownershipHandedOver: true,
      comment: 'Viel  Spaß damit',
    },
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1605877800099,
    changeDate: 1609936597793,
    uuid: 'TECKHD-WPX7WB-IH5DWW-J73OSD5A',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'RS4EAG-WZDLPA-3DYT3P-GH5ICGMA',
      caption: 'Peter LUSTIG',
      firstName: 'Peter',
      lastName: 'Lustig',
    },
    epidNumber: 'DEF-REG-DIS-20-003',
    reportDate: 1605826800000,
    reportingUser: {
      uuid: 'TIF63T-JVFKOF-DEXESZ-QXHDCO3I',
      caption: 'Sormas to Sormas CLIENT - Sormas zu Sormas Client',
      firstName: 'Sormas to Sormas',
      lastName: 'Client',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1605877772845,
      changeDate: 1605877800117,
      uuid: 'TB5M77-444WWS-G2Y6H2-W7YHCCOE',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1605877772868,
      changeDate: 1605877800126,
      uuid: 'QWTQAD-YUC3IG-VDT2EY-PMWCCJFU',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1605877772839,
      changeDate: 1606144710603,
      uuid: 'XZRFWK-4YVNJV-E6X4YA-VE3RSL7Y',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1605877772874,
      changeDate: 1605877800129,
      uuid: 'UYUSJS-PSDLHM-6TSACK-POQLSCK4',
    },
    clinicalCourse: {
      creationDate: 1605877772829,
      changeDate: 1605877800112,
      uuid: 'QHH247-S3HIMZ-J66QG6-QSTOKLTM',
      healthConditions: {
        creationDate: 1605877772829,
        changeDate: 1605877800112,
        uuid: 'T6Y5LP-QPZYXH-VT3K3O-NGKDKCQI',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1605877772855,
      changeDate: 1605877800119,
      uuid: 'XUTO2P-6KKON5-5T4OT6-LPJXSEEU',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1605877772860,
      changeDate: 1605877800120,
      uuid: 'QIBL3D-ZTBK2A-ULFBU3-FK5YKLTM',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1607036400000,
    overwriteFollowUpUntil: false,
    sormasToSormasOriginInfo: {
      creationDate: 1605877800123,
      changeDate: 1605877800123,
      uuid: 'XHIVPK-36VEVO-GIPGIF-PMHOCK3E',
      organizationId: '2.03.1.01',
      senderName: 'National User',
      ownershipHandedOver: false,
    },
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1606412278395,
    changeDate: 1608303073562,
    uuid: 'WQRXQF-RTHICW-3V6VNM-5FESSAGU',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'QM7ZWB-DRIIFO-44MTZW-YMM2SFI4',
      caption: 'AB_1_3388 1_3388',
      firstName: 'AB_1_3388',
      lastName: '1_3388',
    },
    epidNumber: 'DEF-REG-DIS-20-004',
    reportDate: 1606258800000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'CONFIRMED',
    classificationUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    classificationDate: 1606412350675,
    epidemiologicalConfirmation: 'NO',
    laboratoryDiagnosticConfirmation: 'NO',
    investigationStatus: 'PENDING',
    outcome: 'RECOVERED',
    outcomeDate: 1606345200000,
    sequelae: 'NO',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    healthFacilityDetails: 'Test Home FAcility',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1606412278411,
      changeDate: 1608019484505,
      uuid: 'WLB2NS-LNIACS-JPZZ6N-S2TXSLXQ',
      admittedToHealthFacility: 'YES',
      admissionDate: 1606413257633,
      dischargeDate: 1606345200000,
      isolated: 'NO',
      leftAgainstAdvice: 'NO',
      hospitalizedPreviously: 'NO',
      previousHospitalizations: [],
      intensiveCareUnit: 'NO',
    },
    symptoms: {
      creationDate: 1606412278423,
      changeDate: 1606459892180,
      uuid: 'XTPMKL-BTOHDU-3JTHX4-IIB5KKAM',
      pseudonymized: false,
      chillsSweats: 'UNKNOWN',
      cough: 'UNKNOWN',
      diarrhea: 'UNKNOWN',
      difficultyBreathing: 'UNKNOWN',
      fever: 'UNKNOWN',
      headache: 'UNKNOWN',
      musclePain: 'UNKNOWN',
      nausea: 'UNKNOWN',
      otherNonHemorrhagicSymptoms: 'UNKNOWN',
      rapidBreathing: 'UNKNOWN',
      runnyNose: 'UNKNOWN',
      soreThroat: 'UNKNOWN',
      symptomatic: false,
      temperature: 35,
      temperatureSource: 'AXILLARY',
      acuteRespiratoryDistressSyndrome: 'UNKNOWN',
      pneumoniaClinicalOrRadiologic: 'UNKNOWN',
      lossOfTaste: 'UNKNOWN',
      lossOfSmell: 'UNKNOWN',
      respiratoryDiseaseVentilation: 'UNKNOWN',
      feelingIll: 'UNKNOWN',
      fastHeartRate: 'UNKNOWN',
      oxygenSaturationLower94: 'UNKNOWN',
      shivering: 'UNKNOWN',
    },
    epiData: {
      creationDate: 1606412278409,
      changeDate: 1608019484506,
      uuid: 'RSTTKS-57SNBL-XRPE2X-SRIMCC7E',
      pseudonymized: false,
      exposureDetailsKnown: 'YES',
      contactWithSourceCaseKnown: 'NO',
      highTransmissionRiskArea: 'NO',
      largeOutbreaksArea: 'NO',
      exposures: [
        {
          creationDate: 1606412545604,
          changeDate: 1606459892178,
          uuid: 'V2GSVU-4B6YLC-GBULLY-K7DYSCGQ',
          pseudonymized: false,
          reportingUser: {
            uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
            caption: 'National USER - Nationale*r Benutzer*in',
            firstName: 'National',
            lastName: 'User',
          },
          startDate: 1606258800000,
          endDate: 1606345200000,
          exposureType: 'WORK',
          location: {
            creationDate: 1606412545605,
            changeDate: 1606412545605,
            uuid: 'TDCTUT-R4G3GC-TJMMKU-SGLKSG2E',
            pseudonymized: false,
          },
          typeOfPlace: 'FACILITY',
          indoors: 'UNKNOWN',
          outdoors: 'UNKNOWN',
          wearingMask: 'UNKNOWN',
          wearingPpe: 'UNKNOWN',
          otherProtectiveMeasures: 'NO',
          shortDistance: 'NO',
          longFaceToFaceContact: 'NO',
          animalMarket: 'NO',
          riskArea: 'UNKNOWN',
        },
      ],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1606412278430,
      changeDate: 1606412278430,
      uuid: 'XMM7IM-JVCR2D-WYR4MK-AWHISNIM',
    },
    clinicalCourse: {
      creationDate: 1606412278407,
      changeDate: 1606412278407,
      uuid: 'UTMRJH-AWOKFJ-2JTSIQ-TTGXCMUQ',
      healthConditions: {
        creationDate: 1606412278406,
        changeDate: 1606412278406,
        uuid: 'S2YHQL-GZMBDU-EP7GJH-PZ23CG7I',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1606412278414,
      changeDate: 1606412278414,
      uuid: 'T6KGLZ-NUXLVH-ZPR6TK-WFZVKMMY',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1606412278416,
      changeDate: 1606412278416,
      uuid: 'VWGILA-O2Y2JB-D4KYNN-JELW2JT4',
    },
    caseOrigin: 'IN_COUNTRY',
    externalID: '12345',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'UNKNOWN',
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineHomePossible: 'NO',
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1607468400000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1608191077577,
    changeDate: 1608191757302,
    uuid: 'SGLJY4-ZTDZSU-H2OY4W-LT66CMBY',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'RLJG7H-SCS6YY-7IYAHL-UPP2SPBU',
      caption: 'AB_17_12 LN_17_12',
      firstName: 'AB_17_12',
      lastName: 'LN_17_12',
    },
    epidNumber: 'DEF-REG-DIS-20-010',
    reportDate: 1608159600000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'CONFIRMED',
    classificationDate: 1608191230682,
    clinicalConfirmation: 'YES',
    epidemiologicalConfirmation: 'YES',
    laboratoryDiagnosticConfirmation: 'YES',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    healthFacilityDetails: 'Test_17_12',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1608191077587,
      changeDate: 1608191756763,
      uuid: 'WPXWD5-G4NR7K-D37Z67-XJIR2DPU',
      admittedToHealthFacility: 'YES',
      admissionDate: 1608191230464,
      leftAgainstAdvice: 'NO',
      hospitalizedPreviously: 'YES',
      previousHospitalizations: [
        {
          creationDate: 1608191597176,
          changeDate: 1608191756634,
          uuid: 'RSB4QM-KKA6BK-JFF5GP-EVBA2N4I',
          pseudonymized: false,
          admissionDate: 1607900400000,
          dischargeDate: 1608159600000,
          region: {
            uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
            caption: 'Voreingestellte Bundesländer',
            externalId: null,
          },
          district: {
            uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
            caption: 'Voreingestellter Landkreis',
            externalId: null,
          },
          community: {
            uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
            caption: 'Voreingestellte Gemeinde',
            externalId: null,
          },
          healthFacility: {
            uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
            caption: 'Standard Einrichtung',
            externalId: null,
          },
          healthFacilityDetails: '',
          isolated: 'NO',
        },
      ],
      intensiveCareUnit: 'YES',
      intensiveCareUnitStart: 1608159600000,
      intensiveCareUnitEnd: 1608159600000,
    },
    symptoms: {
      creationDate: 1608191077596,
      changeDate: 1608191756766,
      uuid: 'SHH2GC-ST4REG-X3USGF-6KU72MIQ',
      pseudonymized: false,
      chillsSweats: 'NO',
      cough: 'NO',
      diarrhea: 'NO',
      difficultyBreathing: 'NO',
      fever: 'NO',
      headache: 'NO',
      musclePain: 'NO',
      nausea: 'NO',
      otherNonHemorrhagicSymptoms: 'NO',
      rapidBreathing: 'NO',
      runnyNose: 'NO',
      soreThroat: 'NO',
      symptomatic: false,
      temperature: 35,
      temperatureSource: 'ORAL',
      acuteRespiratoryDistressSyndrome: 'NO',
      pneumoniaClinicalOrRadiologic: 'NO',
      lossOfTaste: 'NO',
      lossOfSmell: 'NO',
      respiratoryDiseaseVentilation: 'NO',
      feelingIll: 'NO',
      fastHeartRate: 'NO',
      oxygenSaturationLower94: 'NO',
      shivering: 'NO',
    },
    epiData: {
      creationDate: 1608191077585,
      changeDate: 1608191756764,
      uuid: 'X2UCBH-EHZ3C4-HO5VX3-5DS5CFDE',
      pseudonymized: false,
      exposureDetailsKnown: 'YES',
      highTransmissionRiskArea: 'YES',
      largeOutbreaksArea: 'YES',
      exposures: [
        {
          creationDate: 1608191671574,
          changeDate: 1608191756692,
          uuid: 'TCPER5-NQ3LHQ-PONZX5-NYGE2FQE',
          pseudonymized: false,
          startDate: 1608073200000,
          endDate: 1608159600000,
          exposureType: 'WORK',
          location: {
            creationDate: 1608191671575,
            changeDate: 1608191756692,
            uuid: 'TFPHP3-6DD5BF-3XSWRP-VYA7CNH4',
            pseudonymized: false,
          },
          exposureRole: 'GUEST',
          typeOfPlace: 'FACILITY',
          indoors: 'YES',
          outdoors: 'NO',
          wearingMask: 'YES',
          wearingPpe: 'NO',
          otherProtectiveMeasures: 'YES',
          protectiveMeasuresDetails: '_17_12',
          shortDistance: 'NO',
          longFaceToFaceContact: 'YES',
          animalMarket: 'NO',
          percutaneous: 'YES',
          contactToBodyFluids: 'NO',
          handlingSamples: 'YES',
          riskArea: 'NO',
        },
      ],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1608191077603,
      changeDate: 1608191077603,
      uuid: 'RKHW72-XWWOTR-MCBB3Z-5H3EKPWE',
    },
    clinicalCourse: {
      creationDate: 1608191077584,
      changeDate: 1608191077584,
      uuid: 'QEKPAP-FDR4WF-VJT7ZX-OUTVKOZM',
      healthConditions: {
        creationDate: 1608191077584,
        changeDate: 1608191077584,
        uuid: 'SGDBIK-CFF7YG-KCAGIZ-TEUMCBTE',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1608191077589,
      changeDate: 1608191077589,
      uuid: 'XFO7X7-VNEWQE-UFOZS7-JXQW2MFU',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1608191077591,
      changeDate: 1608191077591,
      uuid: 'XVRCL2-ANTSUK-GA2AR5-ZT4NKOAM',
    },
    caseOrigin: 'IN_COUNTRY',
    externalID: '_17_12_2',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'HOME',
    quarantineFrom: 1607986800000,
    quarantineTo: 1608159600000,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineHomePossible: 'NO',
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1609369200000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    prohibitionToWork: 'YES',
    prohibitionToWorkFrom: 1607986800000,
    prohibitionToWorkUntil: 1608159600000,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1607947962853,
    changeDate: 1607951521534,
    uuid: 'U4N3L6-MWHNVO-F73GE7-CTOCKAUM',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'RLSI45-PN7ELJ-GTS324-ZTX6CN2U',
      caption: 'Maria IONESCU',
      firstName: 'Maria',
      lastName: 'Ionescu',
    },
    epidNumber: 'DEF-REG-DIS-20-008',
    reportDate: 1607641200000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'NOT_CLASSIFIED',
    epidemiologicalConfirmation: 'YES',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    healthFacilityDetails: '',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1607947962879,
      changeDate: 1607951521535,
      uuid: 'WV6O3B-RBARJ4-UL22YE-22Y4KK5Q',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1607947962917,
      changeDate: 1607947962917,
      uuid: 'WSYXJN-HX6PI4-DBCTEX-AQOJCP5I',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1607947962878,
      changeDate: 1607951521536,
      uuid: 'TTAKYS-REFVNH-WOF645-SYJESPSQ',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1607947962926,
      changeDate: 1607947962926,
      uuid: 'V7PVDG-ADEBAM-4Y3JSC-5YNFCMAY',
    },
    clinicalCourse: {
      creationDate: 1607947962876,
      changeDate: 1607947962876,
      uuid: 'VSAROA-4RARBE-VYSICC-6VYKKH5A',
      healthConditions: {
        creationDate: 1607947962876,
        changeDate: 1607947962876,
        uuid: 'RZKSIC-JRB3D4-FCU5FX-SCASCDCM',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1607947962880,
      changeDate: 1607947962880,
      uuid: 'VYMDDY-H3INYX-W22Z7I-EY3N2MDI',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1607947962883,
      changeDate: 1607947962883,
      uuid: 'VWSAUZ-6GNWH2-DDEIQA-BVH52HVQ',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1608850800000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1607951079321,
    changeDate: 1607951138719,
    uuid: 'QROBQR-O4I4F3-3OS2PW-OPIHKFPY',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'QBLNER-EEJU3V-MDRJDL-DYID2CZY',
      caption: 'Marioara VASILESCU',
      firstName: 'Marioara',
      lastName: 'Vasilescu',
    },
    epidNumber: 'DEF-REG-DIS-20-009',
    reportDate: 1607554800000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    facilityType: 'HOSPITAL',
    healthFacility: {
      uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
      caption: 'Standard Einrichtung',
      externalId: null,
    },
    healthFacilityDetails: '',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1607951079329,
      changeDate: 1607951079329,
      uuid: 'R4DM2W-5VCIRG-44C7PM-MJFWKIMM',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1607951079335,
      changeDate: 1607951079335,
      uuid: 'WEYGTB-6KML52-OXZCBN-7H6ECBO4',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1607951079328,
      changeDate: 1607951079328,
      uuid: 'R7EI2R-A2VWVD-XPTPEL-MRKMSAIY',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1607951079336,
      changeDate: 1607951079336,
      uuid: 'SFOV2R-WGHNPB-YJT3GD-IMBJKP5A',
    },
    clinicalCourse: {
      creationDate: 1607951079326,
      changeDate: 1607951079326,
      uuid: 'QZH5WG-5WA5KU-NACVSV-2O322IRM',
      healthConditions: {
        creationDate: 1607951079326,
        changeDate: 1607951079326,
        uuid: 'USOIVT-YWQHYM-6IAKZY-FS3ZKLZU',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1607951079331,
      changeDate: 1607951079331,
      uuid: 'UJ4SJ6-G244P5-DXUGVW-3SDAKLUE',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1607951079332,
      changeDate: 1607951079332,
      uuid: 'QUXJUR-OUCC2T-QEAVCS-WWY4SCHQ',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1608764400000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1607616180058,
    changeDate: 1607616426930,
    uuid: 'RT4DHB-2V746Y-FMBAMM-3SN2SBGE',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'VZ5PF6-KU25MI-B5YGLO-2BKF2GMA',
      caption: 'AB_3608_2_1 LN_3608_2_1',
      firstName: 'AB_3608_2_1',
      lastName: 'LN_3608_2_1',
    },
    epidNumber: 'DEF-REG-DIS-20-007',
    reportDate: 1607554800000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    healthFacilityDetails: '3608_2_1',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1607616180068,
      changeDate: 1607616180068,
      uuid: 'QYOY2Y-KJVBC5-6XLBPZ-FMRVSNEE',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1607616180072,
      changeDate: 1607616180073,
      uuid: 'W5QTXL-ANAQ42-ZND4TR-DJYNSEGY',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1607616180067,
      changeDate: 1607616180067,
      uuid: 'QCCHTU-3WMTMG-OOMWDG-35W3SNUU',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1607616180074,
      changeDate: 1607616180074,
      uuid: 'WBZQHR-ZXZIQE-WK63A7-VM3B2J3A',
    },
    clinicalCourse: {
      creationDate: 1607616180066,
      changeDate: 1607616180066,
      uuid: 'UOHIRY-I2XANJ-342AU5-53W3CLIQ',
      healthConditions: {
        creationDate: 1607616180066,
        changeDate: 1607616180066,
        uuid: 'U2IV7P-Q4IWZY-R2PUP6-BFJYCPSU',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1607616180069,
      changeDate: 1607616180069,
      uuid: 'VG4UFF-P6PZ4O-QMLY3B-XQUXSF74',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1607616180071,
      changeDate: 1607616180071,
      uuid: 'WXF4UR-UVXW2F-ID6IJM-EALGCJEU',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1608764400000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: true,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1607517488687,
    changeDate: 1607615674981,
    uuid: 'XZLAWN-WZUFNY-EYTQNM-E25S2DLU',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'UNZ66I-UZD4FF-2CVH3G-RTWMCPSI',
      caption: 'AB_3608 AB_LN_3608',
      firstName: 'AB_3608',
      lastName: 'AB_LN_3608',
    },
    epidNumber: 'DEF-REG-DIS-20-006',
    reportDate: 1607468400000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'SUSPECT',
    classificationUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    classificationDate: 1607517547401,
    clinicalConfirmation: 'NO',
    epidemiologicalConfirmation: 'NO',
    laboratoryDiagnosticConfirmation: 'NO',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    healthFacilityDetails: 'Home 3608',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1607517488697,
      changeDate: 1607517851101,
      uuid: 'UC6NDE-CUXIWR-ERD5AD-GYBIKD5E',
      hospitalizedPreviously: 'YES',
      previousHospitalizations: [
        {
          creationDate: 1607517697806,
          changeDate: 1607517697806,
          uuid: 'XB3FAA-NLI2BI-DT6VN6-YPXK2G7U',
          pseudonymized: false,
          admissionDate: 1607036400000,
          dischargeDate: 1607382000000,
          region: {
            uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
            caption: 'Voreingestellte Bundesländer',
            externalId: null,
          },
          district: {
            uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
            caption: 'Voreingestellter Landkreis',
            externalId: null,
          },
          community: {
            uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
            caption: 'Voreingestellte Gemeinde',
            externalId: null,
          },
          healthFacility: {
            uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
            caption: 'Standard Einrichtung',
            externalId: null,
          },
          healthFacilityDetails: '',
          isolated: 'NO',
          description: 'Test Hospitalization for 3608',
        },
      ],
    },
    symptoms: {
      creationDate: 1607517488705,
      changeDate: 1607517715291,
      uuid: 'QGTGMP-YCKEK7-2MJJSY-NIE22P3M',
      pseudonymized: false,
      chillsSweats: 'NO',
      cough: 'NO',
      diarrhea: 'NO',
      difficultyBreathing: 'NO',
      fever: 'NO',
      headache: 'NO',
      musclePain: 'NO',
      nausea: 'NO',
      otherNonHemorrhagicSymptoms: 'NO',
      rapidBreathing: 'NO',
      runnyNose: 'NO',
      soreThroat: 'NO',
      symptomatic: false,
      temperature: 35.1,
      temperatureSource: 'AXILLARY',
      acuteRespiratoryDistressSyndrome: 'NO',
      pneumoniaClinicalOrRadiologic: 'NO',
      lossOfTaste: 'NO',
      lossOfSmell: 'NO',
      respiratoryDiseaseVentilation: 'NO',
      feelingIll: 'NO',
      fastHeartRate: 'NO',
      oxygenSaturationLower94: 'NO',
      shivering: 'NO',
    },
    epiData: {
      creationDate: 1607517488696,
      changeDate: 1607517851103,
      uuid: 'XOOT2D-SPKLGZ-UNEAMR-A2ZYKIPU',
      pseudonymized: false,
      exposureDetailsKnown: 'YES',
      contactWithSourceCaseKnown: 'YES',
      highTransmissionRiskArea: 'YES',
      largeOutbreaksArea: 'YES',
      exposures: [
        {
          creationDate: 1607517798282,
          changeDate: 1607517798283,
          uuid: 'RR3TMT-25QVZY-EAAAUR-YKL7CK3Q',
          pseudonymized: false,
          reportingUser: {
            uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
            caption: 'National USER - Nationale*r Benutzer*in',
            firstName: 'National',
            lastName: 'User',
          },
          startDate: 1607036400000,
          endDate: 1607295600000,
          description: 'test 3608 1 epidata',
          exposureType: 'WORK',
          location: {
            creationDate: 1607517798283,
            changeDate: 1607517798283,
            uuid: 'XEYAI2-54KOFG-4AHE2R-2TITCD6E',
            pseudonymized: false,
            region: {
              uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
              caption: 'Voreingestellte Bundesländer',
              externalId: null,
            },
            district: {
              uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
              caption: 'Voreingestellter Landkreis',
              externalId: null,
            },
            facilityType: 'CAMPSITE',
            facility: {
              uuid: 'SORMAS-CONSTID-OTHERS-FACILITY',
              caption: 'Andere Einrichtung',
              externalId: null,
            },
            facilityDetails: 'epi data facility name 1 for 3608',
          },
          typeOfPlace: 'FACILITY',
          indoors: 'NO',
          outdoors: 'NO',
          wearingMask: 'NO',
          wearingPpe: 'NO',
          otherProtectiveMeasures: 'NO',
          shortDistance: 'NO',
          longFaceToFaceContact: 'NO',
          animalMarket: 'NO',
          percutaneous: 'NO',
          contactToBodyFluids: 'NO',
          handlingSamples: 'NO',
          riskArea: 'NO',
        },
      ],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1607517488736,
      changeDate: 1607517488736,
      uuid: 'R2JZXN-X5KTZJ-464II6-XID5CMRE',
    },
    clinicalCourse: {
      creationDate: 1607517488695,
      changeDate: 1607517488695,
      uuid: 'RBMWRR-HDXQT2-X36SX3-TQDGKE7Q',
      healthConditions: {
        creationDate: 1607517488695,
        changeDate: 1607517488695,
        uuid: 'XGZQF4-6YKUBG-A2BQXQ-QA7JCK2I',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1607517488699,
      changeDate: 1607517488699,
      uuid: 'VHBPAZ-OYEG6M-WBLIIT-RRPP2HYY',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1607517488700,
      changeDate: 1607517488700,
      uuid: 'RI6MVJ-I6FXKF-FKX3MH-OFZCSDYY',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'NONE',
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineHomePossible: 'NO',
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1608678000000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: true,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1606464985435,
    changeDate: 1606468301074,
    uuid: 'SCYY5L-AYUH54-64RMMV-QLXP2D6Y',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'VQ6MA4-33XQPT-DCO4WP-3CAYKLUQ',
      caption: 'AB_2 2_3388',
      firstName: 'AB_2',
      lastName: '2_3388',
    },
    epidNumber: 'DEF-REG-DIS-20-005',
    reportDate: 1606431600000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'SUSPECT',
    classificationUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    classificationDate: 1606465111594,
    clinicalConfirmation: 'YES',
    epidemiologicalConfirmation: 'YES',
    laboratoryDiagnosticConfirmation: 'YES',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    healthFacilityDetails: 'AB_2_home FAcility',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1606464985449,
      changeDate: 1606465652852,
      uuid: 'RG4IRT-7KEYEH-SBT6N2-SWUJ2JWU',
      hospitalizedPreviously: 'YES',
      previousHospitalizations: [
        {
          creationDate: 1606465318863,
          changeDate: 1606465318863,
          uuid: 'WKBVY7-JMGA4S-QLL7EK-5P2B2FVY',
          pseudonymized: false,
          admissionDate: 1606345200000,
          dischargeDate: 1606431600000,
          region: {
            uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
            caption: 'Voreingestellte Bundesländer',
            externalId: null,
          },
          district: {
            uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
            caption: 'Voreingestellter Landkreis',
            externalId: null,
          },
          community: {
            uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
            caption: 'Voreingestellte Gemeinde',
            externalId: null,
          },
          healthFacility: {
            uuid: 'QHGNWH-MI44EQ-GTOULS-3SXWSHZM',
            caption: 'Standard Einrichtung',
            externalId: null,
          },
          healthFacilityDetails: '',
          isolated: 'YES',
          description: '3388',
        },
      ],
    },
    symptoms: {
      creationDate: 1606464985453,
      changeDate: 1606465352857,
      uuid: 'QFX6MW-4J4P7B-YPHYU7-S6XKCFBM',
      pseudonymized: false,
      chillsSweats: 'NO',
      cough: 'NO',
      diarrhea: 'NO',
      difficultyBreathing: 'NO',
      fever: 'NO',
      headache: 'NO',
      musclePain: 'NO',
      nausea: 'NO',
      otherNonHemorrhagicSymptoms: 'NO',
      rapidBreathing: 'NO',
      runnyNose: 'NO',
      soreThroat: 'NO',
      symptomatic: false,
      symptomsComments: '3388',
      temperature: 35,
      temperatureSource: 'AXILLARY',
      acuteRespiratoryDistressSyndrome: 'NO',
      pneumoniaClinicalOrRadiologic: 'NO',
      lossOfTaste: 'NO',
      lossOfSmell: 'NO',
      respiratoryDiseaseVentilation: 'NO',
      feelingIll: 'NO',
      fastHeartRate: 'NO',
      oxygenSaturationLower94: 'NO',
      shivering: 'NO',
    },
    epiData: {
      creationDate: 1606464985446,
      changeDate: 1606465652853,
      uuid: 'TVL473-MY6RVB-4EDOJG-WU7Q2ISU',
      pseudonymized: false,
      exposureDetailsKnown: 'YES',
      contactWithSourceCaseKnown: 'NO',
      highTransmissionRiskArea: 'YES',
      largeOutbreaksArea: 'YES',
      exposures: [
        {
          creationDate: 1606465494916,
          changeDate: 1606465494917,
          uuid: 'UCA6N5-3LWBNC-LAMH3I-M6542PSI',
          pseudonymized: false,
          reportingUser: {
            uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
            caption: 'National USER - Nationale*r Benutzer*in',
            firstName: 'National',
            lastName: 'User',
          },
          startDate: 1606345200000,
          endDate: 1606431600000,
          description: '3388',
          exposureType: 'WORK',
          location: {
            creationDate: 1606465494917,
            changeDate: 1606465494917,
            uuid: 'UYTN3R-TQQ7LC-VLC4YO-5FM2SLJY',
            pseudonymized: false,
            region: {
              uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
              caption: 'Voreingestellte Bundesländer',
              externalId: null,
            },
            district: {
              uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
              caption: 'Voreingestellter Landkreis',
              externalId: null,
            },
            community: {
              uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
              caption: 'Voreingestellte Gemeinde',
              externalId: null,
            },
            details: '3388',
            city: '3388',
            areaType: 'URBAN',
            postalCode: '3388',
            street: '3388',
            houseNumber: '3388',
            additionalInformation: '3388',
            facilityType: 'CAMPSITE',
            facility: {
              uuid: 'SORMAS-CONSTID-OTHERS-FACILITY',
              caption: 'Andere Einrichtung',
              externalId: null,
            },
            facilityDetails: '3388',
          },
          typeOfPlace: 'FACILITY',
          indoors: 'YES',
          outdoors: 'YES',
          wearingMask: 'YES',
          wearingPpe: 'YES',
          otherProtectiveMeasures: 'YES',
          protectiveMeasuresDetails: '3388',
          shortDistance: 'YES',
          longFaceToFaceContact: 'YES',
          animalMarket: 'YES',
          percutaneous: 'YES',
          contactToBodyFluids: 'YES',
          handlingSamples: 'YES',
          riskArea: 'YES',
        },
      ],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1606464985455,
      changeDate: 1606464985455,
      uuid: 'UBJ5I7-VOXYEC-QYBM3U-DOLZ2G5I',
    },
    clinicalCourse: {
      creationDate: 1606464985444,
      changeDate: 1606464985444,
      uuid: 'R34WZ4-OHM4EY-LCXVI4-2GTWKB7M',
      healthConditions: {
        creationDate: 1606464985444,
        changeDate: 1606464985444,
        uuid: 'X4F3KC-N2YLJG-FRJNGS-34UVSPV4',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1606464985450,
      changeDate: 1606464985450,
      uuid: 'X42V2X-55SB77-LLECMB-LROR2OXM',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1606464985451,
      changeDate: 1606464985452,
      uuid: 'TMLVPD-I4NDEL-BTLJCA-SZOHKOSU',
    },
    caseOrigin: 'IN_COUNTRY',
    additionalDetails: 'test 27_morning for 3388',
    externalID: '3388_1',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantine: 'HOME',
    quarantineFrom: 1606345200000,
    quarantineTo: 1606431600000,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineHomePossible: 'NO',
    quarantineHomePossibleComment: 'no quarantine',
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1607641200000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: true,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1605872316513,
    changeDate: 1605872318046,
    uuid: 'XFQSRD-7A5W2P-6PWGCK-3K2D2DV4',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'TSQZGU-O26LVZ-WAWPNJ-R5PZKJRM',
      caption: 'Maximiliane MUSTERFRAU',
      firstName: 'Maximiliane',
      lastName: 'Musterfrau',
    },
    epidNumber: 'DEF-REG-DIS-20-002',
    reportDate: 1605826800000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1605872316547,
      changeDate: 1605872316547,
      uuid: 'QCQIGJ-AJBD56-UNUQDP-HJUWKDKU',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1605872316577,
      changeDate: 1605872316577,
      uuid: 'TWV3E4-O4BFA6-RM5QEY-WFNLKK4I',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1605872316542,
      changeDate: 1606144710603,
      uuid: 'VZRARL-LIK2EG-QNGGUP-GVXI2LJ4',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1605872316588,
      changeDate: 1605872316588,
      uuid: 'T7K7TT-YAZTQ2-PELLL5-U74ESBKE',
    },
    clinicalCourse: {
      creationDate: 1605872316535,
      changeDate: 1605872316535,
      uuid: 'U4D5U4-6LYPZ6-DFZUFT-LDLL2NNE',
      healthConditions: {
        creationDate: 1605872316535,
        changeDate: 1605872316535,
        uuid: 'VQPWDY-UJLJLZ-MI7YZL-4K27SH3E',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1605872316554,
      changeDate: 1605872316554,
      uuid: 'RTC2TN-J2P2OK-W4ELLF-LPST2GEE',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1605872316561,
      changeDate: 1605872316561,
      uuid: 'VHDHPD-TEF2VK-L7LNE7-T2AYCDGY',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1607036400000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: true,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
  {
    creationDate: 1605870655523,
    changeDate: 1605870856477,
    uuid: 'TWZBJF-77OVTQ-2IT3W3-AGTSCKKY',
    pseudonymized: false,
    disease: 'CORONAVIRUS',
    person: {
      uuid: 'WWS5FP-E6D3B4-WDVB6Z-C6ZKCMQI',
      caption: 'New CONTACT',
      firstName: 'New',
      lastName: 'Contact',
    },
    epidNumber: 'DEF-REG-DIS-20-001',
    reportDate: 1604185200000,
    reportingUser: {
      uuid: 'XLO5EP-X5AFHM-6X3TTM-W2DBCAL4',
      caption: 'National USER - Nationale*r Benutzer*in',
      firstName: 'National',
      lastName: 'User',
    },
    caseClassification: 'NOT_CLASSIFIED',
    investigationStatus: 'PENDING',
    outcome: 'NO_OUTCOME',
    region: {
      uuid: 'QWDSNP-XOPLSB-6IVQ3B-4OK4SOHE',
      caption: 'Voreingestellte Bundesländer',
      externalId: null,
    },
    district: {
      uuid: 'WADOX3-JTL3XV-G2NPGR-7DHECBFA',
      caption: 'Voreingestellter Landkreis',
      externalId: null,
    },
    community: {
      uuid: 'XSO7BI-GO7D6J-2PUAGS-XPOBKKQ4',
      caption: 'Voreingestellte Gemeinde',
      externalId: null,
    },
    healthFacility: {
      uuid: 'SORMAS-CONSTID-ISNONE-FACILITY',
      caption: 'Zuhause oder anderer Ort',
      externalId: null,
    },
    healthFacilityDetails: 'Home Facility',
    surveillanceOfficer: {
      uuid: 'UCT6ZL-4Z64BF-7NYMX7-T6GK2BO4',
      caption: 'Surveillance OFFICER - Überwachungsbeauftragte*r',
      firstName: 'Surveillance',
      lastName: 'Officer',
    },
    hospitalization: {
      creationDate: 1605870655540,
      changeDate: 1605870856478,
      uuid: 'RX64O3-DK3DFN-PLAIB6-KLHRCOUY',
      previousHospitalizations: [],
    },
    symptoms: {
      creationDate: 1605870655551,
      changeDate: 1605870655552,
      uuid: 'XGIYIL-YNE56H-ADZL2U-4JM3KEMI',
      pseudonymized: false,
      symptomatic: false,
    },
    epiData: {
      creationDate: 1605870655539,
      changeDate: 1606144710603,
      uuid: 'TKWYSH-NAMZ76-AAKIIP-WGXQ2ELU',
      pseudonymized: false,
      exposures: [],
      activitiesAsCase: [],
    },
    therapy: {
      creationDate: 1605870655556,
      changeDate: 1605870655556,
      uuid: 'QLE6TP-34AMVZ-GX4SON-HCUCKAWE',
    },
    clinicalCourse: {
      creationDate: 1605870655534,
      changeDate: 1605870655534,
      uuid: 'UQUEZR-UUJJXV-YZWV72-YZKDSFCI',
      healthConditions: {
        creationDate: 1605870655533,
        changeDate: 1605870655533,
        uuid: 'UOYDUT-33QD44-SQWGI4-R2XUSL5I',
        pseudonymized: false,
      },
    },
    maternalHistory: {
      creationDate: 1605870655543,
      changeDate: 1605870655543,
      uuid: 'TEPN4H-ZIO7FV-7GT6HH-IARMKJJM',
      pseudonymized: false,
    },
    portHealthInfo: {
      creationDate: 1605870655544,
      changeDate: 1605870655544,
      uuid: 'QPYLXC-GSYLAP-2EMPPS-A22UKJCA',
    },
    caseOrigin: 'IN_COUNTRY',
    sharedToCountry: false,
    nosocomialOutbreak: false,
    quarantineOrderedVerbally: false,
    quarantineOrderedOfficialDocument: false,
    quarantineExtended: false,
    quarantineReduced: false,
    quarantineOfficialOrderSent: false,
    followUpStatus: 'FOLLOW_UP',
    followUpUntil: 1605394800000,
    overwriteFollowUpUntil: false,
    ownershipHandedOver: false,
    notACaseReasonNegativeTest: false,
    notACaseReasonPhysicianInformation: false,
    notACaseReasonDifferentPathogen: false,
    notACaseReasonOther: false,
  },
];
