export const ACTIONS_CASE = {
  BASIC_EXPORT: 'CASE_EXPORT_BASIC',
  DETAILED_EXPORT: 'CASE_EXPORT_DETAILED',
  CASE_EXPORT: 'CASE_EXPORT',
  SAMPLE_EXPORT: 'CASE_EXPORT_SAMPLE',
  CUSTOM_EXPORT: 'CASE_EXPORT_CUSTOM',
  CASE_GUIDE: 'CASE_GUIDE',
  MERGE_DUPLICATES: 'CASE_MERGE_DUPLICATES',
  LINE_LISTING: 'CASE_LINE_LISTING',
  CASE_SPECIFIC_SEARCH: 'CASE_SPECIFIC_SEARCH',
  LINE_LISTING_IMPORT: 'LINE_LISTING_IMPORT',
  DETAILED_IMPORT: 'DETAILED_IMPORT',
};

export const ACTIONS_CASE_FOLLOW_UP = {
  BASIC_EXPORT: 'CASE_FOLLOW_UP_EXPORT_BASIC',
};

export const ACTIONS_FACILITY = {
  BASIC_EXPORT: 'FACILITY_EXPORT_BASIC',
  DETAILED_EXPORT: 'FACILITY_EXPORT_DETAILED',
};

export const ACTIONS_SAMPLE = {
  BASIC_EXPORT: 'SAMPLE_EXPORT_BASIC',
  DETAILED_EXPORT: 'SAMPLE_EXPORT_DETAILED',
};

export const ACTIONS_BULK_EDIT = {
  EDIT: 'EDIT',
  DELETE: 'DELETE',
  ARCHIVE: 'ARCHIVE',
  DEARCHIVE: 'DEARCHIVE',
  SHARE: 'SHARE',
  GROUP: 'GROUP',
  REPORTING_TOOL: 'SEND_TO_REPORTING_TOOL',
  QUARANTINE_DOCUMENTS: 'CREATE_QUARANTINE_ORDER_DOCUMENTS',
  ENABLE: 'ENABLE',
  DISABLE: 'DISABLE',
};

export const ACTIONS_EVENT = {
  BASIC_EXPORT: 'EVENT_EXPORT_BASIC',
  DETAILED_EXPORT: 'EVENT_EXPORT_DETAILED',
  EVENT_SPECIFIC_SEARCH: 'EVENT_SPECIFIC_SEARCH',
  IMPORT: 'IMPORT',
};

export const ACTIONS_EVENT_ACTION = {
  BASIC_EXPORT: 'EVENT_ACTION_EXPORT_BASIC',
  DETAILED_EXPORT: 'EVENT_ACTION_EXPORT_DETAILED',
};

export const ACTIONS_EVENT_GROUP = {
  BASIC_EXPORT: 'EVENT_GROUP_EXPORT_BASIC',
};

export const ACTIONS_EVENT_PARTICIPANT = {
  BASIC_EXPORT: 'EVENT_PARTICPANT_EXPORT_BASIC',
  DETAILED_EXPORT: 'EVENT_PARTICPANT_EXPORT_DETAILED',
  CUSTOM_EXPORT: 'EVENT_PARTICPANT_EXPORT_CUSTOM',
};

export const ACTIONS_EVENTS_VIEW_OPTIONS = {
  EVENTS: '/events/list',
  ACTIONS: '/actions/list',
  GROUPS: '/events/event-groups/list',
};

export const ACTIONS_VIEW_OPTIONS = {
  DEFAULT: 'DEFAULT',
  DETAILED: 'DETAILED',
  FOLLOW_UP: 'FOLLOW_UP',
};

export const ACTIONS_FILTERS_CASE_OPTIONS = {
  DISEASE: 'DISEASE',
  CLASSIFICATION: 'CLASSIFICATION',
  OUTCOME: 'OUTCOME',
  REPORTING_USER_ROLE: 'REPORTING_USER_ROLE',
};

export const ACTIONS_CASE_EDIT = {
  ARCHIVE: 'ARCHIVE',
  DELETE: 'DELETE',
};

export const ACTIONS_EVENT_EDIT = {
  ARCHIVE: 'ARCHIVE',
  DELETE: 'DELETE',
};

export const ACTIONS_CONTACT = {
  BASIC_EXPORT: 'CONTACT_EXPORT_BASIC',
  DETAILED_EXPORT: 'CONTACT_EXPORT_DETAILED',
  FOLLOW_UP_EXPORT: 'CONTACT_EXPORT_FOLLOW_UP',
  CUSTOM_EXPORT: 'CONTACT_EXPORT_CUSTOM',
  MERGE_DUPLICATES: 'CONTACT_MERGE_DUPLICATES',
  LINE_LISTING: 'CONTACT_LINE_LISTING',
};

export const ACTIONS_CONTACT_EDIT = {
  DELETE: 'DELETE',
};

export const ACTIONS_SAMPLE_EDIT = {
  DELETE: 'DELETE',
  REFER: 'REFER',
};

export const ACTIONS_ENTRY_EDIT = {
  DELETE: 'DELETE',
};

export const ACTIONS_DASHBOARD_VIEW_OPTIONS = {
  SURVEILLANCE: 'surveillance',
  CONTACTS: 'contacts',
};

export const ACTIONS_IMMUNIZATION_EDIT = {
  ARCHIVE: 'ARCHIVE',
  DELETE: 'DELETE',
};

export const ACTIONS_SAMPLES_VIEW_OPTIONS = {
  SAMPLES: '/samples/list',
  LAB_MESSAGES: '/lab-messages/list',
};

export const ACTIONS_LAB_MESSAGE = {
  ASSIGN: 'ASSIGN',
  PROCESS: 'PROCESS',
  DOWNLOAD: 'DOWNLOAD',
};

export const ACTIONS_TASK = {
  BASIC_EXPORT: 'TASK_EXPORT_BASIC',
  DETAILED_EXPORT: 'TASK_EXPORT_DETAILED',
  CUSTOM_EXPORT: 'TASK_EXPORT_CUSTOM',
};

export const ACTIONS_PERSONS = {
  BASIC_EXPORT: 'PERSON_EXPORT_BASIC',
  DETAILED_EXPORT: 'PERSON_EXPORT_DETAILED',
  CUSTOM_EXPORT: 'PERSON_EXPORT_CUSTOM',
};
