export const ACTIONS_CASE = {
  BASIC_EXPORT: 'CASE_EXPORT_BASIC',
  DETAILED_EXPORT: 'CASE_EXPORT_DETAILED',
  CASE_EXPORT: 'CASE_EXPORT',
  SAMPLE_EXPORT: 'CASE_EXPORT_SAMPLE',
  CUSTOM_EXPORT: 'CASE_EXPORT_CUSTOM',
  CASE_GUIDE: 'CASE_GUIDE',
  MERGE_DUPLICATES: 'CASE_MERGE_DUPLICATES',
  LINE_LISTING: 'CASE_LINE_LISTING',
};

export const ACTIONS_BULK_EDIT = {
  EDIT: 'EDIT',
  DELETE: 'DELETE',
  ARCHIVE: 'ARCHIVE',
  SHARE: 'SHARE',
  GROUP: 'GROUP',
  REPORTING_TOOL: 'SEND_TO_REPORTING_TOOL',
  QUARANTINE_DOCUMENTS: 'CREATE_QUARANTINE_ORDER_DOCUMENTS',
};

export const ACTIONS_CASE_VIEW_OPTIONS = {
  DEFAULT: 'DEFAULT',
  DETAILED: 'DETAILED',
  FOLLOW_UP: 'FOLLOW_UP',
};
