export const ACTIONS_CASE = {
  BASIC_EXPORT: 'CASE_EXPORT_BASIC',
  DETAILED_EXPORT: 'CASE_EXPORT_DETAILED',
  CASE_EXPORT: 'CASE_EXPORT',
  SAMPLE_EXPORT: 'CASE_EXPORT_SAMPLE',
  CUSTOM_EXPORT: 'CASE_EXPORT_CUSTOM',
  CASE_GUIDE: 'CASE_GUIDE',
  MERGE_DUPLICATES: 'CASE_MERGE_DUPLICATES',
  LINE_LISTING: 'CASE_LINE_LISTING',
};

export const ACTIONS_BULK_EDIT = {
  EDIT: 'EDIT',
  DELETE: 'DELETE',
  ARCHIVE: 'ARCHIVE',
  SHARE: 'SHARE',
  GROUP: 'GROUP',
  REPORTING_TOOL: 'SEND_TO_REPORTING_TOOL',
  QUARANTINE_DOCUMENTS: 'CREATE_QUARANTINE_ORDER_DOCUMENTS',
};

export const ACTIONS_EVENTS_VIEW_OPTIONS = {
  EVENTS: '/events/list',
  ACTIONS: '/events/event-actions/list',
  GROUPS: '/events/event-groups/list',
};

export const ACTIONS_CASE_VIEW_OPTIONS = {
  DEFAULT: 'DEFAULT',
  DETAILED: 'DETAILED',
  FOLLOW_UP: 'FOLLOW_UP',
};

export const ACTIONS_FILTERS_CASE_OPTIONS = {
  DISEASE: 'DISEASE',
  CLASSIFICATION: 'CLASSIFICATION',
  OUTCOME: 'OUTCOME',
  REPORTING_USER_ROLE: 'REPORTING_USER_ROLE',
};

export const ACTIONS_CASE_EDIT = {
  ARCHIVE: 'ARCHIVE',
  DELETE: 'DELETE',
};

export const ACTIONS_EVENT_EDIT = {
  ARCHIVE: 'ARCHIVE',
  DELETE: 'DELETE',
};

export const ACTIONS_CONTACT_EDIT = {
  DELETE: 'DELETE',
};

export const ACTIONS_SAMPLE_EDIT = {
  DELETE: 'DELETE',
  REFER: 'REFER',
};

export const ACTIONS_DASHBOARD_VIEW_OPTIONS = {
  SURVEILLANCE: 'surveillance',
  CONTACTS: 'contacts',
};
