/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActionContext } from './actionContext';
import { ActionPriority } from './actionPriority';
import { ActionStatus } from './actionStatus';
import { EventReferenceDto } from './eventReferenceDto';
import { ReferenceDto } from './referenceDto';
import { UserReferenceDto } from './userReferenceDto';

export interface ActionDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  actionContext: ActionContext;
  event?: EventReferenceDto;
  priority?: ActionPriority;
  date: Date;
  actionStatus?: ActionStatus;
  statusChangeDate?: Date;
  creatorUser?: UserReferenceDto;
  title?: string;
  description?: string;
  reply?: string;
  replyingUser?: UserReferenceDto;
  contextReference?: ReferenceDto;
}
