/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AdditionalTestType =
  | 'HAEMOGLOBINURIA'
  | 'PROTEINURIA'
  | 'HEMATURIA'
  | 'ARTERIAL_VENOUS_BLOOD_GAS'
  | 'ALT_SGPT'
  | 'AST_SGOT'
  | 'CREATININE'
  | 'POTASSIUM'
  | 'UREA'
  | 'HAEMOGLOBIN'
  | 'TOTAL_BILIRUBIN'
  | 'CONJ_BILIRUBIN'
  | 'WBC_COUNT'
  | 'PLATELETS'
  | 'PROTHROMBIN_TIME';

export const AdditionalTestType = {
  HAEMOGLOBINURIA: 'HAEMOGLOBINURIA' as AdditionalTestType,
  PROTEINURIA: 'PROTEINURIA' as AdditionalTestType,
  HEMATURIA: 'HEMATURIA' as AdditionalTestType,
  ARTERIALVENOUSBLOODGAS: 'ARTERIAL_VENOUS_BLOOD_GAS' as AdditionalTestType,
  ALTSGPT: 'ALT_SGPT' as AdditionalTestType,
  ASTSGOT: 'AST_SGOT' as AdditionalTestType,
  CREATININE: 'CREATININE' as AdditionalTestType,
  POTASSIUM: 'POTASSIUM' as AdditionalTestType,
  UREA: 'UREA' as AdditionalTestType,
  HAEMOGLOBIN: 'HAEMOGLOBIN' as AdditionalTestType,
  TOTALBILIRUBIN: 'TOTAL_BILIRUBIN' as AdditionalTestType,
  CONJBILIRUBIN: 'CONJ_BILIRUBIN' as AdditionalTestType,
  WBCCOUNT: 'WBC_COUNT' as AdditionalTestType,
  PLATELETS: 'PLATELETS' as AdditionalTestType,
  PROTHROMBINTIME: 'PROTHROMBIN_TIME' as AdditionalTestType,
};
