/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disease } from './disease';
import { DistrictReferenceDto } from './districtReferenceDto';
import { FacilityReferenceDto } from './facilityReferenceDto';
import { PointOfEntryReferenceDto } from './pointOfEntryReferenceDto';
import { RegionReferenceDto } from './regionReferenceDto';
import { UserReferenceDto } from './userReferenceDto';

export interface AggregateReportDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  reportingUser?: UserReferenceDto;
  disease?: Disease;
  year?: number;
  epiWeek?: number;
  region?: RegionReferenceDto;
  district?: DistrictReferenceDto;
  healthFacility?: FacilityReferenceDto;
  pointOfEntry?: PointOfEntryReferenceDto;
  newCases?: number;
  labConfirmations?: number;
  deaths?: number;
}
