/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DengueFeverType = 'DENGUE_FEVER' | 'DENGUE_HEMORRHAGIC_FEVER' | 'DENUGE_SHOCK_SYNDROME';

export const DengueFeverType = {
  DENGUEFEVER: 'DENGUE_FEVER' as DengueFeverType,
  DENGUEHEMORRHAGICFEVER: 'DENGUE_HEMORRHAGIC_FEVER' as DengueFeverType,
  DENUGESHOCKSYNDROME: 'DENUGE_SHOCK_SYNDROME' as DengueFeverType,
};
