/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClassificationCriteriaDto } from './classificationCriteriaDto';
import { Disease } from './disease';

export interface DiseaseClassificationCriteriaDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  disease?: Disease;
  suspectCriteria?: ClassificationCriteriaDto;
  probableCriteria?: ClassificationCriteriaDto;
  confirmedCriteria?: ClassificationCriteriaDto;
  notACaseCriteria?: ClassificationCriteriaDto;
}
