/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationDto } from './locationDto';
import { YesNoUnknown } from './yesNoUnknown';

export interface EpiDataBurialDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  burialPersonName?: string;
  burialRelation?: string;
  burialDateFrom?: Date;
  burialDateTo?: Date;
  burialAddress?: LocationDto;
  burialIll?: YesNoUnknown;
  burialTouching?: YesNoUnknown;
}
