/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EventSourceType =
  | 'NOT_APPLICABLE'
  | 'MEDIA_NEWS'
  | 'HOTLINE_PERSON'
  | 'MATHEMATICAL_MODEL';

export const EventSourceType = {
  NOTAPPLICABLE: 'NOT_APPLICABLE' as EventSourceType,
  MEDIANEWS: 'MEDIA_NEWS' as EventSourceType,
  HOTLINEPERSON: 'HOTLINE_PERSON' as EventSourceType,
  MATHEMATICALMODEL: 'MATHEMATICAL_MODEL' as EventSourceType,
};
