/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disease } from './disease';
import { SymptomsDto } from './symptomsDto';
import { VisitStatus } from './visitStatus';

export interface ExternalVisitDto {
  personUuid: string;
  disease: Disease;
  visitDateTime: Date;
  visitStatus: VisitStatus;
  visitRemarks?: string;
  symptoms?: SymptomsDto;
  reportLat?: number;
  reportLon?: number;
  reportLatLonAccuracy?: number;
}
