/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { YesNoUnknown } from './yesNoUnknown';

export interface HealthConditionsDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  tuberculosis?: YesNoUnknown;
  asplenia?: YesNoUnknown;
  hepatitis?: YesNoUnknown;
  diabetes?: YesNoUnknown;
  hiv?: YesNoUnknown;
  hivArt?: YesNoUnknown;
  chronicLiverDisease?: YesNoUnknown;
  malignancyChemotherapy?: YesNoUnknown;
  chronicHeartFailure?: YesNoUnknown;
  chronicPulmonaryDisease?: YesNoUnknown;
  chronicKidneyDisease?: YesNoUnknown;
  chronicNeurologicCondition?: YesNoUnknown;
  downSyndrome?: YesNoUnknown;
  congenitalSyphilis?: YesNoUnknown;
  immunodeficiencyOtherThanHiv?: YesNoUnknown;
  cardiovascularDiseaseIncludingHypertension?: YesNoUnknown;
  obesity?: YesNoUnknown;
  currentSmoker?: YesNoUnknown;
  formerSmoker?: YesNoUnknown;
  asthma?: YesNoUnknown;
  sickleCellDisease?: YesNoUnknown;
  immunodeficiencyIncludingHiv?: YesNoUnknown;
  otherConditions?: string;
}
