/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Language =
  | 'EN'
  | 'EN_NG'
  | 'EN_GH'
  | 'EN_AF'
  | 'FR'
  | 'FR_CH'
  | 'DE'
  | 'DE_CH'
  | 'ES_EC'
  | 'ES_CU'
  | 'IT'
  | 'IT_CH'
  | 'FI';

export const Language = {
  EN: 'EN' as Language,
  ENNG: 'EN_NG' as Language,
  ENGH: 'EN_GH' as Language,
  ENAF: 'EN_AF' as Language,
  FR: 'FR' as Language,
  FRCH: 'FR_CH' as Language,
  DE: 'DE' as Language,
  DECH: 'DE_CH' as Language,
  ESEC: 'ES_EC' as Language,
  ESCU: 'ES_CU' as Language,
  IT: 'IT' as Language,
  ITCH: 'IT_CH' as Language,
  FI: 'FI' as Language,
};
