/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disease } from './disease';
import { FacilityReferenceDto } from './facilityReferenceDto';
import { PathogenTestResultType } from './pathogenTestResultType';
import { PathogenTestType } from './pathogenTestType';
import { SampleReferenceDto } from './sampleReferenceDto';
import { UserReferenceDto } from './userReferenceDto';

export interface PathogenTestDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  sample: SampleReferenceDto;
  testedDisease: Disease;
  testedDiseaseDetails?: string;
  testType: PathogenTestType;
  testTypeText?: string;
  testDateTime: Date;
  lab: FacilityReferenceDto;
  labDetails?: string;
  labUser: UserReferenceDto;
  testResult: PathogenTestResultType;
  testResultText: string;
  testResultVerified: boolean;
  fourFoldIncreaseAntibodyTiter?: boolean;
  serotype?: string;
  cqValue?: number;
}
