/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApproximateAgeType } from './approximateAgeType';
import { BurialConductor } from './burialConductor';
import { CauseOfDeath } from './causeOfDeath';
import { CommunityReferenceDto } from './communityReferenceDto';
import { DeathPlaceType } from './deathPlaceType';
import { Disease } from './disease';
import { DistrictReferenceDto } from './districtReferenceDto';
import { EducationType } from './educationType';
import { FacilityReferenceDto } from './facilityReferenceDto';
import { FacilityType } from './facilityType';
import { LocationDto } from './locationDto';
import { OccupationType } from './occupationType';
import { PresentCondition } from './presentCondition';
import { RegionReferenceDto } from './regionReferenceDto';
import { Sex } from './sex';
import { SymptomJournalStatus } from './symptomJournalStatus';

export interface PersonDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  firstName: string;
  lastName?: string;
  nickname?: string;
  mothersName?: string;
  mothersMaidenName?: string;
  fathersName?: string;
  sex?: Sex;
  birthdateDD?: number;
  birthdateMM?: number;
  birthdateYYYY?: number;
  approximateAge?: number;
  approximateAgeType?: ApproximateAgeType;
  approximateAgeReferenceDate?: Date;
  placeOfBirthRegion?: RegionReferenceDto;
  placeOfBirthDistrict?: DistrictReferenceDto;
  placeOfBirthCommunity?: CommunityReferenceDto;
  placeOfBirthFacilityType?: FacilityType;
  placeOfBirthFacility?: FacilityReferenceDto;
  placeOfBirthFacilityDetails?: string;
  gestationAgeAtBirth?: number;
  birthWeight?: number;
  presentCondition?: PresentCondition;
  deathDate?: Date;
  causeOfDeath?: CauseOfDeath;
  causeOfDeathDisease?: Disease;
  causeOfDeathDetails?: string;
  deathPlaceType?: DeathPlaceType;
  deathPlaceDescription?: string;
  burialDate?: Date;
  burialPlaceDescription?: string;
  burialConductor?: BurialConductor;
  phone?: string;
  phoneOwner?: string;
  address?: LocationDto;
  emailAddress?: string;
  educationType?: EducationType;
  educationDetails?: string;
  occupationType?: OccupationType;
  occupationDetails?: string;
  generalPractitionerDetails?: string;
  passportNumber?: string;
  nationalHealthId?: string;
  addresses?: Array<LocationDto>;
  hasCovidApp?: boolean;
  covidCodeDelivered?: boolean;
  symptomJournalStatus?: SymptomJournalStatus;
  externalId?: string;
}
