/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ReportingType =
  | 'DOCTOR'
  | 'FORWARDING'
  | 'HOSPITAL_OR_STATIONARY_CARE'
  | 'COMMUNITY_FACILITY'
  | 'LABORATORY'
  | 'OWN_DETERMINATION'
  | 'NOT_DETERMINABLE'
  | 'NOT_RAISED'
  | 'OTHER';

export const ReportingType = {
  DOCTOR: 'DOCTOR' as ReportingType,
  FORWARDING: 'FORWARDING' as ReportingType,
  HOSPITALORSTATIONARYCARE: 'HOSPITAL_OR_STATIONARY_CARE' as ReportingType,
  COMMUNITYFACILITY: 'COMMUNITY_FACILITY' as ReportingType,
  LABORATORY: 'LABORATORY' as ReportingType,
  OWNDETERMINATION: 'OWN_DETERMINATION' as ReportingType,
  NOTDETERMINABLE: 'NOT_DETERMINABLE' as ReportingType,
  NOTRAISED: 'NOT_RAISED' as ReportingType,
  OTHER: 'OTHER' as ReportingType,
};
