/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SimpleTestResultType = 'POSITIVE' | 'NEGATIVE' | 'INDETERMINATE';

export const SimpleTestResultType = {
  POSITIVE: 'POSITIVE' as SimpleTestResultType,
  NEGATIVE: 'NEGATIVE' as SimpleTestResultType,
  INDETERMINATE: 'INDETERMINATE' as SimpleTestResultType,
};
