/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TaskStatus = 'PENDING' | 'DONE' | 'REMOVED' | 'NOT_EXECUTABLE';

export const TaskStatus = {
  PENDING: 'PENDING' as TaskStatus,
  DONE: 'DONE' as TaskStatus,
  REMOVED: 'REMOVED' as TaskStatus,
  NOTEXECUTABLE: 'NOT_EXECUTABLE' as TaskStatus,
};
