/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TaskContext = 'CASE' | 'CONTACT' | 'EVENT' | 'GENERAL';

export const TaskContext = {
  CASE: 'CASE' as TaskContext,
  CONTACT: 'CONTACT' as TaskContext,
  EVENT: 'EVENT' as TaskContext,
  GENERAL: 'GENERAL' as TaskContext,
};
