/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TemperatureSource = 'AXILLARY' | 'ORAL' | 'RECTAL' | 'NON_CONTACT';

export const TemperatureSource = {
  AXILLARY: 'AXILLARY' as TemperatureSource,
  ORAL: 'ORAL' as TemperatureSource,
  RECTAL: 'RECTAL' as TemperatureSource,
  NONCONTACT: 'NON_CONTACT' as TemperatureSource,
};
