/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TravelType = 'ABROAD' | 'WITHIN_COUNTRY';

export const TravelType = {
  ABROAD: 'ABROAD' as TravelType,
  WITHINCOUNTRY: 'WITHIN_COUNTRY' as TravelType,
};
