/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TreatmentRoute = 'ORAL' | 'IV' | 'RECTAL' | 'TOPICAL' | 'OTHER';

export const TreatmentRoute = {
  ORAL: 'ORAL' as TreatmentRoute,
  IV: 'IV' as TreatmentRoute,
  RECTAL: 'RECTAL' as TreatmentRoute,
  TOPICAL: 'TOPICAL' as TreatmentRoute,
  OTHER: 'OTHER' as TreatmentRoute,
};
