/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PrescriptionReferenceDto } from './prescriptionReferenceDto';
import { TherapyReferenceDto } from './therapyReferenceDto';
import { TreatmentRoute } from './treatmentRoute';
import { TreatmentType } from './treatmentType';
import { TypeOfDrug } from './typeOfDrug';

export interface TreatmentDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  therapy?: TherapyReferenceDto;
  treatmentDateTime?: Date;
  executingClinician?: string;
  treatmentType?: TreatmentType;
  treatmentDetails?: string;
  typeOfDrug?: TypeOfDrug;
  dose?: string;
  route?: TreatmentRoute;
  routeDetails?: string;
  additionalNotes?: string;
  prescription?: PrescriptionReferenceDto;
}
