/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TreatmentType =
  | 'DRUG_INTAKE'
  | 'ORAL_REHYDRATION_SALTS'
  | 'BLOOD_TRANSFUSION'
  | 'RENAL_REPLACEMENT_THERAPY'
  | 'IV_FLUID_THERAPY'
  | 'OXYGEN_THERAPY'
  | 'INVASIVE_MECHANICAL_VENTILATION'
  | 'VASOPRESSORS_INOTROPES'
  | 'OTHER';

export const TreatmentType = {
  DRUGINTAKE: 'DRUG_INTAKE' as TreatmentType,
  ORALREHYDRATIONSALTS: 'ORAL_REHYDRATION_SALTS' as TreatmentType,
  BLOODTRANSFUSION: 'BLOOD_TRANSFUSION' as TreatmentType,
  RENALREPLACEMENTTHERAPY: 'RENAL_REPLACEMENT_THERAPY' as TreatmentType,
  IVFLUIDTHERAPY: 'IV_FLUID_THERAPY' as TreatmentType,
  OXYGENTHERAPY: 'OXYGEN_THERAPY' as TreatmentType,
  INVASIVEMECHANICALVENTILATION: 'INVASIVE_MECHANICAL_VENTILATION' as TreatmentType,
  VASOPRESSORSINOTROPES: 'VASOPRESSORS_INOTROPES' as TreatmentType,
  OTHER: 'OTHER' as TreatmentType,
};
