/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeOfPlace =
  | 'FACILITY'
  | 'FESTIVITIES'
  | 'HOME'
  | 'HOSPITAL'
  | 'MEANS_OF_TRANSPORT'
  | 'PUBLIC_PLACE'
  | 'UNKNOWN'
  | 'OTHER';

export const TypeOfPlace = {
  FACILITY: 'FACILITY' as TypeOfPlace,
  FESTIVITIES: 'FESTIVITIES' as TypeOfPlace,
  HOME: 'HOME' as TypeOfPlace,
  HOSPITAL: 'HOSPITAL' as TypeOfPlace,
  MEANSOFTRANSPORT: 'MEANS_OF_TRANSPORT' as TypeOfPlace,
  PUBLICPLACE: 'PUBLIC_PLACE' as TypeOfPlace,
  UNKNOWN: 'UNKNOWN' as TypeOfPlace,
  OTHER: 'OTHER' as TypeOfPlace,
};
