/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type VaccinationInfoSource = 'VACCINATION_CARD' | 'ORAL_COMMUNICATION';

export const VaccinationInfoSource = {
  VACCINATIONCARD: 'VACCINATION_CARD' as VaccinationInfoSource,
  ORALCOMMUNICATION: 'ORAL_COMMUNICATION' as VaccinationInfoSource,
};
