/**
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.51.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disease } from './disease';
import { PersonReferenceDto } from './personReferenceDto';
import { SymptomsDto } from './symptomsDto';
import { UserReferenceDto } from './userReferenceDto';
import { VisitOrigin } from './visitOrigin';
import { VisitStatus } from './visitStatus';

export interface VisitDto {
  creationDate?: Date;
  changeDate?: Date;
  uuid?: string;
  pseudonymized?: boolean;
  person: PersonReferenceDto;
  disease?: Disease;
  visitDateTime: Date;
  visitUser: UserReferenceDto;
  visitStatus: VisitStatus;
  visitRemarks?: string;
  symptoms?: SymptomsDto;
  reportLat?: number;
  reportLon?: number;
  reportLatLonAccuracy?: number;
  origin?: VisitOrigin;
}
