import { FormBase } from '../../shared/dynamic-form/types/form-element-base';
import {
  FORM_DATA_INPUT,
  FORM_DATA_CHECKBOX,
  FORM_DATA_WIDGET,
  FORM_DATA_NULL,
} from '../../app.constants';

export const FORM_DATA_EXPORT_CONFIGURATION: FormBase<any>[] = [
  {
    id: 'export',
    title: 'captions.export',
    required: true,
    fields: [
      {
        ...FORM_DATA_NULL,
        key: 'exportType',
        className: 'hidden',
      },
      {
        ...FORM_DATA_INPUT,
        key: 'name',
        label: 'captions.ExportConfiguration.NAME',
        validation: ['required'],
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sharedToPublic',
        label: 'captions.ExportConfiguration.sharedToPublic',
        newLine: true,
      },
    ],
  },
  {
    id: 'groupSelect',
    title: 'Customize export',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          info: 'strings.infoEditExportConfiguration',
          sections: ['coreData', 'personData', 'vaccinationData'],
        },
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'coreData',
    title: 'enum.ExportGroupType.CORE',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['coreData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventParticipantUuid',
        label: 'captions.EventParticipantExport.eventParticipantUuid',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'caseUuid',
        label: 'captions.EventParticipant.caseUuid',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sampleInformation',
        label: 'captions.EventParticipantExport.sampleInformation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventParticipantInvolvmentDescription',
        label: 'captions.EventParticipantExport.eventParticipantInvolvmentDescription',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'uuid',
        label: 'captions.Event.uuid',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventStatus',
        label: 'captions.Event.eventStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventInvestigationStatus',
        label: 'captions.Event.eventInvestigationStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventDisease',
        label: 'captions.EventParticipantExport.eventDisease',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'typeOfPlace',
        label: 'captions.Event.typeOfPlace',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'startDate',
        label: 'captions.Event.startDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'endDate',
        label: 'captions.Event.endDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventTitle',
        label: 'captions.Event.eventTitle',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventDesc',
        label: 'captions.Event.eventDesc',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'region',
        label: 'captions.Location.region',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'district',
        label: 'captions.Location.district',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'community',
        label: 'captions.Location.community',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'city',
        label: 'captions.city',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'street',
        label: 'captions.Location.street',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'houseNumber',
        label: 'captions.Location.houseNumber',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'contactCount',
        label: 'captions.EventParticipant.contactCount',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'personData',
    title: 'enum.ExportGroupType.PERSON',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['personData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'personUuid',
        label: 'captions.EventParticipant.personUuid',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'firstName',
        label: 'captions.firstName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastName',
        label: 'captions.lastName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'salutation',
        label: 'captions.Person.salutation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherSalutation',
        label: 'captions.Person.otherSalutation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sex',
        label: 'captions.EventParticipant.sex',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'approximateAge',
        label: 'captions.EventParticipant.approximateAge',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'ageGroup',
        label: 'ageGroup',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'birthdate',
        label: 'captions.Person.birthdate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'presentCondition',
        label: 'captions.Person.presentCondition',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'deathDate',
        label: 'captions.Person.deathDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.region',
        label: 'captions.Location.region',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.district',
        label: 'captions.Location.district',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.community',
        label: 'captions.Location.community',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.city',
        label: 'captions.city',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.street',
        label: 'captions.Location.street',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.houseNumber',
        label: 'captions.Location.houseNumber',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.additionalInformation',
        label: 'captions.Location.additionalInformation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.postalCode',
        label: 'captions.Location.postalCode',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'addressGpsCoordinates',
        label: 'captions.EventParticipantExport.addressGpsCoordinates',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.phone',
        label: 'captions.Person.phone',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.emailAddress',
        label: 'captions.Person.emailAddress',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.birthName',
        label: 'captions.Person.birthName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.birthCountry',
        label: 'captions.Person.birthCountry',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.citizenship',
        label: 'captions.Person.citizenship',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'vaccinationData',
    title: 'enum.ExportGroupType.VACCINATION',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['vaccinationData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccinationStatus',
        label: 'captions.EventParticipant.vaccinationStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'numberOfDoses',
        label: 'captions.Immunization.numberOfDoses',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccinationInfoSource',
        label: 'captions.Vaccination.vaccinationInfoSource',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'firstVaccinationDate',
        label: 'firstVaccinationDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastVaccinationDate',
        label: 'lastVaccinationDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineName',
        label: 'captions.Vaccination.vaccineName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherVaccineName',
        label: 'captions.Vaccination.otherVaccineName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineManufacturer',
        label: 'captions.Vaccination.vaccineManufacturer',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherVaccineManufacturer',
        label: 'captions.Vaccination.otherVaccineManufacturer',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineInn',
        label: 'captions.Vaccination.vaccineInn',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineBatchNumber',
        label: 'captions.Vaccination.vaccineBatchNumber',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineUniiCode',
        label: 'captions.Vaccination.vaccineUniiCode',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineAtcCode',
        label: 'captions.Vaccination.vaccineAtcCode',
        className: 'fullwidth',
      },
    ],
  },
];
