import { FORM_DATA_INPUT, FORM_DATA_CHECKBOX, FORM_DATA_WIDGET } from '../../app.constants';

export const FORM_DATA_EXPORT_CONFIGURATION = [
  {
    id: 'export',
    title: 'captions.export',
    required: true,
    fields: [
      {
        ...FORM_DATA_INPUT,
        key: 'name',
        label: 'captions.ExportConfiguration.NAME',
        validation: ['required'],
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sharedToPublic',
        label: 'captions.ExportConfiguration.sharedToPublic',
        newLine: true,
      },
    ],
  },
  {
    id: 'groupSelect',
    title: 'Customize export',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'coreData',
    title: 'enum.ExportGroupType.CORE',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'id',
        label: 'captions.CaseExport.id',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'uuid',
        label: 'captions.CaseData.uuid',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'epidNumber',
        label: 'captions.CaseData.epidNumber',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'externalID',
        label: 'captions.CaseData.externalID',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'externalToken',
        label: 'captions.CaseData.externalToken',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'internalToken',
        label: 'captions.CaseData.internalToken',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'diseaseFormatted',
        label: 'captions.CaseExport.diseaseFormatted',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'diseaseDetails',
        label: 'captions.CaseData.diseaseDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'diseaseVariant',
        label: 'captions.CaseData.diseaseVariant',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'diseaseVariantDetails',
        label: 'captions.diseaseVariantDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'personUuid',
        label: 'captions.CaseData.personUuid',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'reportDate',
        label: 'captions.CaseData.reportDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'responsibleRegion',
        label: 'captions.CaseData.responsibleRegion',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'responsibleDistrict',
        label: 'captions.CaseData.responsibleDistrict',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'responsibleCommunity',
        label: 'captions.CaseData.responsibleCommunity',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'region',
        label: 'captions.CaseData.region',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'district',
        label: 'captions.CaseData.district',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'community',
        label: 'captions.CaseData.community',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'facilityType',
        label: 'captions.CaseData.facilityType',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'healthFacility',
        label: 'captions.CaseData.healthFacility',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'healthFacilityDetails',
        label: 'captions.CaseData.healthFacilityDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'pointOfEntry',
        label: 'captions.CaseData.pointOfEntry',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'pointOfEntryDetails',
        label: 'captions.CaseData.pointOfEntryDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'caseClassification',
        label: 'captions.CaseData.caseClassification',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'investigationStatus',
        label: 'captions.CaseData.investigationStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'investigatedDate',
        label: 'captions.CaseData.investigatedDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'outcome',
        label: 'captions.CaseData.outcome',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'notACaseReasonNegativeTest',
        label: 'captions.CaseData.notACaseReasonNegativeTest',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'notACaseReasonPhysicianInformation',
        label: 'captions.CaseData.notACaseReasonPhysicianInformation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'notACaseReasonDifferentPathogen',
        label: 'captions.CaseData.notACaseReasonDifferentPathogen',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'notACaseReasonOther',
        label: 'captions.CaseData.notACaseReasonOther',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'notACaseReasonDetails',
        label: 'captions.CaseData.notACaseReasonDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'caseIdentificationSource',
        label: 'captions.CaseData.caseIdentificationSource',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'screeningType',
        label: 'captions.CaseData.screeningType',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'sensitiveData',
    title: 'enum.ExportGroupType.SENSITIVE',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'firstName',
        label: 'captions.CaseExport.firstName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastName',
        label: 'captions.CaseExport.lastName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'salutation',
        label: 'captions.Person.salutation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherSalutation',
        label: 'captions.Person.otherSalutation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sex',
        label: 'captions.Person.sex',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'pregnant',
        label: 'captions.CaseData.pregnant',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'trimester',
        label: 'captions.CaseData.trimester',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'postpartum',
        label: 'captions.CaseData.postpartum',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'approximateAge',
        label: 'captions.Person.approximateAge',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'birthdate',
        label: 'captions.Person.birthdate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'deathDate',
        label: 'captions.Person.deathDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'region',
        label: 'captions.regionName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'district',
        label: 'captions.Location.district',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'community',
        label: 'captions.Location.community',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'city',
        label: 'captions.city',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'street',
        label: 'captions.Location.street',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'houseNumber',
        label: 'captions.Location.houseNumber',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'additionalInformation',
        label: 'captions.Location.additionalInformation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'postalCode',
        label: 'captions.Location.postalCode',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'addressGpsCoordinates',
        label: 'captions.CaseExport.addressGpsCoordinates',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'facility',
        label: 'captions.Location.facility',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'facilityDetails',
        label: 'captions.Location.facilityDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'phone',
        label: 'captions.Person.phone',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'phoneOwner',
        label: 'captions.Person.phoneOwner',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'emailAddress',
        label: 'captions.Person.emailAddress',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherContactDetails',
        label: 'captions.Person.otherContactDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'birthName',
        label: 'captions.Person.birthName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'birthCountry',
        label: 'captions.Person.birthCountry',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'citizenship',
        label: 'captions.Person.citizenship',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'personData',
    title: 'enum.ExportGroupType.PERSON',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'ageGroup',
        label: 'captions.CaseExport.ageGroup',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'presentCondition',
        label: 'captions.Person.presentCondition',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'educationType',
        label: 'captions.Person.educationType',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'educationDetails',
        label: 'captions.Person.educationDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'occupationType',
        label: 'captions.Person.occupationType',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'occupationDetails',
        label: 'captions.Person.occupationDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'armedForcesRelationType',
        label: 'captions.Person.armedForcesRelationType',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'hospitalizationData',
    title: 'enum.ExportGroupType.HOSPITALIZATION',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'admittedToHealthFacility',
        label: 'captions.CaseHospitalization.admittedToHealthFacility',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'admissionDate',
        label: 'captions.CaseHospitalization.admissionDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'dischargeDate',
        label: 'captions.CaseHospitalization.dischargeDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'leftAgainstAdvice',
        label: 'captions.CaseHospitalization.leftAgainstAdvice',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'epiData',
    title: 'enum.ExportGroupType.EPIDEMIOLOGICAL',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'traveled',
        label: 'captions.CaseExport.traveled',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'travelHistory',
        label: 'captions.CaseExport.travelHistory',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'burialAttended',
        label: 'captions.CaseExport.burialAttended',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'contactWithSourceCaseKnown',
        label: 'captions.EpiData.contactWithSourceCaseKnown',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'vaccinationData',
    title: 'enum.ExportGroupType.VACCINATION',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccinationStatus',
        label: 'captions.CaseData.vaccinationStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'numberOfDoses',
        label: 'captions.Immunization.numberOfDoses',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccinationInfoSource',
        label: 'captions.Vaccination.vaccinationInfoSource',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'firstVaccinationDate',
        label: 'captions.Immunization.firstVaccinationDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastVaccinationDate',
        label: 'captions.Immunization.lastVaccinationDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineName',
        label: 'captions.Vaccination.vaccineName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherVaccineName',
        label: 'captions.Vaccination.otherVaccineName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineManufacturer',
        label: 'captions.Vaccination.vaccineManufacturer',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherVaccineManufacturer',
        label: 'captions.Vaccination.otherVaccineManufacturer',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineInn',
        label: 'captions.Vaccination.vaccineInn',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineBatchNumber',
        label: 'captions.Vaccination.vaccineBatchNumber',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineUniiCode',
        label: 'captions.Vaccination.vaccineUniiCode',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineAtcCode',
        label: 'captions.Vaccination.vaccineAtcCode',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'clinicalCourseData',
    title: 'enum.ExportGroupType.CLINICAL_COURSE',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'healthConditions',
        label: 'captions.CaseData.healthConditions',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'numberOfClinicalVisits',
        label: 'captions.CaseExport.numberOfClinicalVisits',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'therapyData',
    title: 'enum.ExportGroupType.THERAPY',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'numberOfPrescriptions',
        label: 'captions.CaseExport.numberOfPrescriptions',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'numberOfTreatments',
        label: 'captions.CaseExport.numberOfTreatments',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'followUpData',
    title: 'enum.ExportGroupType.FOLLOW_UP',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'followUpStatus',
        label: 'captions.CaseData.followUpStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'followUpUntil',
        label: 'captions.CaseData.followUpUntil',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'numberOfVisits',
        label: 'captions.CaseData.numberOfVisits',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastCooperativeVisitSymptomatic',
        label: 'captions.CaseExport.lastCooperativeVisitSymptomatic',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastCooperativeVisitDate',
        label: 'captions.CaseExport.lastCooperativeVisitDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastCooperativeVisitSymptoms',
        label: 'captions.CaseExport.lastCooperativeVisitSymptoms',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'additionalData',
    title: 'enum.ExportGroupType.ADDITIONAL',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'country',
        label: 'captions.CaseExport.country',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'initialDetectionPlace',
        label: 'captions.CaseExport.initialDetectionPlace',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'clinicalConfirmation',
        label: 'captions.CaseData.clinicalConfirmation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'epidemiologicalConfirmation',
        label: 'captions.CaseData.epidemiologicalConfirmation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'laboratoryDiagnosticConfirmation',
        label: 'captions.CaseData.laboratoryDiagnosticConfirmation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'outcomeDate',
        label: 'captions.CaseData.outcomeDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sequelae',
        label: 'captions.CaseData.sequelae',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'bloodOrganOrTissueDonated',
        label: 'captions.CaseData.bloodOrganOrTissueDonated',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'nosocomialOutbreak',
        label: 'captions.CaseData.nosocomialOutbreak',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'prohibitionToWork',
        label: 'captions.CaseData.prohibitionToWork',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'reInfection',
        label: 'captions.CaseData.reInfection',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'quarantineInformation',
        label: 'captions.CaseExport.quarantineInformation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'maxSourceCaseClassification',
        label: 'captions.CaseExport.maxSourceCaseClassification',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'associatedWithOutbreak',
        label: 'captions.CaseExport.associatedWithOutbreak',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'symptoms',
        label: 'captions.CaseData.symptoms',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sampleInformation',
        label: 'captions.CaseExport.sampleInformation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'clinicianName',
        label: 'captions.CaseData.clinicianName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'clinicianPhone',
        label: 'captions.CaseData.clinicianPhone',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'clinicianEmail',
        label: 'captions.CaseData.clinicianEmail',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'reportingUserName',
        label: 'captions.CaseExport.reportingUserName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'followUpStatusChangeUserName',
        label: 'captions.CaseExport.followUpStatusChangeUserName',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'eventData',
    title: 'enum.ExportGroupType.EVENT',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventCount',
        label: 'captions.CaseData.eventCount',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'latestEventId',
        label: 'captions.CaseData.latestEventId',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'latestEventStatus',
        label: 'captions.CaseData.latestEventStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'latestEventTitle',
        label: 'captions.CaseData.latestEventTitle',
        className: 'fullwidth',
      },
    ],
  },
];
