import { marker as _ } from '@biesbjerg/ngx-translate-extract-marker';
import {
  FORM_DATA_CHECKBOX,
  FORM_DATA_DATE,
  FORM_DATA_INPUT,
  FORM_DATA_RADIO,
  FORM_DATA_SELECT,
  FORM_DATA_TEXTAREA,
  FORM_DATA_NULL,
  FORM_DATA_NUMBER,
  FORM_DATA_WIDGET,
  CaseClassification,
  InvestigationStatus,
  CaseOutcome,
  Disease,
  YesNoUnknown,
  PlaceOfStay,
  Quarantine,
  VaccinationStatus,
  VaccinationSource,
  VaccineName,
  VaccineManufacturer,
  CaseIdentificationSource,
  ScreeningType,
  InfectionSetting,
  Trimester,
} from '../../../app.constants';

import { EnumToKeyValuePipe } from '../../../_pipes/enum-to-key-value/enum-to-key-value.pipe';

const pipe = new EnumToKeyValuePipe();

const optionsCaseClassification = pipe.transform(CaseClassification);
const optionsCaseOutcome = pipe.transform(CaseOutcome);
const optionsInvestigationStatus = pipe.transform(InvestigationStatus);
const optionsDisese = pipe.transform(Disease);
const optionsYesNoUnknown = pipe.transform(YesNoUnknown);
const optionsPlaceOfStay = pipe.transform(PlaceOfStay);
const optionsQuarantine = pipe.transform(Quarantine);
const optionsVaccinationStatus = pipe.transform(VaccinationStatus);
const optionsVaccinationSource = pipe.transform(VaccinationSource);
const optionsVaccineName = pipe.transform(VaccineName);
const optionsVaccineManufacturer = pipe.transform(VaccineManufacturer);
const optionsCaseIdentificationSource = pipe.transform(CaseIdentificationSource);
const optionsScreeningType = pipe.transform(ScreeningType);
const optionsInfectionSetting = pipe.transform(InfectionSetting);
const optionsTrimester = pipe.transform(Trimester);

export const FORM_DATA_CASE_DETAILS = [
  {
    id: 'reportDate',
    title: _('Date of report'),
    required: true,
    anchor: 'case_data',
    anchorLabel: _('headingCaseData'),
    fields: [
      {
        ...FORM_DATA_DATE,
        key: 'reportDate',
        validation: ['required'],
      },
    ],
  },
  {
    id: 'caseClassification',
    title: _('CaseClassification'),
    required: true,
    fields: [
      {
        ...FORM_DATA_RADIO,
        key: 'caseClassification',
        validation: ['required'],
        options: optionsCaseClassification,
      },
      {
        ...FORM_DATA_SELECT,
        key: 'clinicalConfirmation',
        label: _('CaseData.clinicalConfirmation'),
        options: optionsYesNoUnknown,
        newLine: true,
      },
      {
        ...FORM_DATA_SELECT,
        key: 'epidemiologicalConfirmation',
        label: _('CaseData.epidemiologicalConfirmation'),
        options: optionsYesNoUnknown,
      },
      {
        ...FORM_DATA_SELECT,
        key: 'laboratoryDiagnosticConfirmation',
        label: _('CaseData.laboratoryDiagnosticConfirmation'),
        options: optionsYesNoUnknown,
      },
      {
        ...FORM_DATA_DATE,
        key: 'classificationDate',
        label: _('CaseData.classificationDate'),
        newLine: true,
        className: 'size-medium',
      },
      {
        ...FORM_DATA_NULL,
        key: 'classificationUser.caption',
        label: _('CaseData.classificationUser'),
        dependingOn: 'classificationUser.caption',
      },
    ],
  },
  {
    id: 'investigationStatus',
    title: _('CaseData.investigationStatus'),
    required: true,
    fields: [
      {
        ...FORM_DATA_RADIO,
        key: 'investigationStatus',
        validation: ['required'],
        options: optionsInvestigationStatus,
      },
      {
        ...FORM_DATA_DATE,
        key: 'investigatedDate',
        label: _('CaseData.investigatedDate'),
        newLine: true,
        dependingOn: 'investigationStatus',
        dependingOnValues: ['DISCARDED', 'DONE'],
      },
    ],
  },
  {
    id: 'externalData',
    title: _('CaseData.externalData'),
    required: true,
    fields: [
      {
        ...FORM_DATA_INPUT,
        key: 'externalID',
        label: _('CaseData.externalID'),
      },
      {
        ...FORM_DATA_INPUT,
        key: 'externalToken',
        label: _('CaseData.externalToken'),
      },
    ],
  },
  {
    id: 'disease',
    title: _('disease'),
    required: true,
    fields: [
      {
        ...FORM_DATA_SELECT,
        key: 'disease',
        label: _('disease'),
        validation: ['required'],
        options: optionsDisese,
      },
      {
        ...FORM_DATA_SELECT,
        key: 'diseaseVariant.uuid',
        label: _('CaseData.diseaseVariant'),
        options: optionsDisese,
      },
    ],
  },
  {
    id: 'epidNumber',
    title: _('CaseData.epidNumber'),
    required: false,
    fields: [
      {
        ...FORM_DATA_INPUT,
        key: 'epidNumber',
      },
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-new-epid-number',
      },
    ],
  },
  {
    id: 'caseOutcome',
    title: _('CaseData.outcome'),
    required: true,
    fields: [
      {
        ...FORM_DATA_RADIO,
        key: 'outcome',
        validation: ['required'],
        options: optionsCaseOutcome,
      },
      {
        ...FORM_DATA_DATE,
        key: 'outcomeDate',
        hint: _('CaseData.outcomeDate'),
        newLine: true,
        dependingOn: 'outcome',
        dependingOnValues: ['DECEASED', 'RECOVERED'],
      },
      {
        ...FORM_DATA_RADIO,
        key: 'sequelae',
        label: _('CaseData.sequelae'),
        options: optionsYesNoUnknown,
        dependingOn: 'outcome',
        dependingOnValues: ['RECOVERED', 'UNKNOWN'],
        newLine: true,
      },
      {
        ...FORM_DATA_INPUT,
        key: 'sequelaeDetails',
        label: _('CaseData.sequelaeDetails'),
        newLine: true,
        className: 'size-full',
        dependingOn: 'sequelae',
        dependingOnValues: ['YES'],
      },
    ],
  },
  {
    id: 'source',
    title: _('CaseData.source'),
    fields: [
      {
        ...FORM_DATA_SELECT,
        key: 'reportingDistrict.uuid',
        label: _('CaseData.reportingDistrict'),
        options: [
          {
            key: 'default',
            value: _('defaultDistrict'),
          },
        ],
      },
      {
        ...FORM_DATA_SELECT,
        key: 'caseIdentificationSource',
        label: _('CaseData.caseIdentificationSource'),
        options: optionsCaseIdentificationSource,
        newLine: true,
      },
      {
        ...FORM_DATA_SELECT,
        key: 'screeningType',
        label: _('CaseData.screeningType'),
        options: optionsScreeningType,
        dependingOn: 'caseIdentificationSource',
        dependingOnValues: ['SCREENING'],
      },
    ],
  },
  {
    id: 'caseOrigin',
    title: _('CaseData.caseOrigin'),
    required: false,
    fields: [
      {
        ...FORM_DATA_NULL,
        key: 'caseOrigin',
      },
      {
        ...FORM_DATA_SELECT,
        key: 'region.uuid',
        label: _('CaseData.responsibleRegion'),
        validation: ['required'],
        options: [
          {
            key: 'default',
            value: _('defaultRegion'),
          },
        ],
        newLine: true,
        className: 'size-large',
        dependingOn: 'caseOrigin',
        dependingOnValues: ['IN_COUNTRY'],
      },
      {
        ...FORM_DATA_SELECT,
        key: 'district.uuid',
        label: _('CaseData.responsibleDistrict'),
        validation: ['required'],
        options: [
          {
            key: 'default',
            value: _('defaultDistrict'),
          },
        ],
        newLine: true,
        className: 'size-large',
        dependingOn: 'caseOrigin',
        dependingOnValues: ['IN_COUNTRY'],
      },
      {
        ...FORM_DATA_SELECT,
        key: 'community.uuid',
        label: _('CaseData.responsibleCommunity'),
        options: [
          {
            key: 'default',
            value: _('defaultCommunity'),
          },
        ],
        newLine: true,
        className: 'size-large',
        dependingOn: 'caseOrigin',
        dependingOnValues: ['IN_COUNTRY'],
      },
      {
        ...FORM_DATA_NULL,
        key: 'pointOfEntry.caption',
        label: _('CaseData.pointOfEntry'),
        dependingOn: 'caseOrigin',
        dependingOnValues: ['POINT_OF_ENTRY'],
      },
      {
        ...FORM_DATA_NULL,
        key: 'pointOfEntryDetails',
        label: ' ',
        dependingOn: 'caseOrigin',
        dependingOnValues: ['POINT_OF_ENTRY'],
      },
    ],
  },
  {
    id: 'placeOfStay',
    title: _('casePlaceOfStay'),
    required: true,
    fields: [
      {
        ...FORM_DATA_RADIO,
        key: 'placeOfStaty',
        validation: ['required'],
        options: optionsPlaceOfStay,
      },
      {
        ...FORM_DATA_SELECT,
        key: 'healthFacility.uuid',
        label: _('CaseData.facility.region'),
        validation: ['required'],
        options: [
          {
            key: 'default',
            value: _('defaultRegion'),
          },
        ],
        newLine: true,
        className: 'size-large',
        dependingOn: 'placeOfStaty',
        dependingOnValues: ['FACILITY'],
      },
      {
        ...FORM_DATA_SELECT,
        key: 'facilityType',
        label: _('CaseData.facilityType'),
        validation: ['required'],
        options: [
          {
            key: 'LABORATORY',
            value: _('FacilityType.LABORATORY'),
          },
        ],
        newLine: true,
        className: 'size-large',
        dependingOn: 'placeOfStaty',
        dependingOnValues: ['FACILITY'],
      },
      {
        ...FORM_DATA_INPUT,
        key: 'healthFacilityDetails',
        label: _('CaseData.healthFacilityDetails'),
        newLine: true,
        className: 'size-full',
        dependingOn: 'placeOfStaty',
        dependingOnValues: ['FACILITY'],
      },
      {
        ...FORM_DATA_INPUT,
        key: 'placeOfStatyDetails',
        label: _('CaseData.noneHealthFacilityDetails'),
        newLine: true,
        className: 'size-full',
        dependingOn: 'placeOfStaty',
        dependingOnValues: ['HOME'],
      },
    ],
  },
  {
    id: 'quarantine',
    title: _('CaseData.quarantine'),
    required: false,
    fields: [
      {
        ...FORM_DATA_RADIO,
        key: 'quarantineHomePossible',
        label: _('CaseData.quarantineHomePossible'),
        options: optionsYesNoUnknown,
      },
      {
        ...FORM_DATA_INPUT,
        key: 'quarantineHomePossibleComment',
        label: _('CaseData.quarantineHomePossibleComment'),
        className: 'size-large',
        dependingOn: 'quarantineHomePossible',
        dependingOnValues: ['NO'],
      },
      {
        ...FORM_DATA_RADIO,
        key: 'quarantineHomeSupplyEnsured',
        label: _('CaseData.quarantineHomeSupplyEnsured'),
        options: optionsYesNoUnknown,
        dependingOn: 'quarantineHomePossible',
        dependingOnValues: ['YES'],
        newLine: true,
      },
      {
        ...FORM_DATA_INPUT,
        key: 'quarantineHomeSupplyEnsuredComment',
        label: _('CaseData.quarantineHomePossibleComment'),
        className: 'size-large',
        dependingOn: 'quarantineHomeSupplyEnsured',
        dependingOnValues: ['NO'],
      },
      {
        ...FORM_DATA_SELECT,
        key: 'quarantine',
        label: _('CaseData.placeOfQuarantine'),
        options: optionsQuarantine,
        newLine: true,
      },
      {
        ...FORM_DATA_DATE,
        key: 'quarantineFrom',
        label: _('CaseData.quarantinePeriod'),
        hint: _('CaseData.quarantineFrom'),
        dependingOn: 'quarantine',
        dependingOnValues: ['HOME', 'INSTITUTIONELL'],
      },
      {
        ...FORM_DATA_DATE,
        key: 'quarantineTo',
        label: ' ',
        hint: _('CaseData.quarantineTo'),
        dependingOn: 'quarantine',
        dependingOnValues: ['HOME', 'INSTITUTIONELL'],
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'quarantineOrderedVerbally',
        label: _('CaseData.quarantineOrderedVerbally'),
        dependingOn: 'quarantine',
        dependingOnValues: ['HOME', 'INSTITUTIONELL'],
        newLine: true,
      },
      {
        ...FORM_DATA_DATE,
        key: 'quarantineOrderedVerballyDate',
        hint: _('CaseData.quarantineOrderedVerballyDate'),
        dependingOn: 'quarantineOrderedVerbally',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'quarantineOrderedOfficialDocument',
        label: _('CaseData.quarantineOrderedOfficialDocument'),
        dependingOn: 'quarantine',
        dependingOnValues: ['HOME', 'INSTITUTIONELL'],
        newLine: true,
      },
      {
        ...FORM_DATA_DATE,
        key: 'quarantineOrderedOfficialDocumentDate',
        hint: _('CaseData.quarantineOrderedOfficialDocumentDate'),
        dependingOn: 'quarantineOrderedOfficialDocument',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'quarantineOfficialOrderSent',
        label: _('CaseData.quarantineOfficialOrderSent'),
        dependingOn: 'quarantineOrderedOfficialDocument',
        newLine: true,
      },
      {
        ...FORM_DATA_DATE,
        key: 'quarantineOfficialOrderSentDate',
        hint: _('CaseData.quarantineOfficialOrderSentDate'),
        dependingOn: 'quarantineOfficialOrderSent',
      },
      {
        ...FORM_DATA_INPUT,
        key: 'quarantineHelpNeeded',
        label: _('CaseData.quarantineHelpNeeded'),
        newLine: true,
        className: 'size-full',
        dependingOn: 'quarantine',
        dependingOnValues: ['HOME', 'INSTITUTIONELL'],
      },
      {
        ...FORM_DATA_INPUT,
        key: 'quarantineTypeDetails',
        label: _('CaseData.quarantineTypeDetails'),
        newLine: true,
        className: 'size-full',
        dependingOn: 'quarantine',
        dependingOnValues: ['OTHER'],
      },
    ],
  },
  {
    id: 'reportGPS',
    title: _('CaseData.reportGPS'),
    required: false,
    fields: [
      {
        ...FORM_DATA_INPUT,
        key: 'reportLat',
        label: _('CaseData.reportLatSimple'),
      },
      {
        ...FORM_DATA_INPUT,
        key: 'reportLon',
        label: _('CaseData.reportLonSimple'),
        newLine: true,
      },
      {
        ...FORM_DATA_INPUT,
        key: 'reportLatLonAccuracy',
        label: _('CaseData.reportLatLonAccuracySimple'),
        newLine: true,
      },
    ],
  },
  {
    id: 'donation',
    title: _('CaseData.donation'),
    required: false,
    anchor: 'additional_information',
    anchorLabel: _('CaseData.additionalInfo'),
    fields: [
      {
        ...FORM_DATA_RADIO,
        key: 'bloodOrganOrTissueDonated',
        label: _('CaseData.bloodOrganOrTissueDonated'),
        options: optionsYesNoUnknown,
      },
    ],
  },
  {
    id: 'infection',
    title: _('CaseData.infection'),
    required: false,
    fields: [
      {
        ...FORM_DATA_CHECKBOX,
        key: 'nosocomialOutbreak',
        label: _('CaseData.nosocomialOutbreak'),
      },
      {
        ...FORM_DATA_SELECT,
        key: 'infectionSetting',
        label: _('CaseData.infectionSetting'),
        options: optionsInfectionSetting,
        dependingOn: 'nosocomialOutbreak',
      },
      {
        ...FORM_DATA_RADIO,
        key: 'reInfection',
        label: _('CaseData.reInfection'),
        options: optionsYesNoUnknown,
        newLine: true,
      },
      {
        ...FORM_DATA_DATE,
        key: 'previousInfectionDate',
        label: ' ',
        hint: _('CaseData.previousInfectionDate'),
        dependingOn: 'reInfection',
        dependingOnValues: ['YES'],
      },
    ],
  },
  {
    id: 'medicalInformation',
    title: _('headingMedicalInformation'),
    required: false,
    fields: [
      {
        ...FORM_DATA_RADIO,
        key: 'pregnant',
        label: _('CaseData.pregnancy'),
        options: optionsYesNoUnknown,
      },
      {
        ...FORM_DATA_RADIO,
        key: 'postpartum',
        label: _('CaseData.postpartum'),
        options: optionsYesNoUnknown,
      },
      {
        ...FORM_DATA_RADIO,
        key: 'trimester',
        label: _('CaseData.trimester'),
        options: optionsTrimester,
        newLine: true,
        dependingOn: 'pregnant',
        dependingOnValues: ['YES'],
      },
    ],
  },
  {
    id: 'vaccination',
    title: _('Vaccination'),
    required: false,
    fields: [
      {
        ...FORM_DATA_SELECT,
        key: 'vaccination',
        label: _('CaseData.vaccination'),
        options: optionsVaccinationStatus,
      },
      {
        ...FORM_DATA_NUMBER,
        key: 'vaccinationDoses',
        label: _('CaseData.vaccinationDoses'),
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_DATE,
        key: 'firstVaccinationDate',
        hint: _('CaseData.firstVaccinationDate'),
        newLine: true,
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_DATE,
        key: 'CaseData.lastVaccinationDate',
        hint: _('Last vaccination'),
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_SELECT,
        key: 'vaccinationInfoSource',
        label: _('CaseData.vaccinationInfoSource'),
        options: optionsVaccinationSource,
        newLine: true,
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_SELECT,
        key: 'vaccineName',
        label: _('CaseData.vaccineName'),
        options: optionsVaccineName,
        newLine: true,
        className: 'size-large',
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_SELECT,
        key: 'vaccineManufacturer',
        label: _('CaseData.vaccineManufacturer'),
        options: optionsVaccineManufacturer,
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_INPUT,
        key: 'vaccineInn',
        label: _('CaseData.vaccineInn'),
        newLine: true,
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_INPUT,
        key: 'vaccineBatchNumber',
        label: _('CaseData.vaccineBatchNumber'),
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_INPUT,
        key: 'vaccineUniiCode',
        label: _('CaseData.vaccineUniiCode'),
        newLine: true,
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
      {
        ...FORM_DATA_INPUT,
        key: 'vaccineAtcCode',
        label: _('CaseData.vaccineAtcCode'),
        dependingOn: 'vaccination',
        dependingOnValues: ['VACCINATED'],
      },
    ],
  },
  {
    id: 'work',
    title: _('CaseData.work'),
    required: false,
    fields: [
      {
        ...FORM_DATA_RADIO,
        key: 'prohibitionToWork',
        label: _('CaseData.prohibitionToWork'),
        options: optionsYesNoUnknown,
      },
      {
        ...FORM_DATA_DATE,
        key: 'prohibitionToWorkFrom',
        label: ' ',
        hint: _('CaseData.prohibitionToWorkFrom'),
        dependingOn: 'prohibitionToWork',
        dependingOnValues: ['YES'],
      },
      {
        ...FORM_DATA_DATE,
        key: 'prohibitionToWorkUntil',
        label: ' ',
        hint: _('CaseData.prohibitionToWorkUntil'),
        dependingOn: 'prohibitionToWork',
        dependingOnValues: ['YES'],
      },
    ],
  },
  {
    id: 'surveillance',
    title: _('CaseData.surveillance'),
    required: false,
    fields: [
      {
        ...FORM_DATA_SELECT,
        key: 'surveillanceOfficer',
        label: _('CaseData.surveillanceOfficer'),
        options: [
          {
            key: 'default',
            value: 'Default',
          },
        ],
        className: 'size-large',
      },
      {
        ...FORM_DATA_INPUT,
        key: 'clinicianName',
        label: _('CaseData.clinicianName'),
        newLine: true,
        className: 'size-large',
      },
      {
        ...FORM_DATA_INPUT,
        key: 'clinicianPhone',
        label: _('CaseData.clinicianPhone'),
        newLine: true,
        className: 'size-large',
      },
      {
        ...FORM_DATA_INPUT,
        key: 'clinicianEmail',
        label: _('CaseData.clinicianEmail'),
        newLine: true,
        className: 'size-large',
      },
    ],
  },
  {
    id: 'followupStatus',
    title: '',
    required: false,
    anchor: 'followup_status',
    anchorLabel: _('CaseData.followUpStatus'),
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-follow-up-status',
        className: 'size-large push-right',
      },
      {
        ...FORM_DATA_NULL,
        key: 'followUpStatus',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'overwriteFollowUpUntil',
        label: _('CaseData.overwriteFollowUpUntil'),
        newLine: true,
      },
      {
        ...FORM_DATA_DATE,
        key: 'followUpUntil',
        dependingOn: _('overwriteFollowUpUntil'),
      },
      {
        ...FORM_DATA_INPUT,
        key: 'followUpComment',
        label: _('CaseData.followUpComment'),
        newLine: true,
        className: 'size-full',
      },
    ],
  },
  {
    id: 'paperForm',
    title: '',
    required: false,
    anchor: 'paper_form',
    anchorLabel: _('CaseData.paperForm'),
    fields: [
      {
        ...FORM_DATA_DATE,
        key: 'districtLevelDate',
        label: _('CaseData.districtLevelDate'),
        className: 'size-medium',
      },
      {
        ...FORM_DATA_DATE,
        key: 'regionLevelDate',
        label: _('CaseData.regionLevelDate'),
        newLine: true,
        className: 'size-medium',
      },
      {
        ...FORM_DATA_DATE,
        key: 'nationalLevelDate',
        label: _('CaseData.nationalLevelDate'),
        newLine: true,
        className: 'size-medium',
      },
    ],
  },
  {
    id: 'comment',
    title: '',
    required: false,
    anchor: 'general_comment',
    anchorLabel: _('CaseData.additionalDetails'),
    fields: [
      {
        ...FORM_DATA_TEXTAREA,
        key: 'additionalDetails',
        label: _('Your comment here'),
      },
    ],
  },
];
