import { FormBase } from '../../../shared/dynamic-form/types/form-element-base';
import {
  FORM_DATA_INPUT,
  FORM_DATA_CHECKBOX,
  FORM_DATA_WIDGET,
  FORM_DATA_NULL,
} from '../../../app.constants';

export const FORM_DATA_EXPORT_CONFIGURATION: FormBase<any>[] = [
  {
    id: 'export',
    title: 'captions.export',
    required: true,
    fields: [
      {
        ...FORM_DATA_NULL,
        key: 'exportType',
        className: 'hidden',
      },
      {
        ...FORM_DATA_INPUT,
        key: 'name',
        label: 'captions.ExportConfiguration.NAME',
        validation: ['required'],
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sharedToPublic',
        label: 'captions.ExportConfiguration.sharedToPublic',
        newLine: true,
      },
    ],
  },
  {
    id: 'groupSelect',
    title: 'Customize export',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          info: 'strings.infoEditExportConfiguration',
          sections: [
            'coreData',
            'sensitiveData',
            'personData',
            'epiData',
            'vaccinationData',
            'followUpData',
            'additionalData',
            'eventData',
          ],
        },
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'coreData',
    title: 'enum.ExportGroupType.CORE',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['coreData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'uuid',
        label: 'captions.Contact.uuid',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'externalID',
        label: 'captions.Contact.externalID',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sourceCaseUuid',
        label: 'captions.ContactExport.sourceCaseUuid',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'maxSourceCaseClassification',
        label: 'captions.CaseExport.maxSourceCaseClassification',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'disease',
        label: 'captions.disease',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'diseaseDetails',
        label: 'captions.Contact.diseaseDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'contactClassification',
        label: 'captions.Contact.contactClassification',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'multiDayContact',
        label: 'captions.Contact.multiDayContact',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'firstContactDate',
        label: 'captions.Contact.firstContactDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastContactDate',
        label: 'captions.Contact.lastContactDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'creationDate',
        label: 'captions.creationDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'reportDateTime',
        label: 'captions.Contact.reportDateTime',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'region',
        label: 'captions.Contact.region',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'district',
        label: 'captions.Contact.district',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'community',
        label: 'captions.Contact.community',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'contactIdentificationSource',
        label: 'captions.Contact.contactIdentificationSource',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'contactProximity',
        label: 'captions.Contact.contactProximity',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'contactStatus',
        label: 'captions.Contact.contactStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'completeness',
        label: 'captions.CaseData.completeness',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'externalToken',
        label: 'captions.Contact.externalToken',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'internalToken',
        label: 'captions.Contact.internalToken',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'sensitiveData',
    title: 'enum.ExportGroupType.SENSITIVE',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['sensitiveData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'firstName',
        label: 'captions.ContactExport.firstName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastName',
        label: 'captions.ContactExport.lastName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'birthdate',
        label: 'captions.Person.birthdate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'approximateAge',
        label: 'captions.Person.approximateAge',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'deathDate',
        label: 'captions.Person.deathDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.region',
        label: 'captions.Contact.region',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.district',
        label: 'captions.Contact.district',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.community',
        label: 'captions.Contact.community',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.city',
        label: 'captions.city',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.street',
        label: 'captions.Location.street',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.houseNumber',
        label: 'captions.Location.houseNumber',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.additionalInformation',
        label: 'captions.Location.additionalInformation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'person.postalCode',
        label: 'captions.Location.postalCode',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'facility',
        label: 'captions.Location.facility',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'facilityDetails',
        label: 'captions.Location.facilityDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'phone',
        label: 'captions.Person.phone',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'phoneOwner',
        label: 'captions.Person.phoneOwner',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'emailAddress',
        label: 'captions.Person.emailAddress',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherContactDetails',
        label: 'captions.Person.otherContactDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'birthName',
        label: 'captions.Person.birthName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'birthCountry',
        label: 'captions.Person.birthCountry',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'citizenship',
        label: 'captions.Person.citizenship',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'personData',
    title: 'enum.ExportGroupType.PERSON',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['personData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'salutation',
        label: 'captions.Person.salutation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherSalutation',
        label: 'captions.Person.otherSalutation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'sex',
        label: 'captions.Person.sex',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'presentCondition',
        label: 'captions.Person.presentCondition',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'occupationType',
        label: 'captions.Person.occupationType',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'occupationDetails',
        label: 'captions.Person.occupationDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'armedForcesRelationType',
        label: 'captions.Person.armedForcesRelationType',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'epiData',
    title: 'enum.ExportGroupType.EPIDEMIOLOGICAL',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['epiData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'traveled',
        label: 'captions.ContactExport.traveled',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'travelHistory',
        label: 'captions.ContactExport.travelHistory',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'burialAttended',
        label: 'captions.ContactExport.burialAttended',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'contactWithSourceCaseKnown',
        label: 'captions.EpiData.contactWithSourceCaseKnown',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'vaccinationData',
    title: 'enum.ExportGroupType.VACCINATION',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['vaccinationData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccinationStatus',
        label: 'captions.Contact.vaccinationStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'numberOfDoses',
        label: 'captions.Immunization.numberOfDoses',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccinationInfoSource',
        label: 'captions.Vaccination.vaccinationInfoSource',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'firstVaccinationDate',
        label: 'captions.Immunization.firstVaccinationDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastVaccinationDate',
        label: 'captions.Immunization.lastVaccinationDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineName',
        label: 'captions.Vaccination.vaccineName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherVaccineName',
        label: 'captions.Vaccination.otherVaccineName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineManufacturer',
        label: 'captions.Vaccination.vaccineManufacturer',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'otherVaccineManufacturer',
        label: 'captions.Vaccination.otherVaccineManufacturer',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineInn',
        label: 'captions.Vaccination.vaccineInn',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineBatchNumber',
        label: 'captions.Vaccination.vaccineBatchNumber',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineUniiCode',
        label: 'captions.Vaccination.vaccineUniiCode',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'vaccineAtcCode',
        label: 'captions.Vaccination.vaccineAtcCode',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'followUpData',
    title: 'enum.ExportGroupType.FOLLOW_UP',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['followUpData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'followUpStatus',
        label: 'captions.Contact.followUpStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'followUpUntil',
        label: 'captions.Contact.followUpUntil',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'numberOfVisits',
        label: 'captions.Contact.numberOfVisits',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastCooperativeVisitSymptomatic',
        label: 'captions.ContactExport.lastCooperativeVisitSymptomatic',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastCooperativeVisitDate',
        label: 'captions.ContactExport.lastCooperativeVisitDate',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'lastCooperativeVisitSymptoms',
        label: 'captions.ContactExport.lastCooperativeVisitSymptoms',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'additionalData',
    title: 'enum.ExportGroupType.ADDITIONAL',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['additionalData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'contactIdentificationSourceDetails',
        label: 'captions.Contact.contactIdentificationSourceDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'tracingApp',
        label: 'captions.Contact.tracingApp',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'tracingAppDetails',
        label: 'captions.Contact.tracingAppDetails',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'quarantineInformation',
        label: 'captions.ContactExport.quarantineInformation',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'prohibitionToWork',
        label: 'captions.Contact.prohibitionToWork',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'returningTraveler',
        label: 'captions.Contact.returningTraveler',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'reportingDistrict',
        label: 'captions.Contact.reportingDistrict',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'symptomJournalStatus',
        label: 'captions.Contact.symptomJournalStatus',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'reportingUserName',
        label: 'captions.ContactExport.reportingUserName',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'followUpStatusChangeUserName',
        label: 'captions.ContactExport.followUpStatusChangeUserName',
        className: 'fullwidth',
      },
    ],
  },
  {
    id: 'eventData',
    title: 'enum.ExportGroupType.EVENT',
    className: 'columns-lg-3 columns-md-2',
    fields: [
      {
        ...FORM_DATA_WIDGET,
        widget: 'app-group-select',
        widgetInfo: {
          sections: ['eventData'],
        },
        className: 'widget-fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'latestEventId',
        label: 'captions.Contact.latestEventId',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'latestEventTitle',
        label: 'captions.Contact.latestEventTitle',
        className: 'fullwidth',
      },
      {
        ...FORM_DATA_CHECKBOX,
        key: 'eventCount',
        label: 'captions.CaseData.eventCount',
        className: 'fullwidth',
      },
    ],
  },
];
